// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type CreateEventGatewayVirtualClusterProducePolicySkipRecordRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Virtual Cluster.
	VirtualClusterID string `pathParam:"style=simple,explode=false,name=virtualClusterId"`
	// When specified, it sets the ID of the parent policy.
	ParentPolicyID               *string                              `queryParam:"style=form,explode=true,name=parent_policy_id"`
	EventGatewaySkipRecordPolicy *shared.EventGatewaySkipRecordPolicy `request:"mediaType=application/json"`
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordRequest) GetGatewayID() string {
	if c == nil {
		return ""
	}
	return c.GatewayID
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordRequest) GetVirtualClusterID() string {
	if c == nil {
		return ""
	}
	return c.VirtualClusterID
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordRequest) GetParentPolicyID() *string {
	if c == nil {
		return nil
	}
	return c.ParentPolicyID
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordRequest) GetEventGatewaySkipRecordPolicy() *shared.EventGatewaySkipRecordPolicy {
	if c == nil {
		return nil
	}
	return c.EventGatewaySkipRecordPolicy
}

type CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	EventGatewayPolicy *shared.EventGatewayPolicy
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetEventGatewayPolicy() *shared.EventGatewayPolicy {
	if c == nil {
		return nil
	}
	return c.EventGatewayPolicy
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetBadRequestError() *shared.BadRequestError {
	if c == nil {
		return nil
	}
	return c.BadRequestError
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if c == nil {
		return nil
	}
	return c.UnauthorizedError
}

func (c *CreateEventGatewayVirtualClusterProducePolicySkipRecordResponse) GetForbiddenError() *shared.ForbiddenError {
	if c == nil {
		return nil
	}
	return c.ForbiddenError
}
