// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type CreateEventGatewayBackendClusterRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The request schema for creating a backend cluster.
	CreateBackendClusterRequest *shared.CreateBackendClusterRequest `request:"mediaType=application/json"`
}

func (o *CreateEventGatewayBackendClusterRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *CreateEventGatewayBackendClusterRequest) GetCreateBackendClusterRequest() *shared.CreateBackendClusterRequest {
	if o == nil {
		return nil
	}
	return o.CreateBackendClusterRequest
}

type CreateEventGatewayBackendClusterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	BackendCluster *shared.BackendCluster
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
}

func (o *CreateEventGatewayBackendClusterResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateEventGatewayBackendClusterResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateEventGatewayBackendClusterResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateEventGatewayBackendClusterResponse) GetBackendCluster() *shared.BackendCluster {
	if o == nil {
		return nil
	}
	return o.BackendCluster
}

func (o *CreateEventGatewayBackendClusterResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *CreateEventGatewayBackendClusterResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *CreateEventGatewayBackendClusterResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}
