// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type DeleteZoneIngressRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// name of the ZoneIngress
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (d *DeleteZoneIngressRequest) GetCpID() string {
	if d == nil {
		return ""
	}
	return d.CpID
}

func (d *DeleteZoneIngressRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type DeleteZoneIngressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneIngressDeleteSuccessResponse *shared.ZoneIngressDeleteSuccessResponse
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (d *DeleteZoneIngressResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteZoneIngressResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteZoneIngressResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteZoneIngressResponse) GetZoneIngressDeleteSuccessResponse() *shared.ZoneIngressDeleteSuccessResponse {
	if d == nil {
		return nil
	}
	return d.ZoneIngressDeleteSuccessResponse
}

func (d *DeleteZoneIngressResponse) GetNotFoundError() *shared.NotFoundError {
	if d == nil {
		return nil
	}
	return d.NotFoundError
}
