// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetAiGatewayCaCertificateRequest struct {
	// The unique ID of the AI Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The unique ID of the AI Gateway CA Certificate.
	CaCertificateID string `pathParam:"style=simple,explode=false,name=caCertificateIdOrName"`
}

func (g *GetAiGatewayCaCertificateRequest) GetGatewayID() string {
	if g == nil {
		return ""
	}
	return g.GatewayID
}

func (g *GetAiGatewayCaCertificateRequest) GetCaCertificateID() string {
	if g == nil {
		return ""
	}
	return g.CaCertificateID
}

type GetAiGatewayCaCertificateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A successful response returning an AI Gateway CA Certificate.
	AIGatewayCACertificate *shared.AIGatewayCACertificate
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	// Too Many Requests
	TooManyRequestsError *shared.TooManyRequestsError
}

func (g *GetAiGatewayCaCertificateResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAiGatewayCaCertificateResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAiGatewayCaCertificateResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAiGatewayCaCertificateResponse) GetAIGatewayCACertificate() *shared.AIGatewayCACertificate {
	if g == nil {
		return nil
	}
	return g.AIGatewayCACertificate
}

func (g *GetAiGatewayCaCertificateResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if g == nil {
		return nil
	}
	return g.UnauthorizedError
}

func (g *GetAiGatewayCaCertificateResponse) GetForbiddenError() *shared.ForbiddenError {
	if g == nil {
		return nil
	}
	return g.ForbiddenError
}

func (g *GetAiGatewayCaCertificateResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}

func (g *GetAiGatewayCaCertificateResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if g == nil {
		return nil
	}
	return g.TooManyRequestsError
}
