// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetEventGatewayVirtualClusterConsumePolicySkipRecordRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Virtual Cluster.
	VirtualClusterID string `pathParam:"style=simple,explode=false,name=virtualClusterId"`
	// The UUID of the policy.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordRequest) GetVirtualClusterID() string {
	if o == nil {
		return ""
	}
	return o.VirtualClusterID
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

type GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A single consume policy object.
	EventGatewayPolicy *shared.EventGatewayPolicy
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetEventGatewayPolicy() *shared.EventGatewayPolicy {
	if o == nil {
		return nil
	}
	return o.EventGatewayPolicy
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *GetEventGatewayVirtualClusterConsumePolicySkipRecordResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}
