// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetEventGatewayStaticKeyRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the static key.
	StaticKeyID string `pathParam:"style=simple,explode=false,name=staticKeyId"`
}

func (o *GetEventGatewayStaticKeyRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *GetEventGatewayStaticKeyRequest) GetStaticKeyID() string {
	if o == nil {
		return ""
	}
	return o.StaticKeyID
}

type GetEventGatewayStaticKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A single static key.
	EventGatewayStaticKey *shared.EventGatewayStaticKey
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (o *GetEventGatewayStaticKeyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEventGatewayStaticKeyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEventGatewayStaticKeyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEventGatewayStaticKeyResponse) GetEventGatewayStaticKey() *shared.EventGatewayStaticKey {
	if o == nil {
		return nil
	}
	return o.EventGatewayStaticKey
}

func (o *GetEventGatewayStaticKeyResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *GetEventGatewayStaticKeyResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *GetEventGatewayStaticKeyResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}
