// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetEventGatewayListenerPolicyTLSServerRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Event Gateway Listener.
	EventGatewayListenerID string `pathParam:"style=simple,explode=false,name=eventGatewayListenerId"`
	// The UUID of the policy.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
}

func (o *GetEventGatewayListenerPolicyTLSServerRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *GetEventGatewayListenerPolicyTLSServerRequest) GetEventGatewayListenerID() string {
	if o == nil {
		return ""
	}
	return o.EventGatewayListenerID
}

func (o *GetEventGatewayListenerPolicyTLSServerRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

type GetEventGatewayListenerPolicyTLSServerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A single policy object.
	EventGatewayListenerPolicy *shared.EventGatewayListenerPolicy
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetEventGatewayListenerPolicy() *shared.EventGatewayListenerPolicy {
	if o == nil {
		return nil
	}
	return o.EventGatewayListenerPolicy
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *GetEventGatewayListenerPolicyTLSServerResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}
