// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

// GetMeshOpenTelemetryBackendListQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshOpenTelemetryBackendListQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshOpenTelemetryBackendListQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshOpenTelemetryBackendListQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshOpenTelemetryBackendListRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshOpenTelemetryBackendListQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
}

func (g GetMeshOpenTelemetryBackendListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshOpenTelemetryBackendListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshOpenTelemetryBackendListRequest) GetCpID() string {
	if g == nil {
		return ""
	}
	return g.CpID
}

func (g *GetMeshOpenTelemetryBackendListRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshOpenTelemetryBackendListRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshOpenTelemetryBackendListRequest) GetFilter() *GetMeshOpenTelemetryBackendListQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

func (g *GetMeshOpenTelemetryBackendListRequest) GetMesh() string {
	if g == nil {
		return ""
	}
	return g.Mesh
}

type GetMeshOpenTelemetryBackendListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshOpenTelemetryBackendList *shared.MeshOpenTelemetryBackendList
}

func (g *GetMeshOpenTelemetryBackendListResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshOpenTelemetryBackendListResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshOpenTelemetryBackendListResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshOpenTelemetryBackendListResponse) GetMeshOpenTelemetryBackendList() *shared.MeshOpenTelemetryBackendList {
	if g == nil {
		return nil
	}
	return g.MeshOpenTelemetryBackendList
}
