// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetZoneEgressRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// name of the ZoneEgress
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetZoneEgressRequest) GetCpID() string {
	if g == nil {
		return ""
	}
	return g.CpID
}

func (g *GetZoneEgressRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetZoneEgressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneEgressItem *shared.ZoneEgressItem
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (g *GetZoneEgressResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetZoneEgressResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetZoneEgressResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetZoneEgressResponse) GetZoneEgressItem() *shared.ZoneEgressItem {
	if g == nil {
		return nil
	}
	return g.ZoneEgressItem
}

func (g *GetZoneEgressResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
