// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type GetZoneIngressRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// name of the ZoneIngress
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetZoneIngressRequest) GetCpID() string {
	if g == nil {
		return ""
	}
	return g.CpID
}

func (g *GetZoneIngressRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetZoneIngressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneIngressItem *shared.ZoneIngressItem
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (g *GetZoneIngressResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetZoneIngressResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetZoneIngressResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetZoneIngressResponse) GetZoneIngressItem() *shared.ZoneIngressItem {
	if g == nil {
		return nil
	}
	return g.ZoneIngressItem
}

func (g *GetZoneIngressResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
