// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type PutMeshZoneAddressRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the MeshZoneAddress
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	MeshZoneAddressItem shared.MeshZoneAddressItemInput `request:"mediaType=application/json"`
}

func (p *PutMeshZoneAddressRequest) GetCpID() string {
	if p == nil {
		return ""
	}
	return p.CpID
}

func (p *PutMeshZoneAddressRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PutMeshZoneAddressRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutMeshZoneAddressRequest) GetMeshZoneAddressItem() shared.MeshZoneAddressItemInput {
	if p == nil {
		return shared.MeshZoneAddressItemInput{}
	}
	return p.MeshZoneAddressItem
}

type PutMeshZoneAddressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshZoneAddressCreateOrUpdateSuccessResponse *shared.MeshZoneAddressCreateOrUpdateSuccessResponse
}

func (p *PutMeshZoneAddressResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutMeshZoneAddressResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutMeshZoneAddressResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutMeshZoneAddressResponse) GetMeshZoneAddressCreateOrUpdateSuccessResponse() *shared.MeshZoneAddressCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshZoneAddressCreateOrUpdateSuccessResponse
}
