// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type PutZoneIngressRequest struct {
	// Id of the Konnect resource
	CpID string `pathParam:"style=simple,explode=false,name=cpId"`
	// name of the ZoneIngress
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	ZoneIngressItem shared.ZoneIngressItem `request:"mediaType=application/json"`
}

func (p *PutZoneIngressRequest) GetCpID() string {
	if p == nil {
		return ""
	}
	return p.CpID
}

func (p *PutZoneIngressRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutZoneIngressRequest) GetZoneIngressItem() shared.ZoneIngressItem {
	if p == nil {
		return shared.ZoneIngressItem{}
	}
	return p.ZoneIngressItem
}

type PutZoneIngressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneIngressCreateOrUpdateSuccessResponse *shared.ZoneIngressCreateOrUpdateSuccessResponse
}

func (p *PutZoneIngressResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutZoneIngressResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutZoneIngressResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutZoneIngressResponse) GetZoneIngressCreateOrUpdateSuccessResponse() *shared.ZoneIngressCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.ZoneIngressCreateOrUpdateSuccessResponse
}
