// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type UpdateEventGatewayVirtualClusterRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Virtual Cluster.
	VirtualClusterID string `pathParam:"style=simple,explode=false,name=virtualClusterId"`
	// The request schema for updating a virtual cluster.
	UpdateVirtualClusterRequest *shared.UpdateVirtualClusterRequest `request:"mediaType=application/json"`
}

func (o *UpdateEventGatewayVirtualClusterRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *UpdateEventGatewayVirtualClusterRequest) GetVirtualClusterID() string {
	if o == nil {
		return ""
	}
	return o.VirtualClusterID
}

func (o *UpdateEventGatewayVirtualClusterRequest) GetUpdateVirtualClusterRequest() *shared.UpdateVirtualClusterRequest {
	if o == nil {
		return nil
	}
	return o.UpdateVirtualClusterRequest
}

type UpdateEventGatewayVirtualClusterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated virtual cluster object.
	VirtualCluster *shared.VirtualCluster
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetVirtualCluster() *shared.VirtualCluster {
	if o == nil {
		return nil
	}
	return o.VirtualCluster
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *UpdateEventGatewayVirtualClusterResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}
