// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
	"net/http"
)

type UpdateEventGatewayRequest struct {
	// The UUID of your Gateway.
	GatewayID            string                      `pathParam:"style=simple,explode=false,name=gatewayId"`
	UpdateGatewayRequest shared.UpdateGatewayRequest `request:"mediaType=application/json"`
}

func (o *UpdateEventGatewayRequest) GetGatewayID() string {
	if o == nil {
		return ""
	}
	return o.GatewayID
}

func (o *UpdateEventGatewayRequest) GetUpdateGatewayRequest() shared.UpdateGatewayRequest {
	if o == nil {
		return shared.UpdateGatewayRequest{}
	}
	return o.UpdateGatewayRequest
}

type UpdateEventGatewayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A response to updating a gateway.
	EventGatewayInfo *shared.EventGatewayInfo
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	// Internal
	BaseError *shared.BaseError
}

func (o *UpdateEventGatewayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateEventGatewayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateEventGatewayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateEventGatewayResponse) GetEventGatewayInfo() *shared.EventGatewayInfo {
	if o == nil {
		return nil
	}
	return o.EventGatewayInfo
}

func (o *UpdateEventGatewayResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *UpdateEventGatewayResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *UpdateEventGatewayResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *UpdateEventGatewayResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}

func (o *UpdateEventGatewayResponse) GetBaseError() *shared.BaseError {
	if o == nil {
		return nil
	}
	return o.BaseError
}
