// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Subjects struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

func (s *Subjects) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Subjects) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

type AccessRoleBindingItem struct {
	Labels   map[string]string `json:"labels,omitempty"`
	Name     string            `json:"name"`
	Roles    []string          `json:"roles"`
	Subjects []Subjects        `json:"subjects"`
	Type     string            `json:"type"`
}

func (a *AccessRoleBindingItem) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AccessRoleBindingItem) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AccessRoleBindingItem) GetRoles() []string {
	if a == nil {
		return nil
	}
	return a.Roles
}

func (a *AccessRoleBindingItem) GetSubjects() []Subjects {
	if a == nil {
		return nil
	}
	return a.Subjects
}

func (a *AccessRoleBindingItem) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}
