// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AddAIGatewayConsumerToGroupRequest - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
type AddAIGatewayConsumerToGroupRequest struct {
	// The ID of the consumer to add to the group.
	ConsumerID string `json:"consumer"`
}

func (a *AddAIGatewayConsumerToGroupRequest) GetConsumerID() string {
	if a == nil {
		return ""
	}
	return a.ConsumerID
}
