// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AgenticMetrics string

const (
	AgenticMetricsA2aLatencyAverage      AgenticMetrics = "a2a_latency_average"
	AgenticMetricsA2aResponseSizeSum     AgenticMetrics = "a2a_response_size_sum"
	AgenticMetricsErrorRate              AgenticMetrics = "error_rate"
	AgenticMetricsKongLatencyAverage     AgenticMetrics = "kong_latency_average"
	AgenticMetricsKongLatencyP50         AgenticMetrics = "kong_latency_p50"
	AgenticMetricsKongLatencyP95         AgenticMetrics = "kong_latency_p95"
	AgenticMetricsKongLatencyP99         AgenticMetrics = "kong_latency_p99"
	AgenticMetricsMcpResponseBodySizeSum AgenticMetrics = "mcp_response_body_size_sum"
	AgenticMetricsRequestCount           AgenticMetrics = "request_count"
	AgenticMetricsRequestPerMinute       AgenticMetrics = "request_per_minute"
	AgenticMetricsRequestSizeAverage     AgenticMetrics = "request_size_average"
	AgenticMetricsRequestSizeP50         AgenticMetrics = "request_size_p50"
	AgenticMetricsRequestSizeP95         AgenticMetrics = "request_size_p95"
	AgenticMetricsRequestSizeP99         AgenticMetrics = "request_size_p99"
	AgenticMetricsRequestSizeSum         AgenticMetrics = "request_size_sum"
	AgenticMetricsResponseLatencyAverage AgenticMetrics = "response_latency_average"
	AgenticMetricsResponseLatencyP50     AgenticMetrics = "response_latency_p50"
	AgenticMetricsResponseLatencyP95     AgenticMetrics = "response_latency_p95"
	AgenticMetricsResponseLatencyP99     AgenticMetrics = "response_latency_p99"
	AgenticMetricsResponseSizeAverage    AgenticMetrics = "response_size_average"
	AgenticMetricsResponseSizeP50        AgenticMetrics = "response_size_p50"
	AgenticMetricsResponseSizeP95        AgenticMetrics = "response_size_p95"
	AgenticMetricsResponseSizeP99        AgenticMetrics = "response_size_p99"
	AgenticMetricsResponseSizeSum        AgenticMetrics = "response_size_sum"
	AgenticMetricsUpstreamLatencyAverage AgenticMetrics = "upstream_latency_average"
	AgenticMetricsUpstreamLatencyP50     AgenticMetrics = "upstream_latency_p50"
	AgenticMetricsUpstreamLatencyP95     AgenticMetrics = "upstream_latency_p95"
	AgenticMetricsUpstreamLatencyP99     AgenticMetrics = "upstream_latency_p99"
)

func (e AgenticMetrics) ToPointer() *AgenticMetrics {
	return &e
}
func (e *AgenticMetrics) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "a2a_latency_average":
		fallthrough
	case "a2a_response_size_sum":
		fallthrough
	case "error_rate":
		fallthrough
	case "kong_latency_average":
		fallthrough
	case "kong_latency_p50":
		fallthrough
	case "kong_latency_p95":
		fallthrough
	case "kong_latency_p99":
		fallthrough
	case "mcp_response_body_size_sum":
		fallthrough
	case "request_count":
		fallthrough
	case "request_per_minute":
		fallthrough
	case "request_size_average":
		fallthrough
	case "request_size_p50":
		fallthrough
	case "request_size_p95":
		fallthrough
	case "request_size_p99":
		fallthrough
	case "request_size_sum":
		fallthrough
	case "response_latency_average":
		fallthrough
	case "response_latency_p50":
		fallthrough
	case "response_latency_p95":
		fallthrough
	case "response_latency_p99":
		fallthrough
	case "response_size_average":
		fallthrough
	case "response_size_p50":
		fallthrough
	case "response_size_p95":
		fallthrough
	case "response_size_p99":
		fallthrough
	case "response_size_sum":
		fallthrough
	case "upstream_latency_average":
		fallthrough
	case "upstream_latency_p50":
		fallthrough
	case "upstream_latency_p95":
		fallthrough
	case "upstream_latency_p99":
		*e = AgenticMetrics(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgenticMetrics: %v", v)
	}
}
