// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type AgenticFiltersType string

const (
	AgenticFiltersTypeA2aContextID              AgenticFiltersType = "a2a_context_id"
	AgenticFiltersTypeA2aError                  AgenticFiltersType = "a2a_error"
	AgenticFiltersTypeA2aMethod                 AgenticFiltersType = "a2a_method"
	AgenticFiltersTypeA2aTaskID                 AgenticFiltersType = "a2a_task_id"
	AgenticFiltersTypeAPI                       AgenticFiltersType = "api"
	AgenticFiltersTypeAPIPackage                AgenticFiltersType = "api_package"
	AgenticFiltersTypeAPIProduct                AgenticFiltersType = "api_product"
	AgenticFiltersTypeAPIProductVersion         AgenticFiltersType = "api_product_version"
	AgenticFiltersTypeApplication               AgenticFiltersType = "application"
	AgenticFiltersTypeConsumer                  AgenticFiltersType = "consumer"
	AgenticFiltersTypeControlPlane              AgenticFiltersType = "control_plane"
	AgenticFiltersTypeControlPlaneGroup         AgenticFiltersType = "control_plane_group"
	AgenticFiltersTypeCountryCode               AgenticFiltersType = "country_code"
	AgenticFiltersTypeDataPlaneNode             AgenticFiltersType = "data_plane_node"
	AgenticFiltersTypeDataPlaneNodeVersion      AgenticFiltersType = "data_plane_node_version"
	AgenticFiltersTypeGatewayService            AgenticFiltersType = "gateway_service"
	AgenticFiltersTypeMcpError                  AgenticFiltersType = "mcp_error"
	AgenticFiltersTypeMcpMethod                 AgenticFiltersType = "mcp_method"
	AgenticFiltersTypeMcpSessionID              AgenticFiltersType = "mcp_session_id"
	AgenticFiltersTypeMcpToolName               AgenticFiltersType = "mcp_tool_name"
	AgenticFiltersTypePortal                    AgenticFiltersType = "portal"
	AgenticFiltersTypeRealm                     AgenticFiltersType = "realm"
	AgenticFiltersTypeResponseSource            AgenticFiltersType = "response_source"
	AgenticFiltersTypeRoute                     AgenticFiltersType = "route"
	AgenticFiltersTypeStatusCode                AgenticFiltersType = "status_code"
	AgenticFiltersTypeStatusCodeGrouped         AgenticFiltersType = "status_code_grouped"
	AgenticFiltersTypeUpstreamStatusCode        AgenticFiltersType = "upstream_status_code"
	AgenticFiltersTypeUpstreamStatusCodeGrouped AgenticFiltersType = "upstream_status_code_grouped"
)

type AgenticFilters struct {
	MetricsA2aContextIDFilterByField              *MetricsA2aContextIDFilterByField              `queryParam:"inline" union:"member"`
	MetricsA2aErrorFilterByField                  *MetricsA2aErrorFilterByField                  `queryParam:"inline" union:"member"`
	MetricsA2aMethodFilterByField                 *MetricsA2aMethodFilterByField                 `queryParam:"inline" union:"member"`
	MetricsA2aTaskIDFilterByField                 *MetricsA2aTaskIDFilterByField                 `queryParam:"inline" union:"member"`
	MetricsAPIFilterByField                       *MetricsAPIFilterByField                       `queryParam:"inline" union:"member"`
	MetricsAPIPackageFilterByField                *MetricsAPIPackageFilterByField                `queryParam:"inline" union:"member"`
	MetricsAPIProductFilterByField                *MetricsAPIProductFilterByField                `queryParam:"inline" union:"member"`
	MetricsAPIProductVersionFilterByField         *MetricsAPIProductVersionFilterByField         `queryParam:"inline" union:"member"`
	MetricsApplicationFilterByField               *MetricsApplicationFilterByField               `queryParam:"inline" union:"member"`
	MetricsConsumerFilterByField                  *MetricsConsumerFilterByField                  `queryParam:"inline" union:"member"`
	MetricsControlPlaneFilterByField              *MetricsControlPlaneFilterByField              `queryParam:"inline" union:"member"`
	MetricsControlPlaneGroupFilterByField         *MetricsControlPlaneGroupFilterByField         `queryParam:"inline" union:"member"`
	MetricsCountryCodeFilterByField               *MetricsCountryCodeFilterByField               `queryParam:"inline" union:"member"`
	MetricsDataPlaneNodeFilterByField             *MetricsDataPlaneNodeFilterByField             `queryParam:"inline" union:"member"`
	MetricsDataPlaneNodeVersionFilterByField      *MetricsDataPlaneNodeVersionFilterByField      `queryParam:"inline" union:"member"`
	MetricsGatewayServiceFilterByField            *MetricsGatewayServiceFilterByField            `queryParam:"inline" union:"member"`
	MetricsMcpErrorFilterByField                  *MetricsMcpErrorFilterByField                  `queryParam:"inline" union:"member"`
	MetricsMcpMethodFilterByField                 *MetricsMcpMethodFilterByField                 `queryParam:"inline" union:"member"`
	MetricsMcpSessionIDFilterByField              *MetricsMcpSessionIDFilterByField              `queryParam:"inline" union:"member"`
	MetricsMcpToolNameFilterByField               *MetricsMcpToolNameFilterByField               `queryParam:"inline" union:"member"`
	MetricsPortalFilterByField                    *MetricsPortalFilterByField                    `queryParam:"inline" union:"member"`
	MetricsRealmFilterByField                     *MetricsRealmFilterByField                     `queryParam:"inline" union:"member"`
	MetricsResponseSourceFilterByField            *MetricsResponseSourceFilterByField            `queryParam:"inline" union:"member"`
	MetricsRouteFilterByField                     *MetricsRouteFilterByField                     `queryParam:"inline" union:"member"`
	MetricsStatusCodeFilterByField                *MetricsStatusCodeFilterByField                `queryParam:"inline" union:"member"`
	MetricsStatusCodeGroupedFilterByField         *MetricsStatusCodeGroupedFilterByField         `queryParam:"inline" union:"member"`
	MetricsUpstreamStatusCodeFilterByField        *MetricsUpstreamStatusCodeFilterByField        `queryParam:"inline" union:"member"`
	MetricsUpstreamStatusCodeGroupedFilterByField *MetricsUpstreamStatusCodeGroupedFilterByField `queryParam:"inline" union:"member"`

	Type AgenticFiltersType
}

func CreateAgenticFiltersA2aContextID(a2aContextID MetricsA2aContextIDFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeA2aContextID

	return AgenticFilters{
		MetricsA2aContextIDFilterByField: &a2aContextID,
		Type:                             typ,
	}
}

func CreateAgenticFiltersA2aError(a2aError MetricsA2aErrorFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeA2aError

	return AgenticFilters{
		MetricsA2aErrorFilterByField: &a2aError,
		Type:                         typ,
	}
}

func CreateAgenticFiltersA2aMethod(a2aMethod MetricsA2aMethodFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeA2aMethod

	return AgenticFilters{
		MetricsA2aMethodFilterByField: &a2aMethod,
		Type:                          typ,
	}
}

func CreateAgenticFiltersA2aTaskID(a2aTaskID MetricsA2aTaskIDFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeA2aTaskID

	return AgenticFilters{
		MetricsA2aTaskIDFilterByField: &a2aTaskID,
		Type:                          typ,
	}
}

func CreateAgenticFiltersAPI(api MetricsAPIFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeAPI

	return AgenticFilters{
		MetricsAPIFilterByField: &api,
		Type:                    typ,
	}
}

func CreateAgenticFiltersAPIPackage(apiPackage MetricsAPIPackageFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeAPIPackage

	return AgenticFilters{
		MetricsAPIPackageFilterByField: &apiPackage,
		Type:                           typ,
	}
}

func CreateAgenticFiltersAPIProduct(apiProduct MetricsAPIProductFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeAPIProduct

	return AgenticFilters{
		MetricsAPIProductFilterByField: &apiProduct,
		Type:                           typ,
	}
}

func CreateAgenticFiltersAPIProductVersion(apiProductVersion MetricsAPIProductVersionFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeAPIProductVersion

	return AgenticFilters{
		MetricsAPIProductVersionFilterByField: &apiProductVersion,
		Type:                                  typ,
	}
}

func CreateAgenticFiltersApplication(application MetricsApplicationFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeApplication

	return AgenticFilters{
		MetricsApplicationFilterByField: &application,
		Type:                            typ,
	}
}

func CreateAgenticFiltersConsumer(consumer MetricsConsumerFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeConsumer

	return AgenticFilters{
		MetricsConsumerFilterByField: &consumer,
		Type:                         typ,
	}
}

func CreateAgenticFiltersControlPlane(controlPlane MetricsControlPlaneFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeControlPlane

	return AgenticFilters{
		MetricsControlPlaneFilterByField: &controlPlane,
		Type:                             typ,
	}
}

func CreateAgenticFiltersControlPlaneGroup(controlPlaneGroup MetricsControlPlaneGroupFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeControlPlaneGroup

	return AgenticFilters{
		MetricsControlPlaneGroupFilterByField: &controlPlaneGroup,
		Type:                                  typ,
	}
}

func CreateAgenticFiltersCountryCode(countryCode MetricsCountryCodeFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeCountryCode

	return AgenticFilters{
		MetricsCountryCodeFilterByField: &countryCode,
		Type:                            typ,
	}
}

func CreateAgenticFiltersDataPlaneNode(dataPlaneNode MetricsDataPlaneNodeFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeDataPlaneNode

	return AgenticFilters{
		MetricsDataPlaneNodeFilterByField: &dataPlaneNode,
		Type:                              typ,
	}
}

func CreateAgenticFiltersDataPlaneNodeVersion(dataPlaneNodeVersion MetricsDataPlaneNodeVersionFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeDataPlaneNodeVersion

	return AgenticFilters{
		MetricsDataPlaneNodeVersionFilterByField: &dataPlaneNodeVersion,
		Type:                                     typ,
	}
}

func CreateAgenticFiltersGatewayService(gatewayService MetricsGatewayServiceFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeGatewayService

	return AgenticFilters{
		MetricsGatewayServiceFilterByField: &gatewayService,
		Type:                               typ,
	}
}

func CreateAgenticFiltersMcpError(mcpError MetricsMcpErrorFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeMcpError

	return AgenticFilters{
		MetricsMcpErrorFilterByField: &mcpError,
		Type:                         typ,
	}
}

func CreateAgenticFiltersMcpMethod(mcpMethod MetricsMcpMethodFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeMcpMethod

	return AgenticFilters{
		MetricsMcpMethodFilterByField: &mcpMethod,
		Type:                          typ,
	}
}

func CreateAgenticFiltersMcpSessionID(mcpSessionID MetricsMcpSessionIDFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeMcpSessionID

	return AgenticFilters{
		MetricsMcpSessionIDFilterByField: &mcpSessionID,
		Type:                             typ,
	}
}

func CreateAgenticFiltersMcpToolName(mcpToolName MetricsMcpToolNameFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeMcpToolName

	return AgenticFilters{
		MetricsMcpToolNameFilterByField: &mcpToolName,
		Type:                            typ,
	}
}

func CreateAgenticFiltersPortal(portal MetricsPortalFilterByField) AgenticFilters {
	typ := AgenticFiltersTypePortal

	return AgenticFilters{
		MetricsPortalFilterByField: &portal,
		Type:                       typ,
	}
}

func CreateAgenticFiltersRealm(realm MetricsRealmFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeRealm

	return AgenticFilters{
		MetricsRealmFilterByField: &realm,
		Type:                      typ,
	}
}

func CreateAgenticFiltersResponseSource(responseSource MetricsResponseSourceFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeResponseSource

	return AgenticFilters{
		MetricsResponseSourceFilterByField: &responseSource,
		Type:                               typ,
	}
}

func CreateAgenticFiltersRoute(route MetricsRouteFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeRoute

	return AgenticFilters{
		MetricsRouteFilterByField: &route,
		Type:                      typ,
	}
}

func CreateAgenticFiltersStatusCode(statusCode MetricsStatusCodeFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeStatusCode

	return AgenticFilters{
		MetricsStatusCodeFilterByField: &statusCode,
		Type:                           typ,
	}
}

func CreateAgenticFiltersStatusCodeGrouped(statusCodeGrouped MetricsStatusCodeGroupedFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeStatusCodeGrouped

	return AgenticFilters{
		MetricsStatusCodeGroupedFilterByField: &statusCodeGrouped,
		Type:                                  typ,
	}
}

func CreateAgenticFiltersUpstreamStatusCode(upstreamStatusCode MetricsUpstreamStatusCodeFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeUpstreamStatusCode

	return AgenticFilters{
		MetricsUpstreamStatusCodeFilterByField: &upstreamStatusCode,
		Type:                                   typ,
	}
}

func CreateAgenticFiltersUpstreamStatusCodeGrouped(upstreamStatusCodeGrouped MetricsUpstreamStatusCodeGroupedFilterByField) AgenticFilters {
	typ := AgenticFiltersTypeUpstreamStatusCodeGrouped

	return AgenticFilters{
		MetricsUpstreamStatusCodeGroupedFilterByField: &upstreamStatusCodeGrouped,
		Type: typ,
	}
}

func (u *AgenticFilters) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Field string `json:"field"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Field {
	case "a2a_context_id":
		metricsA2aContextIDFilterByField := new(MetricsA2aContextIDFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsA2aContextIDFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == a2a_context_id) type MetricsA2aContextIDFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsA2aContextIDFilterByField = metricsA2aContextIDFilterByField
		u.Type = AgenticFiltersTypeA2aContextID
		return nil
	case "a2a_error":
		metricsA2aErrorFilterByField := new(MetricsA2aErrorFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsA2aErrorFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == a2a_error) type MetricsA2aErrorFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsA2aErrorFilterByField = metricsA2aErrorFilterByField
		u.Type = AgenticFiltersTypeA2aError
		return nil
	case "a2a_method":
		metricsA2aMethodFilterByField := new(MetricsA2aMethodFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsA2aMethodFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == a2a_method) type MetricsA2aMethodFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsA2aMethodFilterByField = metricsA2aMethodFilterByField
		u.Type = AgenticFiltersTypeA2aMethod
		return nil
	case "a2a_task_id":
		metricsA2aTaskIDFilterByField := new(MetricsA2aTaskIDFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsA2aTaskIDFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == a2a_task_id) type MetricsA2aTaskIDFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsA2aTaskIDFilterByField = metricsA2aTaskIDFilterByField
		u.Type = AgenticFiltersTypeA2aTaskID
		return nil
	case "api":
		metricsAPIFilterByField := new(MetricsAPIFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsAPIFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == api) type MetricsAPIFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsAPIFilterByField = metricsAPIFilterByField
		u.Type = AgenticFiltersTypeAPI
		return nil
	case "api_package":
		metricsAPIPackageFilterByField := new(MetricsAPIPackageFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsAPIPackageFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == api_package) type MetricsAPIPackageFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsAPIPackageFilterByField = metricsAPIPackageFilterByField
		u.Type = AgenticFiltersTypeAPIPackage
		return nil
	case "api_product":
		metricsAPIProductFilterByField := new(MetricsAPIProductFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsAPIProductFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == api_product) type MetricsAPIProductFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsAPIProductFilterByField = metricsAPIProductFilterByField
		u.Type = AgenticFiltersTypeAPIProduct
		return nil
	case "api_product_version":
		metricsAPIProductVersionFilterByField := new(MetricsAPIProductVersionFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsAPIProductVersionFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == api_product_version) type MetricsAPIProductVersionFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsAPIProductVersionFilterByField = metricsAPIProductVersionFilterByField
		u.Type = AgenticFiltersTypeAPIProductVersion
		return nil
	case "application":
		metricsApplicationFilterByField := new(MetricsApplicationFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsApplicationFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == application) type MetricsApplicationFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsApplicationFilterByField = metricsApplicationFilterByField
		u.Type = AgenticFiltersTypeApplication
		return nil
	case "consumer":
		metricsConsumerFilterByField := new(MetricsConsumerFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsConsumerFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == consumer) type MetricsConsumerFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsConsumerFilterByField = metricsConsumerFilterByField
		u.Type = AgenticFiltersTypeConsumer
		return nil
	case "control_plane":
		metricsControlPlaneFilterByField := new(MetricsControlPlaneFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsControlPlaneFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == control_plane) type MetricsControlPlaneFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsControlPlaneFilterByField = metricsControlPlaneFilterByField
		u.Type = AgenticFiltersTypeControlPlane
		return nil
	case "control_plane_group":
		metricsControlPlaneGroupFilterByField := new(MetricsControlPlaneGroupFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsControlPlaneGroupFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == control_plane_group) type MetricsControlPlaneGroupFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsControlPlaneGroupFilterByField = metricsControlPlaneGroupFilterByField
		u.Type = AgenticFiltersTypeControlPlaneGroup
		return nil
	case "country_code":
		metricsCountryCodeFilterByField := new(MetricsCountryCodeFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsCountryCodeFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == country_code) type MetricsCountryCodeFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsCountryCodeFilterByField = metricsCountryCodeFilterByField
		u.Type = AgenticFiltersTypeCountryCode
		return nil
	case "data_plane_node":
		metricsDataPlaneNodeFilterByField := new(MetricsDataPlaneNodeFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == data_plane_node) type MetricsDataPlaneNodeFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsDataPlaneNodeFilterByField = metricsDataPlaneNodeFilterByField
		u.Type = AgenticFiltersTypeDataPlaneNode
		return nil
	case "data_plane_node_version":
		metricsDataPlaneNodeVersionFilterByField := new(MetricsDataPlaneNodeVersionFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeVersionFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == data_plane_node_version) type MetricsDataPlaneNodeVersionFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsDataPlaneNodeVersionFilterByField = metricsDataPlaneNodeVersionFilterByField
		u.Type = AgenticFiltersTypeDataPlaneNodeVersion
		return nil
	case "gateway_service":
		metricsGatewayServiceFilterByField := new(MetricsGatewayServiceFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsGatewayServiceFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == gateway_service) type MetricsGatewayServiceFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsGatewayServiceFilterByField = metricsGatewayServiceFilterByField
		u.Type = AgenticFiltersTypeGatewayService
		return nil
	case "mcp_error":
		metricsMcpErrorFilterByField := new(MetricsMcpErrorFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsMcpErrorFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == mcp_error) type MetricsMcpErrorFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsMcpErrorFilterByField = metricsMcpErrorFilterByField
		u.Type = AgenticFiltersTypeMcpError
		return nil
	case "mcp_method":
		metricsMcpMethodFilterByField := new(MetricsMcpMethodFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsMcpMethodFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == mcp_method) type MetricsMcpMethodFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsMcpMethodFilterByField = metricsMcpMethodFilterByField
		u.Type = AgenticFiltersTypeMcpMethod
		return nil
	case "mcp_session_id":
		metricsMcpSessionIDFilterByField := new(MetricsMcpSessionIDFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsMcpSessionIDFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == mcp_session_id) type MetricsMcpSessionIDFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsMcpSessionIDFilterByField = metricsMcpSessionIDFilterByField
		u.Type = AgenticFiltersTypeMcpSessionID
		return nil
	case "mcp_tool_name":
		metricsMcpToolNameFilterByField := new(MetricsMcpToolNameFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsMcpToolNameFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == mcp_tool_name) type MetricsMcpToolNameFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsMcpToolNameFilterByField = metricsMcpToolNameFilterByField
		u.Type = AgenticFiltersTypeMcpToolName
		return nil
	case "portal":
		metricsPortalFilterByField := new(MetricsPortalFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsPortalFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == portal) type MetricsPortalFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsPortalFilterByField = metricsPortalFilterByField
		u.Type = AgenticFiltersTypePortal
		return nil
	case "realm":
		metricsRealmFilterByField := new(MetricsRealmFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsRealmFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == realm) type MetricsRealmFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsRealmFilterByField = metricsRealmFilterByField
		u.Type = AgenticFiltersTypeRealm
		return nil
	case "response_source":
		metricsResponseSourceFilterByField := new(MetricsResponseSourceFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsResponseSourceFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == response_source) type MetricsResponseSourceFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsResponseSourceFilterByField = metricsResponseSourceFilterByField
		u.Type = AgenticFiltersTypeResponseSource
		return nil
	case "route":
		metricsRouteFilterByField := new(MetricsRouteFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsRouteFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == route) type MetricsRouteFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsRouteFilterByField = metricsRouteFilterByField
		u.Type = AgenticFiltersTypeRoute
		return nil
	case "status_code":
		metricsStatusCodeFilterByField := new(MetricsStatusCodeFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsStatusCodeFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == status_code) type MetricsStatusCodeFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsStatusCodeFilterByField = metricsStatusCodeFilterByField
		u.Type = AgenticFiltersTypeStatusCode
		return nil
	case "status_code_grouped":
		metricsStatusCodeGroupedFilterByField := new(MetricsStatusCodeGroupedFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsStatusCodeGroupedFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == status_code_grouped) type MetricsStatusCodeGroupedFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsStatusCodeGroupedFilterByField = metricsStatusCodeGroupedFilterByField
		u.Type = AgenticFiltersTypeStatusCodeGrouped
		return nil
	case "upstream_status_code":
		metricsUpstreamStatusCodeFilterByField := new(MetricsUpstreamStatusCodeFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsUpstreamStatusCodeFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == upstream_status_code) type MetricsUpstreamStatusCodeFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsUpstreamStatusCodeFilterByField = metricsUpstreamStatusCodeFilterByField
		u.Type = AgenticFiltersTypeUpstreamStatusCode
		return nil
	case "upstream_status_code_grouped":
		metricsUpstreamStatusCodeGroupedFilterByField := new(MetricsUpstreamStatusCodeGroupedFilterByField)
		if err := utils.UnmarshalJSON(data, &metricsUpstreamStatusCodeGroupedFilterByField, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Field == upstream_status_code_grouped) type MetricsUpstreamStatusCodeGroupedFilterByField within AgenticFilters: %w", string(data), err)
		}

		u.MetricsUpstreamStatusCodeGroupedFilterByField = metricsUpstreamStatusCodeGroupedFilterByField
		u.Type = AgenticFiltersTypeUpstreamStatusCodeGrouped
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgenticFilters", string(data))
}

func (u AgenticFilters) MarshalJSON() ([]byte, error) {
	if u.MetricsA2aContextIDFilterByField != nil {
		return utils.MarshalJSON(u.MetricsA2aContextIDFilterByField, "", true)
	}

	if u.MetricsA2aErrorFilterByField != nil {
		return utils.MarshalJSON(u.MetricsA2aErrorFilterByField, "", true)
	}

	if u.MetricsA2aMethodFilterByField != nil {
		return utils.MarshalJSON(u.MetricsA2aMethodFilterByField, "", true)
	}

	if u.MetricsA2aTaskIDFilterByField != nil {
		return utils.MarshalJSON(u.MetricsA2aTaskIDFilterByField, "", true)
	}

	if u.MetricsAPIFilterByField != nil {
		return utils.MarshalJSON(u.MetricsAPIFilterByField, "", true)
	}

	if u.MetricsAPIPackageFilterByField != nil {
		return utils.MarshalJSON(u.MetricsAPIPackageFilterByField, "", true)
	}

	if u.MetricsAPIProductFilterByField != nil {
		return utils.MarshalJSON(u.MetricsAPIProductFilterByField, "", true)
	}

	if u.MetricsAPIProductVersionFilterByField != nil {
		return utils.MarshalJSON(u.MetricsAPIProductVersionFilterByField, "", true)
	}

	if u.MetricsApplicationFilterByField != nil {
		return utils.MarshalJSON(u.MetricsApplicationFilterByField, "", true)
	}

	if u.MetricsConsumerFilterByField != nil {
		return utils.MarshalJSON(u.MetricsConsumerFilterByField, "", true)
	}

	if u.MetricsControlPlaneFilterByField != nil {
		return utils.MarshalJSON(u.MetricsControlPlaneFilterByField, "", true)
	}

	if u.MetricsControlPlaneGroupFilterByField != nil {
		return utils.MarshalJSON(u.MetricsControlPlaneGroupFilterByField, "", true)
	}

	if u.MetricsCountryCodeFilterByField != nil {
		return utils.MarshalJSON(u.MetricsCountryCodeFilterByField, "", true)
	}

	if u.MetricsDataPlaneNodeFilterByField != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeFilterByField, "", true)
	}

	if u.MetricsDataPlaneNodeVersionFilterByField != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeVersionFilterByField, "", true)
	}

	if u.MetricsGatewayServiceFilterByField != nil {
		return utils.MarshalJSON(u.MetricsGatewayServiceFilterByField, "", true)
	}

	if u.MetricsMcpErrorFilterByField != nil {
		return utils.MarshalJSON(u.MetricsMcpErrorFilterByField, "", true)
	}

	if u.MetricsMcpMethodFilterByField != nil {
		return utils.MarshalJSON(u.MetricsMcpMethodFilterByField, "", true)
	}

	if u.MetricsMcpSessionIDFilterByField != nil {
		return utils.MarshalJSON(u.MetricsMcpSessionIDFilterByField, "", true)
	}

	if u.MetricsMcpToolNameFilterByField != nil {
		return utils.MarshalJSON(u.MetricsMcpToolNameFilterByField, "", true)
	}

	if u.MetricsPortalFilterByField != nil {
		return utils.MarshalJSON(u.MetricsPortalFilterByField, "", true)
	}

	if u.MetricsRealmFilterByField != nil {
		return utils.MarshalJSON(u.MetricsRealmFilterByField, "", true)
	}

	if u.MetricsResponseSourceFilterByField != nil {
		return utils.MarshalJSON(u.MetricsResponseSourceFilterByField, "", true)
	}

	if u.MetricsRouteFilterByField != nil {
		return utils.MarshalJSON(u.MetricsRouteFilterByField, "", true)
	}

	if u.MetricsStatusCodeFilterByField != nil {
		return utils.MarshalJSON(u.MetricsStatusCodeFilterByField, "", true)
	}

	if u.MetricsStatusCodeGroupedFilterByField != nil {
		return utils.MarshalJSON(u.MetricsStatusCodeGroupedFilterByField, "", true)
	}

	if u.MetricsUpstreamStatusCodeFilterByField != nil {
		return utils.MarshalJSON(u.MetricsUpstreamStatusCodeFilterByField, "", true)
	}

	if u.MetricsUpstreamStatusCodeGroupedFilterByField != nil {
		return utils.MarshalJSON(u.MetricsUpstreamStatusCodeGroupedFilterByField, "", true)
	}

	return nil, errors.New("could not marshal union type AgenticFilters: all fields are null")
}
