// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// AIGatewayAuthStrategyOpenIDConnect - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
//
// Configuration for an auth strategy.
type AIGatewayAuthStrategyOpenIDConnect struct {
	// The display name for this auth strategy instance.
	DisplayName string `json:"display_name"`
	// **Pre-release Feature**
	// This feature is currently in beta and is subject to change.
	//
	// A user-defined unique identifier for this auth strategy instance, used as a stable human-readable reference. This value is immutable after creation.
	Name string `json:"name"`
	// Public labels store information about an entity that can be used for filtering a list of objects.
	//
	// Public labels are intended to store **PUBLIC** metadata.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels,omitempty"`
	// Stores information about what manages this entity, such as the tool or system responsible for its lifecycle (for example, `terraform`).
	//
	// Keys must be 1–63 characters long and start with an alphanumeric character.
	//
	ManagedBy map[string]string `json:"managed_by,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"openid-connect" json:"type"`
	// Configuration for the OpenID Connect auth strategy.
	// For advanced use cases, additional config properties can be sent in the request body.
	// See: https://developer.konghq.com/plugins/openid-connect/reference/ for the list of properties
	//
	Config any `json:"config,omitempty"`
}

func (a AIGatewayAuthStrategyOpenIDConnect) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayAuthStrategyOpenIDConnect) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetManagedBy() map[string]string {
	if a == nil {
		return nil
	}
	return a.ManagedBy
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetType() string {
	return "openid-connect"
}

func (a *AIGatewayAuthStrategyOpenIDConnect) GetConfig() any {
	if a == nil {
		return nil
	}
	return a.Config
}
