// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type AIGatewayTargetAnthropicConfigType string

const (
	AIGatewayTargetAnthropicConfigTypeAnthropic AIGatewayTargetAnthropicConfigType = "anthropic"
)

func (e AIGatewayTargetAnthropicConfigType) ToPointer() *AIGatewayTargetAnthropicConfigType {
	return &e
}
func (e *AIGatewayTargetAnthropicConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "anthropic":
		*e = AIGatewayTargetAnthropicConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AIGatewayTargetAnthropicConfigType: %v", v)
	}
}

// AIGatewayTargetAnthropicConfig - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
//
// Anthropic-specific configuration for a model.
type AIGatewayTargetAnthropicConfig struct {
	// The number of dimensions for embedding outputs.
	EmbeddingsDimensions *int64 `default:"null" json:"embeddings_dimensions"`
	// The maximum number of tokens to generate in the response.
	MaxTokens *int64 `default:"null" json:"max_tokens"`
	// Cost per input token for billing and cost tracking.
	InputCost *float64 `default:"null" json:"input_cost"`
	// Cost per output token for billing and cost tracking.
	OutputCost *float64 `default:"null" json:"output_cost"`
	// Controls randomness in the model output. Higher values produce more varied responses.
	Temperature *float64 `default:"null" json:"temperature"`
	// Limits the number of highest-probability tokens considered during generation.
	TopK *int64 `default:"null" json:"top_k"`
	// Nucleus sampling probability mass. Tokens with cumulative probability up to top_p are considered.
	TopP *float64 `default:"null" json:"top_p"`
	// The upstream URL for the model endpoint.
	UpstreamURL *string                            `default:"null" json:"upstream_url"`
	Type        AIGatewayTargetAnthropicConfigType `json:"type"`
	// The Anthropic API version to use.
	Version *string `default:"2023-06-01" json:"version"`
}

func (a AIGatewayTargetAnthropicConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayTargetAnthropicConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayTargetAnthropicConfig) GetEmbeddingsDimensions() *int64 {
	if a == nil {
		return nil
	}
	return a.EmbeddingsDimensions
}

func (a *AIGatewayTargetAnthropicConfig) GetMaxTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxTokens
}

func (a *AIGatewayTargetAnthropicConfig) GetInputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.InputCost
}

func (a *AIGatewayTargetAnthropicConfig) GetOutputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.OutputCost
}

func (a *AIGatewayTargetAnthropicConfig) GetTemperature() *float64 {
	if a == nil {
		return nil
	}
	return a.Temperature
}

func (a *AIGatewayTargetAnthropicConfig) GetTopK() *int64 {
	if a == nil {
		return nil
	}
	return a.TopK
}

func (a *AIGatewayTargetAnthropicConfig) GetTopP() *float64 {
	if a == nil {
		return nil
	}
	return a.TopP
}

func (a *AIGatewayTargetAnthropicConfig) GetUpstreamURL() *string {
	if a == nil {
		return nil
	}
	return a.UpstreamURL
}

func (a *AIGatewayTargetAnthropicConfig) GetType() AIGatewayTargetAnthropicConfigType {
	if a == nil {
		return AIGatewayTargetAnthropicConfigType("")
	}
	return a.Type
}

func (a *AIGatewayTargetAnthropicConfig) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
