// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type AIGatewayTargetCerebrasConfigType string

const (
	AIGatewayTargetCerebrasConfigTypeCerebras AIGatewayTargetCerebrasConfigType = "cerebras"
)

func (e AIGatewayTargetCerebrasConfigType) ToPointer() *AIGatewayTargetCerebrasConfigType {
	return &e
}
func (e *AIGatewayTargetCerebrasConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cerebras":
		*e = AIGatewayTargetCerebrasConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AIGatewayTargetCerebrasConfigType: %v", v)
	}
}

// AIGatewayTargetCerebrasConfig - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
//
// Cerebras-specific configuration for a model.
type AIGatewayTargetCerebrasConfig struct {
	// The number of dimensions for embedding outputs.
	EmbeddingsDimensions *int64 `default:"null" json:"embeddings_dimensions"`
	// The maximum number of tokens to generate in the response.
	MaxTokens *int64 `default:"null" json:"max_tokens"`
	// Cost per input token for billing and cost tracking.
	InputCost *float64 `default:"null" json:"input_cost"`
	// Cost per output token for billing and cost tracking.
	OutputCost *float64 `default:"null" json:"output_cost"`
	// Controls randomness in the model output. Higher values produce more varied responses.
	Temperature *float64 `default:"null" json:"temperature"`
	// Limits the number of highest-probability tokens considered during generation.
	TopK *int64 `default:"null" json:"top_k"`
	// Nucleus sampling probability mass. Tokens with cumulative probability up to top_p are considered.
	TopP *float64 `default:"null" json:"top_p"`
	// The upstream URL for the model endpoint.
	UpstreamURL *string                           `default:"null" json:"upstream_url"`
	Type        AIGatewayTargetCerebrasConfigType `json:"type"`
}

func (a AIGatewayTargetCerebrasConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayTargetCerebrasConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayTargetCerebrasConfig) GetEmbeddingsDimensions() *int64 {
	if a == nil {
		return nil
	}
	return a.EmbeddingsDimensions
}

func (a *AIGatewayTargetCerebrasConfig) GetMaxTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxTokens
}

func (a *AIGatewayTargetCerebrasConfig) GetInputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.InputCost
}

func (a *AIGatewayTargetCerebrasConfig) GetOutputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.OutputCost
}

func (a *AIGatewayTargetCerebrasConfig) GetTemperature() *float64 {
	if a == nil {
		return nil
	}
	return a.Temperature
}

func (a *AIGatewayTargetCerebrasConfig) GetTopK() *int64 {
	if a == nil {
		return nil
	}
	return a.TopK
}

func (a *AIGatewayTargetCerebrasConfig) GetTopP() *float64 {
	if a == nil {
		return nil
	}
	return a.TopP
}

func (a *AIGatewayTargetCerebrasConfig) GetUpstreamURL() *string {
	if a == nil {
		return nil
	}
	return a.UpstreamURL
}

func (a *AIGatewayTargetCerebrasConfig) GetType() AIGatewayTargetCerebrasConfigType {
	if a == nil {
		return AIGatewayTargetCerebrasConfigType("")
	}
	return a.Type
}
