// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type AnyChartTileDefinitionType string

const (
	AnyChartTileDefinitionTypeChartVisualization AnyChartTileDefinitionType = "ChartVisualization"
	AnyChartTileDefinitionTypeTableVisualization AnyChartTileDefinitionType = "TableVisualization"
)

// AnyChartTileDefinition - The tile's definition, which consists of a query to fetch data and a visualization to render the data.
// Charts and tables expect certain query types to render properly. The documentation for the individual visualization types has more information.
type AnyChartTileDefinition struct {
	ChartVisualization *ChartVisualization `queryParam:"inline" union:"member"`
	TableVisualization *TableVisualization `queryParam:"inline" union:"member"`

	Type AnyChartTileDefinitionType
}

func CreateAnyChartTileDefinitionChartVisualization(chartVisualization ChartVisualization) AnyChartTileDefinition {
	typ := AnyChartTileDefinitionTypeChartVisualization

	return AnyChartTileDefinition{
		ChartVisualization: &chartVisualization,
		Type:               typ,
	}
}

func CreateAnyChartTileDefinitionTableVisualization(tableVisualization TableVisualization) AnyChartTileDefinition {
	typ := AnyChartTileDefinitionTypeTableVisualization

	return AnyChartTileDefinition{
		TableVisualization: &tableVisualization,
		Type:               typ,
	}
}

func (u *AnyChartTileDefinition) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var chartVisualization ChartVisualization = ChartVisualization{}
	if err := utils.UnmarshalJSON(data, &chartVisualization, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyChartTileDefinitionTypeChartVisualization,
			Value: &chartVisualization,
		})
	}

	var tableVisualization TableVisualization = TableVisualization{}
	if err := utils.UnmarshalJSON(data, &tableVisualization, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AnyChartTileDefinitionTypeTableVisualization,
			Value: &tableVisualization,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyChartTileDefinition", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyChartTileDefinition", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AnyChartTileDefinitionType)
	switch best.Type {
	case AnyChartTileDefinitionTypeChartVisualization:
		u.ChartVisualization = best.Value.(*ChartVisualization)
		return nil
	case AnyChartTileDefinitionTypeTableVisualization:
		u.TableVisualization = best.Value.(*TableVisualization)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AnyChartTileDefinition", string(data))
}

func (u AnyChartTileDefinition) MarshalJSON() ([]byte, error) {
	if u.ChartVisualization != nil {
		return utils.MarshalJSON(u.ChartVisualization, "", true)
	}

	if u.TableVisualization != nil {
		return utils.MarshalJSON(u.TableVisualization, "", true)
	}

	return nil, errors.New("could not marshal union type AnyChartTileDefinition: all fields are null")
}
