// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// APIImplementationControlPlaneInput - A Control plane that implements an API
type APIImplementationControlPlaneInput struct {
	ControlPlaneID string `json:"control_plane_id"`
}

func (o *APIImplementationControlPlaneInput) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}
