// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type APISpecProviderPayloadProviderType string

const (
	APISpecProviderPayloadProviderTypeURLProvider                      APISpecProviderPayloadProviderType = "UrlProvider"
	APISpecProviderPayloadProviderTypeIntegrationProvider              APISpecProviderPayloadProviderType = "IntegrationProvider"
	APISpecProviderPayloadProviderTypeResourceBoundIntegrationProvider APISpecProviderPayloadProviderType = "ResourceBoundIntegrationProvider"
)

type APISpecProviderPayloadProvider struct {
	URLProvider                      *URLProvider                      `queryParam:"inline" union:"member"`
	IntegrationProvider              *IntegrationProvider              `queryParam:"inline" union:"member"`
	ResourceBoundIntegrationProvider *ResourceBoundIntegrationProvider `queryParam:"inline" union:"member"`

	Type APISpecProviderPayloadProviderType
}

func CreateAPISpecProviderPayloadProviderURLProvider(urlProvider URLProvider) APISpecProviderPayloadProvider {
	typ := APISpecProviderPayloadProviderTypeURLProvider

	return APISpecProviderPayloadProvider{
		URLProvider: &urlProvider,
		Type:        typ,
	}
}

func CreateAPISpecProviderPayloadProviderIntegrationProvider(integrationProvider IntegrationProvider) APISpecProviderPayloadProvider {
	typ := APISpecProviderPayloadProviderTypeIntegrationProvider

	return APISpecProviderPayloadProvider{
		IntegrationProvider: &integrationProvider,
		Type:                typ,
	}
}

func CreateAPISpecProviderPayloadProviderResourceBoundIntegrationProvider(resourceBoundIntegrationProvider ResourceBoundIntegrationProvider) APISpecProviderPayloadProvider {
	typ := APISpecProviderPayloadProviderTypeResourceBoundIntegrationProvider

	return APISpecProviderPayloadProvider{
		ResourceBoundIntegrationProvider: &resourceBoundIntegrationProvider,
		Type:                             typ,
	}
}

func (u *APISpecProviderPayloadProvider) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var urlProvider URLProvider = URLProvider{}
	if err := utils.UnmarshalJSON(data, &urlProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APISpecProviderPayloadProviderTypeURLProvider,
			Value: &urlProvider,
		})
	}

	var integrationProvider IntegrationProvider = IntegrationProvider{}
	if err := utils.UnmarshalJSON(data, &integrationProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APISpecProviderPayloadProviderTypeIntegrationProvider,
			Value: &integrationProvider,
		})
	}

	var resourceBoundIntegrationProvider ResourceBoundIntegrationProvider = ResourceBoundIntegrationProvider{}
	if err := utils.UnmarshalJSON(data, &resourceBoundIntegrationProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APISpecProviderPayloadProviderTypeResourceBoundIntegrationProvider,
			Value: &resourceBoundIntegrationProvider,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecProviderPayloadProvider", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecProviderPayloadProvider", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(APISpecProviderPayloadProviderType)
	switch best.Type {
	case APISpecProviderPayloadProviderTypeURLProvider:
		u.URLProvider = best.Value.(*URLProvider)
		return nil
	case APISpecProviderPayloadProviderTypeIntegrationProvider:
		u.IntegrationProvider = best.Value.(*IntegrationProvider)
		return nil
	case APISpecProviderPayloadProviderTypeResourceBoundIntegrationProvider:
		u.ResourceBoundIntegrationProvider = best.Value.(*ResourceBoundIntegrationProvider)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecProviderPayloadProvider", string(data))
}

func (u APISpecProviderPayloadProvider) MarshalJSON() ([]byte, error) {
	if u.URLProvider != nil {
		return utils.MarshalJSON(u.URLProvider, "", true)
	}

	if u.IntegrationProvider != nil {
		return utils.MarshalJSON(u.IntegrationProvider, "", true)
	}

	if u.ResourceBoundIntegrationProvider != nil {
		return utils.MarshalJSON(u.ResourceBoundIntegrationProvider, "", true)
	}

	return nil, errors.New("could not marshal union type APISpecProviderPayloadProvider: all fields are null")
}

// ProviderPayload - Represent spec provider information used for fetching the API spec. For raw, provide the raw content in the `content` property instead of using this provider.
type ProviderPayload struct {
	Provider APISpecProviderPayloadProvider `json:"provider"`
}

func (p ProviderPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProviderPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProviderPayload) GetProvider() APISpecProviderPayloadProvider {
	if p == nil {
		return APISpecProviderPayloadProvider{}
	}
	return p.Provider
}

// ContentPayload - The raw content of API specification, in json or yaml format (OpenAPI or AsyncAPI).
type ContentPayload struct {
	Content string `json:"content"`
}

func (c ContentPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentPayload) GetContent() string {
	if c == nil {
		return ""
	}
	return c.Content
}

type APISpecPayloadType string

const (
	APISpecPayloadTypeContentPayload  APISpecPayloadType = "ContentPayload"
	APISpecPayloadTypeProviderPayload APISpecPayloadType = "ProviderPayload"
)

type APISpecPayload struct {
	ContentPayload  *ContentPayload  `queryParam:"inline" union:"member"`
	ProviderPayload *ProviderPayload `queryParam:"inline" union:"member"`

	Type APISpecPayloadType
}

func CreateAPISpecPayloadContentPayload(contentPayload ContentPayload) APISpecPayload {
	typ := APISpecPayloadTypeContentPayload

	return APISpecPayload{
		ContentPayload: &contentPayload,
		Type:           typ,
	}
}

func CreateAPISpecPayloadProviderPayload(providerPayload ProviderPayload) APISpecPayload {
	typ := APISpecPayloadTypeProviderPayload

	return APISpecPayload{
		ProviderPayload: &providerPayload,
		Type:            typ,
	}
}

func (u *APISpecPayload) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var contentPayload ContentPayload = ContentPayload{}
	if err := utils.UnmarshalJSON(data, &contentPayload, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APISpecPayloadTypeContentPayload,
			Value: &contentPayload,
		})
	}

	var providerPayload ProviderPayload = ProviderPayload{}
	if err := utils.UnmarshalJSON(data, &providerPayload, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APISpecPayloadTypeProviderPayload,
			Value: &providerPayload,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecPayload", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecPayload", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(APISpecPayloadType)
	switch best.Type {
	case APISpecPayloadTypeContentPayload:
		u.ContentPayload = best.Value.(*ContentPayload)
		return nil
	case APISpecPayloadTypeProviderPayload:
		u.ProviderPayload = best.Value.(*ProviderPayload)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for APISpecPayload", string(data))
}

func (u APISpecPayload) MarshalJSON() ([]byte, error) {
	if u.ContentPayload != nil {
		return utils.MarshalJSON(u.ContentPayload, "", true)
	}

	if u.ProviderPayload != nil {
		return utils.MarshalJSON(u.ProviderPayload, "", true)
	}

	return nil, errors.New("could not marshal union type APISpecPayload: all fields are null")
}
