// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type APIVersion struct {
	// The version of the api.
	Version *string `json:"version,omitempty"`
	// The raw content of your API spec, in json or yaml format (OpenAPI or AsyncAPI).
	//
	SpecContent *string `json:"spec_content,omitempty"`
}

func (o *APIVersion) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *APIVersion) GetSpecContent() *string {
	if o == nil {
		return nil
	}
	return o.SpecContent
}
