// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
	"time"
)

// APIVersionResponseAPISpecType - The type of specification being stored. This allows us to render the specification correctly.
type APIVersionResponseAPISpecType string

const (
	APIVersionResponseAPISpecTypeOas2     APIVersionResponseAPISpecType = "oas2"
	APIVersionResponseAPISpecTypeOas3     APIVersionResponseAPISpecType = "oas3"
	APIVersionResponseAPISpecTypeAsyncapi APIVersionResponseAPISpecType = "asyncapi"
)

func (e APIVersionResponseAPISpecType) ToPointer() *APIVersionResponseAPISpecType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *APIVersionResponseAPISpecType) IsExact() bool {
	if e != nil {
		switch *e {
		case "oas2", "oas3", "asyncapi":
			return true
		}
	}
	return false
}

type APIVersionResponseValidationMessages struct {
	Message string `json:"message"`
}

func (a *APIVersionResponseValidationMessages) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

type APIVersionResponseAPISpecProviderType string

const (
	APIVersionResponseAPISpecProviderTypeRawProvider                      APIVersionResponseAPISpecProviderType = "RawProvider"
	APIVersionResponseAPISpecProviderTypeURLProvider                      APIVersionResponseAPISpecProviderType = "UrlProvider"
	APIVersionResponseAPISpecProviderTypeIntegrationProvider              APIVersionResponseAPISpecProviderType = "IntegrationProvider"
	APIVersionResponseAPISpecProviderTypeResourceBoundIntegrationProvider APIVersionResponseAPISpecProviderType = "ResourceBoundIntegrationProvider"
)

// APIVersionResponseAPISpecProvider - The provider used to supply the spec content. In write requests, provide
// this instead of or alongside content. If omitted on writes, the server
// infers type raw from spec.content.
type APIVersionResponseAPISpecProvider struct {
	RawProvider                      *RawProvider                      `queryParam:"inline" union:"member"`
	URLProvider                      *URLProvider                      `queryParam:"inline" union:"member"`
	IntegrationProvider              *IntegrationProvider              `queryParam:"inline" union:"member"`
	ResourceBoundIntegrationProvider *ResourceBoundIntegrationProvider `queryParam:"inline" union:"member"`

	Type APIVersionResponseAPISpecProviderType
}

func CreateAPIVersionResponseAPISpecProviderRawProvider(rawProvider RawProvider) APIVersionResponseAPISpecProvider {
	typ := APIVersionResponseAPISpecProviderTypeRawProvider

	return APIVersionResponseAPISpecProvider{
		RawProvider: &rawProvider,
		Type:        typ,
	}
}

func CreateAPIVersionResponseAPISpecProviderURLProvider(urlProvider URLProvider) APIVersionResponseAPISpecProvider {
	typ := APIVersionResponseAPISpecProviderTypeURLProvider

	return APIVersionResponseAPISpecProvider{
		URLProvider: &urlProvider,
		Type:        typ,
	}
}

func CreateAPIVersionResponseAPISpecProviderIntegrationProvider(integrationProvider IntegrationProvider) APIVersionResponseAPISpecProvider {
	typ := APIVersionResponseAPISpecProviderTypeIntegrationProvider

	return APIVersionResponseAPISpecProvider{
		IntegrationProvider: &integrationProvider,
		Type:                typ,
	}
}

func CreateAPIVersionResponseAPISpecProviderResourceBoundIntegrationProvider(resourceBoundIntegrationProvider ResourceBoundIntegrationProvider) APIVersionResponseAPISpecProvider {
	typ := APIVersionResponseAPISpecProviderTypeResourceBoundIntegrationProvider

	return APIVersionResponseAPISpecProvider{
		ResourceBoundIntegrationProvider: &resourceBoundIntegrationProvider,
		Type:                             typ,
	}
}

func (u *APIVersionResponseAPISpecProvider) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var rawProvider RawProvider = RawProvider{}
	if err := utils.UnmarshalJSON(data, &rawProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APIVersionResponseAPISpecProviderTypeRawProvider,
			Value: &rawProvider,
		})
	}

	var urlProvider URLProvider = URLProvider{}
	if err := utils.UnmarshalJSON(data, &urlProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APIVersionResponseAPISpecProviderTypeURLProvider,
			Value: &urlProvider,
		})
	}

	var integrationProvider IntegrationProvider = IntegrationProvider{}
	if err := utils.UnmarshalJSON(data, &integrationProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APIVersionResponseAPISpecProviderTypeIntegrationProvider,
			Value: &integrationProvider,
		})
	}

	var resourceBoundIntegrationProvider ResourceBoundIntegrationProvider = ResourceBoundIntegrationProvider{}
	if err := utils.UnmarshalJSON(data, &resourceBoundIntegrationProvider, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  APIVersionResponseAPISpecProviderTypeResourceBoundIntegrationProvider,
			Value: &resourceBoundIntegrationProvider,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APIVersionResponseAPISpecProvider", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for APIVersionResponseAPISpecProvider", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(APIVersionResponseAPISpecProviderType)
	switch best.Type {
	case APIVersionResponseAPISpecProviderTypeRawProvider:
		u.RawProvider = best.Value.(*RawProvider)
		return nil
	case APIVersionResponseAPISpecProviderTypeURLProvider:
		u.URLProvider = best.Value.(*URLProvider)
		return nil
	case APIVersionResponseAPISpecProviderTypeIntegrationProvider:
		u.IntegrationProvider = best.Value.(*IntegrationProvider)
		return nil
	case APIVersionResponseAPISpecProviderTypeResourceBoundIntegrationProvider:
		u.ResourceBoundIntegrationProvider = best.Value.(*ResourceBoundIntegrationProvider)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for APIVersionResponseAPISpecProvider", string(data))
}

func (u APIVersionResponseAPISpecProvider) MarshalJSON() ([]byte, error) {
	if u.RawProvider != nil {
		return utils.MarshalJSON(u.RawProvider, "", true)
	}

	if u.URLProvider != nil {
		return utils.MarshalJSON(u.URLProvider, "", true)
	}

	if u.IntegrationProvider != nil {
		return utils.MarshalJSON(u.IntegrationProvider, "", true)
	}

	if u.ResourceBoundIntegrationProvider != nil {
		return utils.MarshalJSON(u.ResourceBoundIntegrationProvider, "", true)
	}

	return nil, errors.New("could not marshal union type APIVersionResponseAPISpecProvider: all fields are null")
}

type APIVersionResponseSpec struct {
	// The raw content of your API spec, in json or yaml format (OpenAPI or AsyncAPI).
	//
	Content *string `default:"null" json:"content"`
	// The type of specification being stored. This allows us to render the specification correctly.
	//
	Type *APIVersionResponseAPISpecType `json:"type,omitempty"`
	// The errors that occurred while parsing the API version spec.
	ValidationMessages []APIVersionResponseValidationMessages `json:"validation_messages,omitempty"`
	// The provider used to supply the spec content. In write requests, provide
	// this instead of or alongside content. If omitted on writes, the server
	// infers type raw from spec.content.
	//
	Provider *APIVersionResponseAPISpecProvider `json:"provider,omitempty"`
}

func (a APIVersionResponseSpec) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIVersionResponseSpec) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIVersionResponseSpec) GetContent() *string {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *APIVersionResponseSpec) GetType() *APIVersionResponseAPISpecType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *APIVersionResponseSpec) GetValidationMessages() []APIVersionResponseValidationMessages {
	if a == nil {
		return nil
	}
	return a.ValidationMessages
}

func (a *APIVersionResponseSpec) GetProvider() *APIVersionResponseAPISpecProvider {
	if a == nil {
		return nil
	}
	return a.Provider
}

// APIVersionResponse - API version (OpenAPI or AsyncAPI)
type APIVersionResponse struct {
	// The API version identifier.
	ID string `json:"id"`
	// The version of the api.
	Version string                  `json:"version"`
	Spec    *APIVersionResponseSpec `json:"spec"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (a APIVersionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIVersionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIVersionResponse) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *APIVersionResponse) GetVersion() string {
	if a == nil {
		return ""
	}
	return a.Version
}

func (a *APIVersionResponse) GetSpec() *APIVersionResponseSpec {
	if a == nil {
		return nil
	}
	return a.Spec
}

func (a *APIVersionResponse) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *APIVersionResponse) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}
