// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// BackendClusterAuthenticationSaslAwsIamDefaultProviderChain - Configures whether to authenticate using credentials obtained from the AWS default credentials provider chain
//
// **Requires a minimum runtime version of `1.3`**.
type BackendClusterAuthenticationSaslAwsIamDefaultProviderChain struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"default_provider_chain" json:"type"`
}

func (b BackendClusterAuthenticationSaslAwsIamDefaultProviderChain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackendClusterAuthenticationSaslAwsIamDefaultProviderChain) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BackendClusterAuthenticationSaslAwsIamDefaultProviderChain) GetType() string {
	return "default_provider_chain"
}
