// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// BackendClusterAuthenticationSaslPlainSensitiveDataAware - SASL/PLAIN authentication scheme for the backend cluster without requiring sensitive password data.
type BackendClusterAuthenticationSaslPlainSensitiveDataAware struct {
	type_ string `const:"sasl_plain" json:"type"`
	// A literal value or a reference to an existing secret as a template string expression.
	// The value is stored and returned by the API as-is, not treated as sensitive information.
	//
	Username string `json:"username"`
	// A sensitive value containing the secret or a reference to a secret as a template string expression.
	// If the value is provided as plain text, it is encrypted at rest and omitted from API responses.
	// If provided as an expression, the expression itself is stored and returned by the API.
	//
	Password *string `json:"password,omitempty"`
}

func (b BackendClusterAuthenticationSaslPlainSensitiveDataAware) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackendClusterAuthenticationSaslPlainSensitiveDataAware) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BackendClusterAuthenticationSaslPlainSensitiveDataAware) GetType() string {
	return "sasl_plain"
}

func (o *BackendClusterAuthenticationSaslPlainSensitiveDataAware) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *BackendClusterAuthenticationSaslPlainSensitiveDataAware) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}
