// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// CertificateMetadata - Metadata extracted from a certificate.
type CertificateMetadata struct {
	// The issuer of the certificate.
	Issuer *string `default:"null" json:"issuer"`
	// The subject of the certificate.
	Subject *string `default:"null" json:"subject"`
	// The key usages of the certificate.
	KeyUsages []string `json:"key_usages"`
	// The expiry date of the certificate as a unix timestamp.
	Expiry *int64 `default:"null" json:"expiry"`
	// The Subject Alternative Names (SAN) of the certificate.
	SanNames []string `json:"san_names"`
	// The DNS names in the certificate SAN.
	DNSNames []string `json:"dns_names"`
	// The email addresses in the certificate SAN.
	EmailAddresses []string `json:"email_addresses"`
	// The IP addresses in the certificate SAN.
	IPAddresses []string `json:"ip_addresses"`
	// The URIs in the certificate SAN.
	Uris []string `json:"uris"`
	// The SHA-256 fingerprint of the certificate.
	Sha256Fingerprint *string `default:"null" json:"sha256_fingerprint"`
}

func (c CertificateMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CertificateMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CertificateMetadata) GetIssuer() *string {
	if o == nil {
		return nil
	}
	return o.Issuer
}

func (o *CertificateMetadata) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *CertificateMetadata) GetKeyUsages() []string {
	if o == nil {
		return nil
	}
	return o.KeyUsages
}

func (o *CertificateMetadata) GetExpiry() *int64 {
	if o == nil {
		return nil
	}
	return o.Expiry
}

func (o *CertificateMetadata) GetSanNames() []string {
	if o == nil {
		return nil
	}
	return o.SanNames
}

func (o *CertificateMetadata) GetDNSNames() []string {
	if o == nil {
		return nil
	}
	return o.DNSNames
}

func (o *CertificateMetadata) GetEmailAddresses() []string {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *CertificateMetadata) GetIPAddresses() []string {
	if o == nil {
		return nil
	}
	return o.IPAddresses
}

func (o *CertificateMetadata) GetUris() []string {
	if o == nil {
		return nil
	}
	return o.Uris
}

func (o *CertificateMetadata) GetSha256Fingerprint() *string {
	if o == nil {
		return nil
	}
	return o.Sha256Fingerprint
}
