// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// ControlPlaneReference - A control plane that implements an API
type ControlPlaneReference struct {
	// The environment this implementation is scoped to, by name. On write, selects the
	// target environment: required when the API is configured across multiple
	// environments, and optional otherwise (accepted only if it matches the API's sole
	// environment). On read, the resolved environment name. Present only for APIs
	// configured across multiple environments.
	//
	Environment *string `default:"null" json:"environment"`
	// A Control plane that implements an API
	ControlPlane *APIImplementationControlPlaneInput `json:"control_plane,omitempty"`
}

func (c ControlPlaneReference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ControlPlaneReference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ControlPlaneReference) GetEnvironment() *string {
	if c == nil {
		return nil
	}
	return c.Environment
}

func (c *ControlPlaneReference) GetControlPlane() *APIImplementationControlPlaneInput {
	if c == nil {
		return nil
	}
	return c.ControlPlane
}
