// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// CreateScope - Scope to be created
type CreateScope struct {
	// The name of the scope
	Name string `json:"name"`
	// Description of the scope
	Description *string `json:"description,omitempty"`
	// Specifies whether the scope is included by default in access tokens without being explicitly requested by the client. If the scope is not allowed by the client, it will not be included in the access token.
	Default *bool `default:"false" json:"default"`
	// Specifies whether to include the scope in the metadata document
	IncludeInMetadata *bool `default:"false" json:"include_in_metadata"`
	// Specifies whether the scope is enabled
	Enabled *bool `default:"true" json:"enabled"`
}

func (c CreateScope) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateScope) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateScope) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateScope) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateScope) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *CreateScope) GetIncludeInMetadata() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeInMetadata
}

func (o *CreateScope) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}
