// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DashboardUpdateRequest struct {
	// The dashboard name, which is displayed at the top of the dashboard and in lists.
	// It does not need to be unique.
	//
	Name string `json:"name"`
	// A JSON object describing a dashboard.
	//
	// A dashboard is an array of tiles.  All tiles are of type 'chart', which query data and render a chart displaying that data.
	//
	// Dashboards have 6 columns and as many rows as necessary to display their tiles.
	//
	Definition Dashboard `json:"definition"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
}

func (o *DashboardUpdateRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DashboardUpdateRequest) GetDefinition() Dashboard {
	if o == nil {
		return Dashboard{}
	}
	return o.Definition
}

func (o *DashboardUpdateRequest) GetLabels() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Labels
}
