// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Dashboard - A JSON object describing a dashboard.
//
// A dashboard is an array of tiles.  All tiles are of type 'chart', which query data and render a chart displaying that data.
//
// Dashboards have 6 columns and as many rows as necessary to display their tiles.
type Dashboard struct {
	// The array of tiles.  We currently support up to 102 tiles, which is 17 rows of 6x1 tiles.
	Tiles []Tile `json:"tiles"`
	// An optional array of filters that are applied globally to all relevant tiles in the dashboard.
	PresetFilters [][]AdvancedFilters `json:"preset_filters,omitempty"`
}

func (o *Dashboard) GetTiles() []Tile {
	if o == nil {
		return []Tile{}
	}
	return o.Tiles
}

func (o *Dashboard) GetPresetFilters() [][]AdvancedFilters {
	if o == nil {
		return nil
	}
	return o.PresetFilters
}
