// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type EncryptionKeyStaticReferenceType string

const (
	EncryptionKeyStaticReferenceTypeReferenceByID   EncryptionKeyStaticReferenceType = "ReferenceByID"
	EncryptionKeyStaticReferenceTypeReferenceByName EncryptionKeyStaticReferenceType = "ReferenceByName"
)

// EncryptionKeyStaticReference - A static encryption key reference, either by ID or by value.
type EncryptionKeyStaticReference struct {
	ReferenceByID   *ReferenceByID   `queryParam:"inline"`
	ReferenceByName *ReferenceByName `queryParam:"inline"`

	Type EncryptionKeyStaticReferenceType
}

func CreateEncryptionKeyStaticReferenceReferenceByID(referenceByID ReferenceByID) EncryptionKeyStaticReference {
	typ := EncryptionKeyStaticReferenceTypeReferenceByID

	return EncryptionKeyStaticReference{
		ReferenceByID: &referenceByID,
		Type:          typ,
	}
}

func CreateEncryptionKeyStaticReferenceReferenceByName(referenceByName ReferenceByName) EncryptionKeyStaticReference {
	typ := EncryptionKeyStaticReferenceTypeReferenceByName

	return EncryptionKeyStaticReference{
		ReferenceByName: &referenceByName,
		Type:            typ,
	}
}

func (u *EncryptionKeyStaticReference) UnmarshalJSON(data []byte) error {

	var referenceByID ReferenceByID = ReferenceByID{}
	if err := utils.UnmarshalJSON(data, &referenceByID, "", true, true); err == nil {
		u.ReferenceByID = &referenceByID
		u.Type = EncryptionKeyStaticReferenceTypeReferenceByID
		return nil
	}

	var referenceByName ReferenceByName = ReferenceByName{}
	if err := utils.UnmarshalJSON(data, &referenceByName, "", true, true); err == nil {
		u.ReferenceByName = &referenceByName
		u.Type = EncryptionKeyStaticReferenceTypeReferenceByName
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EncryptionKeyStaticReference", string(data))
}

func (u EncryptionKeyStaticReference) MarshalJSON() ([]byte, error) {
	if u.ReferenceByID != nil {
		return utils.MarshalJSON(u.ReferenceByID, "", true)
	}

	if u.ReferenceByName != nil {
		return utils.MarshalJSON(u.ReferenceByName, "", true)
	}

	return nil, errors.New("could not marshal union type EncryptionKeyStaticReference: all fields are null")
}
