// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// EncryptionKeyAWS - The AWS KMS key to use for encryption.
type EncryptionKeyAWS struct {
	type_ string `const:"aws" json:"type"`
	// The AWS KMS key ARN.
	Arn string `json:"arn"`
}

func (e EncryptionKeyAWS) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EncryptionKeyAWS) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EncryptionKeyAWS) GetType() string {
	return "aws"
}

func (o *EncryptionKeyAWS) GetArn() string {
	if o == nil {
		return ""
	}
	return o.Arn
}
