// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type EventGatewayListenerPolicyModifyType string

const (
	EventGatewayListenerPolicyModifyTypeTLSServer               EventGatewayListenerPolicyModifyType = "tls_server"
	EventGatewayListenerPolicyModifyTypeForwardToVirtualCluster EventGatewayListenerPolicyModifyType = "forward_to_virtual_cluster"
)

// EventGatewayListenerPolicyModify - The typed schema of the policy to modify it.
type EventGatewayListenerPolicyModify struct {
	EventGatewayTLSListenerPolicy *EventGatewayTLSListenerPolicy `queryParam:"inline"`
	ForwardToVirtualClusterPolicy *ForwardToVirtualClusterPolicy `queryParam:"inline"`

	Type EventGatewayListenerPolicyModifyType
}

func CreateEventGatewayListenerPolicyModifyTLSServer(tlsServer EventGatewayTLSListenerPolicy) EventGatewayListenerPolicyModify {
	typ := EventGatewayListenerPolicyModifyTypeTLSServer

	typStr := EventGatewayTLSListenerPolicyType(typ)
	tlsServer.Type = typStr

	return EventGatewayListenerPolicyModify{
		EventGatewayTLSListenerPolicy: &tlsServer,
		Type:                          typ,
	}
}

func CreateEventGatewayListenerPolicyModifyForwardToVirtualCluster(forwardToVirtualCluster ForwardToVirtualClusterPolicy) EventGatewayListenerPolicyModify {
	typ := EventGatewayListenerPolicyModifyTypeForwardToVirtualCluster

	typStr := ForwardToVirtualClusterPolicyType(typ)
	forwardToVirtualCluster.Type = typStr

	return EventGatewayListenerPolicyModify{
		ForwardToVirtualClusterPolicy: &forwardToVirtualCluster,
		Type:                          typ,
	}
}

func (u *EventGatewayListenerPolicyModify) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "tls_server":
		eventGatewayTLSListenerPolicy := new(EventGatewayTLSListenerPolicy)
		if err := utils.UnmarshalJSON(data, &eventGatewayTLSListenerPolicy, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == tls_server) type EventGatewayTLSListenerPolicy within EventGatewayListenerPolicyModify: %w", string(data), err)
		}

		u.EventGatewayTLSListenerPolicy = eventGatewayTLSListenerPolicy
		u.Type = EventGatewayListenerPolicyModifyTypeTLSServer
		return nil
	case "forward_to_virtual_cluster":
		forwardToVirtualClusterPolicy := new(ForwardToVirtualClusterPolicy)
		if err := utils.UnmarshalJSON(data, &forwardToVirtualClusterPolicy, "", true, false); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == forward_to_virtual_cluster) type ForwardToVirtualClusterPolicy within EventGatewayListenerPolicyModify: %w", string(data), err)
		}

		u.ForwardToVirtualClusterPolicy = forwardToVirtualClusterPolicy
		u.Type = EventGatewayListenerPolicyModifyTypeForwardToVirtualCluster
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EventGatewayListenerPolicyModify", string(data))
}

func (u EventGatewayListenerPolicyModify) MarshalJSON() ([]byte, error) {
	if u.EventGatewayTLSListenerPolicy != nil {
		return utils.MarshalJSON(u.EventGatewayTLSListenerPolicy, "", true)
	}

	if u.ForwardToVirtualClusterPolicy != nil {
		return utils.MarshalJSON(u.ForwardToVirtualClusterPolicy, "", true)
	}

	return nil, errors.New("could not marshal union type EventGatewayListenerPolicyModify: all fields are null")
}
