// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// EventGatewayKonnectVault - A konnect vault.
type EventGatewayKonnectVault struct {
	// The name of the vault.
	Name  string `json:"name"`
	type_ string `const:"konnect" json:"type"`
	// A human-readable description of the vault.
	Description *string `default:"null" json:"description"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
}

func (e EventGatewayKonnectVault) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGatewayKonnectVault) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EventGatewayKonnectVault) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EventGatewayKonnectVault) GetType() string {
	return "konnect"
}

func (o *EventGatewayKonnectVault) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *EventGatewayKonnectVault) GetLabels() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Labels
}
