// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// EventGatewayModifyHeadersPolicyConfig - The configuration of the modify headers policy.
type EventGatewayModifyHeadersPolicyConfig struct {
	// Actions are run in sequential order and act on individual headers.
	Actions []EventGatewayModifyHeaderAction `json:"actions"`
}

func (o *EventGatewayModifyHeadersPolicyConfig) GetActions() []EventGatewayModifyHeaderAction {
	if o == nil {
		return nil
	}
	return o.Actions
}

// EventGatewayModifyHeadersPolicy - A policy that modifies headers for requests.
type EventGatewayModifyHeadersPolicy struct {
	type_ string `const:"modify_headers" json:"type"`
	// A unique user-defined name of the policy.
	Name *string `default:"null" json:"name"`
	// A human-readable description of the policy.
	Description *string `json:"description,omitempty"`
	// Whether the policy is enabled.
	Enabled *bool `default:"true" json:"enabled"`
	// A string containing the boolean expression that determines whether the policy is applied.
	//
	// When the policy is applied as a child policy of schema_validation, the expression can also reference
	// `record.value` fields.
	//
	Condition *string `json:"condition,omitempty"`
	// The configuration of the modify headers policy.
	Config EventGatewayModifyHeadersPolicyConfig `json:"config"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
}

func (e EventGatewayModifyHeadersPolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGatewayModifyHeadersPolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EventGatewayModifyHeadersPolicy) GetType() string {
	return "modify_headers"
}

func (o *EventGatewayModifyHeadersPolicy) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *EventGatewayModifyHeadersPolicy) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *EventGatewayModifyHeadersPolicy) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *EventGatewayModifyHeadersPolicy) GetCondition() *string {
	if o == nil {
		return nil
	}
	return o.Condition
}

func (o *EventGatewayModifyHeadersPolicy) GetConfig() EventGatewayModifyHeadersPolicyConfig {
	if o == nil {
		return EventGatewayModifyHeadersPolicyConfig{}
	}
	return o.Config
}

func (o *EventGatewayModifyHeadersPolicy) GetLabels() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Labels
}
