// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
	"time"
)

// EventGatewayListenerPolicyConfig - The configuration of the policy.
type EventGatewayListenerPolicyConfig struct {
}

// EventGatewayListenerPolicy - A listener policy associated with an Event Gateway.
type EventGatewayListenerPolicy struct {
	// The type name of the policy.
	Type string `json:"type"`
	// A unique user-defined name of the policy.
	Name *string `default:"null" json:"name"`
	// A human-readable description of the policy.
	Description *string `json:"description,omitempty"`
	// Whether the policy is enabled.
	Enabled *bool `default:"true" json:"enabled"`
	// The configuration of the policy.
	Config EventGatewayListenerPolicyConfig `json:"config"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
	// The unique identifier of the policy.
	ID string `json:"id"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// The unique identifier of the parent policy, if any.
	ParentPolicyID *string `default:"null" json:"parent_policy_id"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (e EventGatewayListenerPolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGatewayListenerPolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EventGatewayListenerPolicy) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *EventGatewayListenerPolicy) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *EventGatewayListenerPolicy) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *EventGatewayListenerPolicy) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *EventGatewayListenerPolicy) GetConfig() EventGatewayListenerPolicyConfig {
	if o == nil {
		return EventGatewayListenerPolicyConfig{}
	}
	return o.Config
}

func (o *EventGatewayListenerPolicy) GetLabels() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *EventGatewayListenerPolicy) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *EventGatewayListenerPolicy) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *EventGatewayListenerPolicy) GetParentPolicyID() *string {
	if o == nil {
		return nil
	}
	return o.ParentPolicyID
}

func (o *EventGatewayListenerPolicy) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
