// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// EventGatewayParsedRecordDecryptionSelector - Selects fields of a parsed record for decryption.
type EventGatewayParsedRecordDecryptionSelector struct {
	// This expression should evaluate to an array of exact field paths,
	// equivalent to the `match` values in the array variant.
	//
	PathsExpression *string                                   `json:"paths_expression,omitempty"`
	Paths           []EventGatewayParsedRecordFieldPathsArray `json:"paths,omitempty"`
}

func (e EventGatewayParsedRecordDecryptionSelector) MarshalJSON() ([]byte, error) {
	jsonBytes, err := utils.MarshalJSON(e, "", false)
	if err != nil {
		return nil, err
	}
	out, err := utils.RunJQBytes(jsonBytes, "if (.paths_expression | type) == \"string\" then .paths = .paths_expression | del(.paths_expression) else . end")
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (e *EventGatewayParsedRecordDecryptionSelector) UnmarshalJSON(data []byte) error {
	if out, err := utils.RunJQBytes(data, "if (.paths | type) == \"string\" then .paths_expression = .paths | del(.paths) else . end"); err != nil {
		return err
	} else {
		data = out
	}
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EventGatewayParsedRecordDecryptionSelector) GetPathsExpression() *string {
	if e == nil {
		return nil
	}
	return e.PathsExpression
}

func (e *EventGatewayParsedRecordDecryptionSelector) GetPaths() []EventGatewayParsedRecordFieldPathsArray {
	if e == nil {
		return nil
	}
	return e.Paths
}
