// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// HeadersSelector - Configuration for routing requests to a specific model using a header.
type HeadersSelector struct {
	// Value indexed by property name that will cause this route to match if present in the request headers.
	//
	Headers map[string]any `json:"headers"`
}

func (h HeadersSelector) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HeadersSelector) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HeadersSelector) GetHeaders() map[string]any {
	if h == nil {
		return map[string]any{}
	}
	return h.Headers
}
