// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshOpenTelemetryBackendList - List
type MeshOpenTelemetryBackendList struct {
	Items []MeshOpenTelemetryBackendItem `json:"items,omitempty"`
	// The total number of entities
	Total *float64 `json:"total,omitempty"`
	// URL to the next page
	Next *string `json:"next,omitempty"`
}

func (m *MeshOpenTelemetryBackendList) GetItems() []MeshOpenTelemetryBackendItem {
	if m == nil {
		return nil
	}
	return m.Items
}

func (m *MeshOpenTelemetryBackendList) GetTotal() *float64 {
	if m == nil {
		return nil
	}
	return m.Total
}

func (m *MeshOpenTelemetryBackendList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
