// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsAPIProductFilterByField2Field - The field to filter.
type MetricsAPIProductFilterByField2Field string

const (
	MetricsAPIProductFilterByField2FieldAPIProduct MetricsAPIProductFilterByField2Field = "api_product"
)

func (e MetricsAPIProductFilterByField2Field) ToPointer() *MetricsAPIProductFilterByField2Field {
	return &e
}
func (e *MetricsAPIProductFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_product":
		*e = MetricsAPIProductFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsAPIProductFilterByField2Field: %v", v)
	}
}

type MetricsAPIProductFilterByFieldEmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsAPIProductFilterByField2Field `json:"field"`
}

func (m MetricsAPIProductFilterByFieldEmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsAPIProductFilterByFieldEmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsAPIProductFilterByFieldEmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if m == nil {
		return RequestsFilterTypeEmpty("")
	}
	return m.Operator
}

func (m *MetricsAPIProductFilterByFieldEmptyFilters) GetField() MetricsAPIProductFilterByField2Field {
	if m == nil {
		return MetricsAPIProductFilterByField2Field("")
	}
	return m.Field
}

// MetricsAPIProductFilterByFieldField - The field to filter.
type MetricsAPIProductFilterByFieldField string

const (
	MetricsAPIProductFilterByFieldFieldAPIProduct MetricsAPIProductFilterByFieldField = "api_product"
)

func (e MetricsAPIProductFilterByFieldField) ToPointer() *MetricsAPIProductFilterByFieldField {
	return &e
}
func (e *MetricsAPIProductFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_product":
		*e = MetricsAPIProductFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsAPIProductFilterByFieldField: %v", v)
	}
}

type MetricsAPIProductFilterByFieldMultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The IDs to include in the results.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsAPIProductFilterByFieldField `json:"field"`
}

func (m MetricsAPIProductFilterByFieldMultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsAPIProductFilterByFieldMultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsAPIProductFilterByFieldMultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MetricsAPIProductFilterByFieldMultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MetricsAPIProductFilterByFieldMultiselectFilters) GetField() MetricsAPIProductFilterByFieldField {
	if m == nil {
		return MetricsAPIProductFilterByFieldField("")
	}
	return m.Field
}

type MetricsAPIProductFilterByFieldType string

const (
	MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldMultiselectFilters MetricsAPIProductFilterByFieldType = "MetricsApiProductFilterByField_Multiselect filters"
	MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldEmptyFilters       MetricsAPIProductFilterByFieldType = "MetricsApiProductFilterByField_Empty filters"
)

type MetricsAPIProductFilterByField struct {
	MetricsAPIProductFilterByFieldMultiselectFilters *MetricsAPIProductFilterByFieldMultiselectFilters `queryParam:"inline" union:"member"`
	MetricsAPIProductFilterByFieldEmptyFilters       *MetricsAPIProductFilterByFieldEmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsAPIProductFilterByFieldType
}

func CreateMetricsAPIProductFilterByFieldMetricsAPIProductFilterByFieldMultiselectFilters(metricsAPIProductFilterByFieldMultiselectFilters MetricsAPIProductFilterByFieldMultiselectFilters) MetricsAPIProductFilterByField {
	typ := MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldMultiselectFilters

	return MetricsAPIProductFilterByField{
		MetricsAPIProductFilterByFieldMultiselectFilters: &metricsAPIProductFilterByFieldMultiselectFilters,
		Type: typ,
	}
}

func CreateMetricsAPIProductFilterByFieldMetricsAPIProductFilterByFieldEmptyFilters(metricsAPIProductFilterByFieldEmptyFilters MetricsAPIProductFilterByFieldEmptyFilters) MetricsAPIProductFilterByField {
	typ := MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldEmptyFilters

	return MetricsAPIProductFilterByField{
		MetricsAPIProductFilterByFieldEmptyFilters: &metricsAPIProductFilterByFieldEmptyFilters,
		Type: typ,
	}
}

func (u *MetricsAPIProductFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var metricsAPIProductFilterByFieldMultiselectFilters MetricsAPIProductFilterByFieldMultiselectFilters = MetricsAPIProductFilterByFieldMultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &metricsAPIProductFilterByFieldMultiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldMultiselectFilters,
			Value: &metricsAPIProductFilterByFieldMultiselectFilters,
		})
	}

	var metricsAPIProductFilterByFieldEmptyFilters MetricsAPIProductFilterByFieldEmptyFilters = MetricsAPIProductFilterByFieldEmptyFilters{}
	if err := utils.UnmarshalJSON(data, &metricsAPIProductFilterByFieldEmptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldEmptyFilters,
			Value: &metricsAPIProductFilterByFieldEmptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsAPIProductFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsAPIProductFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsAPIProductFilterByFieldType)
	switch best.Type {
	case MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldMultiselectFilters:
		u.MetricsAPIProductFilterByFieldMultiselectFilters = best.Value.(*MetricsAPIProductFilterByFieldMultiselectFilters)
		return nil
	case MetricsAPIProductFilterByFieldTypeMetricsAPIProductFilterByFieldEmptyFilters:
		u.MetricsAPIProductFilterByFieldEmptyFilters = best.Value.(*MetricsAPIProductFilterByFieldEmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsAPIProductFilterByField", string(data))
}

func (u MetricsAPIProductFilterByField) MarshalJSON() ([]byte, error) {
	if u.MetricsAPIProductFilterByFieldMultiselectFilters != nil {
		return utils.MarshalJSON(u.MetricsAPIProductFilterByFieldMultiselectFilters, "", true)
	}

	if u.MetricsAPIProductFilterByFieldEmptyFilters != nil {
		return utils.MarshalJSON(u.MetricsAPIProductFilterByFieldEmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsAPIProductFilterByField: all fields are null")
}
