// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsDataPlaneNodeFilterByField2Field - The field to filter.
type MetricsDataPlaneNodeFilterByField2Field string

const (
	MetricsDataPlaneNodeFilterByField2FieldDataPlaneNode MetricsDataPlaneNodeFilterByField2Field = "data_plane_node"
)

func (e MetricsDataPlaneNodeFilterByField2Field) ToPointer() *MetricsDataPlaneNodeFilterByField2Field {
	return &e
}
func (e *MetricsDataPlaneNodeFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "data_plane_node":
		*e = MetricsDataPlaneNodeFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsDataPlaneNodeFilterByField2Field: %v", v)
	}
}

type MetricsDataPlaneNodeFilterByFieldEmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsDataPlaneNodeFilterByField2Field `json:"field"`
}

func (m MetricsDataPlaneNodeFilterByFieldEmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsDataPlaneNodeFilterByFieldEmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsDataPlaneNodeFilterByFieldEmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if m == nil {
		return RequestsFilterTypeEmpty("")
	}
	return m.Operator
}

func (m *MetricsDataPlaneNodeFilterByFieldEmptyFilters) GetField() MetricsDataPlaneNodeFilterByField2Field {
	if m == nil {
		return MetricsDataPlaneNodeFilterByField2Field("")
	}
	return m.Field
}

// MetricsDataPlaneNodeFilterByFieldField - The field to filter.
type MetricsDataPlaneNodeFilterByFieldField string

const (
	MetricsDataPlaneNodeFilterByFieldFieldDataPlaneNode MetricsDataPlaneNodeFilterByFieldField = "data_plane_node"
)

func (e MetricsDataPlaneNodeFilterByFieldField) ToPointer() *MetricsDataPlaneNodeFilterByFieldField {
	return &e
}
func (e *MetricsDataPlaneNodeFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "data_plane_node":
		*e = MetricsDataPlaneNodeFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsDataPlaneNodeFilterByFieldField: %v", v)
	}
}

type MetricsDataPlaneNodeFilterByFieldMultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The IDs to include in the results. Because gateway IDs are only unique within a given control plane, the filter values must be of the form `control_plane_id:field_id` or `control_plane_group_id:field_id` for data plane nodes within a control plane group.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsDataPlaneNodeFilterByFieldField `json:"field"`
}

func (m MetricsDataPlaneNodeFilterByFieldMultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsDataPlaneNodeFilterByFieldMultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsDataPlaneNodeFilterByFieldMultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MetricsDataPlaneNodeFilterByFieldMultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MetricsDataPlaneNodeFilterByFieldMultiselectFilters) GetField() MetricsDataPlaneNodeFilterByFieldField {
	if m == nil {
		return MetricsDataPlaneNodeFilterByFieldField("")
	}
	return m.Field
}

type MetricsDataPlaneNodeFilterByFieldType string

const (
	MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldMultiselectFilters MetricsDataPlaneNodeFilterByFieldType = "MetricsDataPlaneNodeFilterByField_Multiselect filters"
	MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldEmptyFilters       MetricsDataPlaneNodeFilterByFieldType = "MetricsDataPlaneNodeFilterByField_Empty filters"
)

type MetricsDataPlaneNodeFilterByField struct {
	MetricsDataPlaneNodeFilterByFieldMultiselectFilters *MetricsDataPlaneNodeFilterByFieldMultiselectFilters `queryParam:"inline" union:"member"`
	MetricsDataPlaneNodeFilterByFieldEmptyFilters       *MetricsDataPlaneNodeFilterByFieldEmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsDataPlaneNodeFilterByFieldType
}

func CreateMetricsDataPlaneNodeFilterByFieldMetricsDataPlaneNodeFilterByFieldMultiselectFilters(metricsDataPlaneNodeFilterByFieldMultiselectFilters MetricsDataPlaneNodeFilterByFieldMultiselectFilters) MetricsDataPlaneNodeFilterByField {
	typ := MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldMultiselectFilters

	return MetricsDataPlaneNodeFilterByField{
		MetricsDataPlaneNodeFilterByFieldMultiselectFilters: &metricsDataPlaneNodeFilterByFieldMultiselectFilters,
		Type: typ,
	}
}

func CreateMetricsDataPlaneNodeFilterByFieldMetricsDataPlaneNodeFilterByFieldEmptyFilters(metricsDataPlaneNodeFilterByFieldEmptyFilters MetricsDataPlaneNodeFilterByFieldEmptyFilters) MetricsDataPlaneNodeFilterByField {
	typ := MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldEmptyFilters

	return MetricsDataPlaneNodeFilterByField{
		MetricsDataPlaneNodeFilterByFieldEmptyFilters: &metricsDataPlaneNodeFilterByFieldEmptyFilters,
		Type: typ,
	}
}

func (u *MetricsDataPlaneNodeFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var metricsDataPlaneNodeFilterByFieldMultiselectFilters MetricsDataPlaneNodeFilterByFieldMultiselectFilters = MetricsDataPlaneNodeFilterByFieldMultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeFilterByFieldMultiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldMultiselectFilters,
			Value: &metricsDataPlaneNodeFilterByFieldMultiselectFilters,
		})
	}

	var metricsDataPlaneNodeFilterByFieldEmptyFilters MetricsDataPlaneNodeFilterByFieldEmptyFilters = MetricsDataPlaneNodeFilterByFieldEmptyFilters{}
	if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeFilterByFieldEmptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldEmptyFilters,
			Value: &metricsDataPlaneNodeFilterByFieldEmptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsDataPlaneNodeFilterByFieldType)
	switch best.Type {
	case MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldMultiselectFilters:
		u.MetricsDataPlaneNodeFilterByFieldMultiselectFilters = best.Value.(*MetricsDataPlaneNodeFilterByFieldMultiselectFilters)
		return nil
	case MetricsDataPlaneNodeFilterByFieldTypeMetricsDataPlaneNodeFilterByFieldEmptyFilters:
		u.MetricsDataPlaneNodeFilterByFieldEmptyFilters = best.Value.(*MetricsDataPlaneNodeFilterByFieldEmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeFilterByField", string(data))
}

func (u MetricsDataPlaneNodeFilterByField) MarshalJSON() ([]byte, error) {
	if u.MetricsDataPlaneNodeFilterByFieldMultiselectFilters != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeFilterByFieldMultiselectFilters, "", true)
	}

	if u.MetricsDataPlaneNodeFilterByFieldEmptyFilters != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeFilterByFieldEmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsDataPlaneNodeFilterByField: all fields are null")
}
