// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsA2aContextIDFilterByField2Field - The field to filter.
type MetricsA2aContextIDFilterByField2Field string

const (
	MetricsA2aContextIDFilterByField2FieldA2aContextID MetricsA2aContextIDFilterByField2Field = "a2a_context_id"
)

func (e MetricsA2aContextIDFilterByField2Field) ToPointer() *MetricsA2aContextIDFilterByField2Field {
	return &e
}
func (e *MetricsA2aContextIDFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "a2a_context_id":
		*e = MetricsA2aContextIDFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsA2aContextIDFilterByField2Field: %v", v)
	}
}

type EmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsA2aContextIDFilterByField2Field `json:"field"`
}

func (e EmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if e == nil {
		return RequestsFilterTypeEmpty("")
	}
	return e.Operator
}

func (e *EmptyFilters) GetField() MetricsA2aContextIDFilterByField2Field {
	if e == nil {
		return MetricsA2aContextIDFilterByField2Field("")
	}
	return e.Field
}

// MetricsA2aContextIDFilterByFieldField - The field to filter.
type MetricsA2aContextIDFilterByFieldField string

const (
	MetricsA2aContextIDFilterByFieldFieldA2aContextID MetricsA2aContextIDFilterByFieldField = "a2a_context_id"
)

func (e MetricsA2aContextIDFilterByFieldField) ToPointer() *MetricsA2aContextIDFilterByFieldField {
	return &e
}
func (e *MetricsA2aContextIDFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "a2a_context_id":
		*e = MetricsA2aContextIDFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsA2aContextIDFilterByFieldField: %v", v)
	}
}

type MultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The values to include in the results.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsA2aContextIDFilterByFieldField `json:"field"`
}

func (m MultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MultiselectFilters) GetField() MetricsA2aContextIDFilterByFieldField {
	if m == nil {
		return MetricsA2aContextIDFilterByFieldField("")
	}
	return m.Field
}

type MetricsA2aContextIDFilterByFieldType string

const (
	MetricsA2aContextIDFilterByFieldTypeMultiselectFilters MetricsA2aContextIDFilterByFieldType = "Multiselect filters"
	MetricsA2aContextIDFilterByFieldTypeEmptyFilters       MetricsA2aContextIDFilterByFieldType = "Empty filters"
)

type MetricsA2aContextIDFilterByField struct {
	MultiselectFilters *MultiselectFilters `queryParam:"inline" union:"member"`
	EmptyFilters       *EmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsA2aContextIDFilterByFieldType
}

func CreateMetricsA2aContextIDFilterByFieldMultiselectFilters(multiselectFilters MultiselectFilters) MetricsA2aContextIDFilterByField {
	typ := MetricsA2aContextIDFilterByFieldTypeMultiselectFilters

	return MetricsA2aContextIDFilterByField{
		MultiselectFilters: &multiselectFilters,
		Type:               typ,
	}
}

func CreateMetricsA2aContextIDFilterByFieldEmptyFilters(emptyFilters EmptyFilters) MetricsA2aContextIDFilterByField {
	typ := MetricsA2aContextIDFilterByFieldTypeEmptyFilters

	return MetricsA2aContextIDFilterByField{
		EmptyFilters: &emptyFilters,
		Type:         typ,
	}
}

func (u *MetricsA2aContextIDFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var multiselectFilters MultiselectFilters = MultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &multiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsA2aContextIDFilterByFieldTypeMultiselectFilters,
			Value: &multiselectFilters,
		})
	}

	var emptyFilters EmptyFilters = EmptyFilters{}
	if err := utils.UnmarshalJSON(data, &emptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsA2aContextIDFilterByFieldTypeEmptyFilters,
			Value: &emptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsA2aContextIDFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsA2aContextIDFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsA2aContextIDFilterByFieldType)
	switch best.Type {
	case MetricsA2aContextIDFilterByFieldTypeMultiselectFilters:
		u.MultiselectFilters = best.Value.(*MultiselectFilters)
		return nil
	case MetricsA2aContextIDFilterByFieldTypeEmptyFilters:
		u.EmptyFilters = best.Value.(*EmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsA2aContextIDFilterByField", string(data))
}

func (u MetricsA2aContextIDFilterByField) MarshalJSON() ([]byte, error) {
	if u.MultiselectFilters != nil {
		return utils.MarshalJSON(u.MultiselectFilters, "", true)
	}

	if u.EmptyFilters != nil {
		return utils.MarshalJSON(u.EmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsA2aContextIDFilterByField: all fields are null")
}
