// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsMcpToolNameFilterByField2Field - The field to filter.
type MetricsMcpToolNameFilterByField2Field string

const (
	MetricsMcpToolNameFilterByField2FieldMcpToolName MetricsMcpToolNameFilterByField2Field = "mcp_tool_name"
)

func (e MetricsMcpToolNameFilterByField2Field) ToPointer() *MetricsMcpToolNameFilterByField2Field {
	return &e
}
func (e *MetricsMcpToolNameFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp_tool_name":
		*e = MetricsMcpToolNameFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsMcpToolNameFilterByField2Field: %v", v)
	}
}

type MetricsMcpToolNameFilterByFieldEmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsMcpToolNameFilterByField2Field `json:"field"`
}

func (m MetricsMcpToolNameFilterByFieldEmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsMcpToolNameFilterByFieldEmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsMcpToolNameFilterByFieldEmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if m == nil {
		return RequestsFilterTypeEmpty("")
	}
	return m.Operator
}

func (m *MetricsMcpToolNameFilterByFieldEmptyFilters) GetField() MetricsMcpToolNameFilterByField2Field {
	if m == nil {
		return MetricsMcpToolNameFilterByField2Field("")
	}
	return m.Field
}

// MetricsMcpToolNameFilterByFieldField - The field to filter.
type MetricsMcpToolNameFilterByFieldField string

const (
	MetricsMcpToolNameFilterByFieldFieldMcpToolName MetricsMcpToolNameFilterByFieldField = "mcp_tool_name"
)

func (e MetricsMcpToolNameFilterByFieldField) ToPointer() *MetricsMcpToolNameFilterByFieldField {
	return &e
}
func (e *MetricsMcpToolNameFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp_tool_name":
		*e = MetricsMcpToolNameFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsMcpToolNameFilterByFieldField: %v", v)
	}
}

type MetricsMcpToolNameFilterByFieldMultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The values to include in the results.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsMcpToolNameFilterByFieldField `json:"field"`
}

func (m MetricsMcpToolNameFilterByFieldMultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsMcpToolNameFilterByFieldMultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsMcpToolNameFilterByFieldMultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MetricsMcpToolNameFilterByFieldMultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MetricsMcpToolNameFilterByFieldMultiselectFilters) GetField() MetricsMcpToolNameFilterByFieldField {
	if m == nil {
		return MetricsMcpToolNameFilterByFieldField("")
	}
	return m.Field
}

type MetricsMcpToolNameFilterByFieldType string

const (
	MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldMultiselectFilters MetricsMcpToolNameFilterByFieldType = "MetricsMcpToolNameFilterByField_Multiselect filters"
	MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldEmptyFilters       MetricsMcpToolNameFilterByFieldType = "MetricsMcpToolNameFilterByField_Empty filters"
)

type MetricsMcpToolNameFilterByField struct {
	MetricsMcpToolNameFilterByFieldMultiselectFilters *MetricsMcpToolNameFilterByFieldMultiselectFilters `queryParam:"inline" union:"member"`
	MetricsMcpToolNameFilterByFieldEmptyFilters       *MetricsMcpToolNameFilterByFieldEmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsMcpToolNameFilterByFieldType
}

func CreateMetricsMcpToolNameFilterByFieldMetricsMcpToolNameFilterByFieldMultiselectFilters(metricsMcpToolNameFilterByFieldMultiselectFilters MetricsMcpToolNameFilterByFieldMultiselectFilters) MetricsMcpToolNameFilterByField {
	typ := MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldMultiselectFilters

	return MetricsMcpToolNameFilterByField{
		MetricsMcpToolNameFilterByFieldMultiselectFilters: &metricsMcpToolNameFilterByFieldMultiselectFilters,
		Type: typ,
	}
}

func CreateMetricsMcpToolNameFilterByFieldMetricsMcpToolNameFilterByFieldEmptyFilters(metricsMcpToolNameFilterByFieldEmptyFilters MetricsMcpToolNameFilterByFieldEmptyFilters) MetricsMcpToolNameFilterByField {
	typ := MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldEmptyFilters

	return MetricsMcpToolNameFilterByField{
		MetricsMcpToolNameFilterByFieldEmptyFilters: &metricsMcpToolNameFilterByFieldEmptyFilters,
		Type: typ,
	}
}

func (u *MetricsMcpToolNameFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var metricsMcpToolNameFilterByFieldMultiselectFilters MetricsMcpToolNameFilterByFieldMultiselectFilters = MetricsMcpToolNameFilterByFieldMultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &metricsMcpToolNameFilterByFieldMultiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldMultiselectFilters,
			Value: &metricsMcpToolNameFilterByFieldMultiselectFilters,
		})
	}

	var metricsMcpToolNameFilterByFieldEmptyFilters MetricsMcpToolNameFilterByFieldEmptyFilters = MetricsMcpToolNameFilterByFieldEmptyFilters{}
	if err := utils.UnmarshalJSON(data, &metricsMcpToolNameFilterByFieldEmptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldEmptyFilters,
			Value: &metricsMcpToolNameFilterByFieldEmptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsMcpToolNameFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsMcpToolNameFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsMcpToolNameFilterByFieldType)
	switch best.Type {
	case MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldMultiselectFilters:
		u.MetricsMcpToolNameFilterByFieldMultiselectFilters = best.Value.(*MetricsMcpToolNameFilterByFieldMultiselectFilters)
		return nil
	case MetricsMcpToolNameFilterByFieldTypeMetricsMcpToolNameFilterByFieldEmptyFilters:
		u.MetricsMcpToolNameFilterByFieldEmptyFilters = best.Value.(*MetricsMcpToolNameFilterByFieldEmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsMcpToolNameFilterByField", string(data))
}

func (u MetricsMcpToolNameFilterByField) MarshalJSON() ([]byte, error) {
	if u.MetricsMcpToolNameFilterByFieldMultiselectFilters != nil {
		return utils.MarshalJSON(u.MetricsMcpToolNameFilterByFieldMultiselectFilters, "", true)
	}

	if u.MetricsMcpToolNameFilterByFieldEmptyFilters != nil {
		return utils.MarshalJSON(u.MetricsMcpToolNameFilterByFieldEmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsMcpToolNameFilterByField: all fields are null")
}
