// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsPortalFilterByField2Field - The field to filter.
type MetricsPortalFilterByField2Field string

const (
	MetricsPortalFilterByField2FieldPortal MetricsPortalFilterByField2Field = "portal"
)

func (e MetricsPortalFilterByField2Field) ToPointer() *MetricsPortalFilterByField2Field {
	return &e
}
func (e *MetricsPortalFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "portal":
		*e = MetricsPortalFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsPortalFilterByField2Field: %v", v)
	}
}

type MetricsPortalFilterByFieldEmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsPortalFilterByField2Field `json:"field"`
}

func (m MetricsPortalFilterByFieldEmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsPortalFilterByFieldEmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsPortalFilterByFieldEmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if m == nil {
		return RequestsFilterTypeEmpty("")
	}
	return m.Operator
}

func (m *MetricsPortalFilterByFieldEmptyFilters) GetField() MetricsPortalFilterByField2Field {
	if m == nil {
		return MetricsPortalFilterByField2Field("")
	}
	return m.Field
}

// MetricsPortalFilterByFieldField - The field to filter.
type MetricsPortalFilterByFieldField string

const (
	MetricsPortalFilterByFieldFieldPortal MetricsPortalFilterByFieldField = "portal"
)

func (e MetricsPortalFilterByFieldField) ToPointer() *MetricsPortalFilterByFieldField {
	return &e
}
func (e *MetricsPortalFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "portal":
		*e = MetricsPortalFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsPortalFilterByFieldField: %v", v)
	}
}

type MetricsPortalFilterByFieldMultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The IDs to include in the results.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsPortalFilterByFieldField `json:"field"`
}

func (m MetricsPortalFilterByFieldMultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsPortalFilterByFieldMultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsPortalFilterByFieldMultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MetricsPortalFilterByFieldMultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MetricsPortalFilterByFieldMultiselectFilters) GetField() MetricsPortalFilterByFieldField {
	if m == nil {
		return MetricsPortalFilterByFieldField("")
	}
	return m.Field
}

type MetricsPortalFilterByFieldType string

const (
	MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldMultiselectFilters MetricsPortalFilterByFieldType = "MetricsPortalFilterByField_Multiselect filters"
	MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldEmptyFilters       MetricsPortalFilterByFieldType = "MetricsPortalFilterByField_Empty filters"
)

type MetricsPortalFilterByField struct {
	MetricsPortalFilterByFieldMultiselectFilters *MetricsPortalFilterByFieldMultiselectFilters `queryParam:"inline" union:"member"`
	MetricsPortalFilterByFieldEmptyFilters       *MetricsPortalFilterByFieldEmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsPortalFilterByFieldType
}

func CreateMetricsPortalFilterByFieldMetricsPortalFilterByFieldMultiselectFilters(metricsPortalFilterByFieldMultiselectFilters MetricsPortalFilterByFieldMultiselectFilters) MetricsPortalFilterByField {
	typ := MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldMultiselectFilters

	return MetricsPortalFilterByField{
		MetricsPortalFilterByFieldMultiselectFilters: &metricsPortalFilterByFieldMultiselectFilters,
		Type: typ,
	}
}

func CreateMetricsPortalFilterByFieldMetricsPortalFilterByFieldEmptyFilters(metricsPortalFilterByFieldEmptyFilters MetricsPortalFilterByFieldEmptyFilters) MetricsPortalFilterByField {
	typ := MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldEmptyFilters

	return MetricsPortalFilterByField{
		MetricsPortalFilterByFieldEmptyFilters: &metricsPortalFilterByFieldEmptyFilters,
		Type:                                   typ,
	}
}

func (u *MetricsPortalFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var metricsPortalFilterByFieldMultiselectFilters MetricsPortalFilterByFieldMultiselectFilters = MetricsPortalFilterByFieldMultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &metricsPortalFilterByFieldMultiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldMultiselectFilters,
			Value: &metricsPortalFilterByFieldMultiselectFilters,
		})
	}

	var metricsPortalFilterByFieldEmptyFilters MetricsPortalFilterByFieldEmptyFilters = MetricsPortalFilterByFieldEmptyFilters{}
	if err := utils.UnmarshalJSON(data, &metricsPortalFilterByFieldEmptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldEmptyFilters,
			Value: &metricsPortalFilterByFieldEmptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsPortalFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsPortalFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsPortalFilterByFieldType)
	switch best.Type {
	case MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldMultiselectFilters:
		u.MetricsPortalFilterByFieldMultiselectFilters = best.Value.(*MetricsPortalFilterByFieldMultiselectFilters)
		return nil
	case MetricsPortalFilterByFieldTypeMetricsPortalFilterByFieldEmptyFilters:
		u.MetricsPortalFilterByFieldEmptyFilters = best.Value.(*MetricsPortalFilterByFieldEmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsPortalFilterByField", string(data))
}

func (u MetricsPortalFilterByField) MarshalJSON() ([]byte, error) {
	if u.MetricsPortalFilterByFieldMultiselectFilters != nil {
		return utils.MarshalJSON(u.MetricsPortalFilterByFieldMultiselectFilters, "", true)
	}

	if u.MetricsPortalFilterByFieldEmptyFilters != nil {
		return utils.MarshalJSON(u.MetricsPortalFilterByFieldEmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsPortalFilterByField: all fields are null")
}
