// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// MetricsDataPlaneNodeVersionFilterByField2Field - The field to filter.
type MetricsDataPlaneNodeVersionFilterByField2Field string

const (
	MetricsDataPlaneNodeVersionFilterByField2FieldDataPlaneNodeVersion MetricsDataPlaneNodeVersionFilterByField2Field = "data_plane_node_version"
)

func (e MetricsDataPlaneNodeVersionFilterByField2Field) ToPointer() *MetricsDataPlaneNodeVersionFilterByField2Field {
	return &e
}
func (e *MetricsDataPlaneNodeVersionFilterByField2Field) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "data_plane_node_version":
		*e = MetricsDataPlaneNodeVersionFilterByField2Field(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsDataPlaneNodeVersionFilterByField2Field: %v", v)
	}
}

type MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters struct {
	// The type of filter to apply.
	Operator RequestsFilterTypeEmpty `json:"operator"`
	// The field to filter.
	Field MetricsDataPlaneNodeVersionFilterByField2Field `json:"field"`
}

func (m MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters) GetOperator() RequestsFilterTypeEmpty {
	if m == nil {
		return RequestsFilterTypeEmpty("")
	}
	return m.Operator
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters) GetField() MetricsDataPlaneNodeVersionFilterByField2Field {
	if m == nil {
		return MetricsDataPlaneNodeVersionFilterByField2Field("")
	}
	return m.Field
}

// MetricsDataPlaneNodeVersionFilterByFieldField - The field to filter.
type MetricsDataPlaneNodeVersionFilterByFieldField string

const (
	MetricsDataPlaneNodeVersionFilterByFieldFieldDataPlaneNodeVersion MetricsDataPlaneNodeVersionFilterByFieldField = "data_plane_node_version"
)

func (e MetricsDataPlaneNodeVersionFilterByFieldField) ToPointer() *MetricsDataPlaneNodeVersionFilterByFieldField {
	return &e
}
func (e *MetricsDataPlaneNodeVersionFilterByFieldField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "data_plane_node_version":
		*e = MetricsDataPlaneNodeVersionFilterByFieldField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MetricsDataPlaneNodeVersionFilterByFieldField: %v", v)
	}
}

type MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters struct {
	// The type of filter to apply.  `in` filters will limit results to only the specified values, while `not_in` filters will exclude the specified values.
	Operator RequestsFilterType `json:"operator"`
	// The values to include in the results.
	//
	Value []string `json:"value"`
	// The field to filter.
	Field MetricsDataPlaneNodeVersionFilterByFieldField `json:"field"`
}

func (m MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) GetOperator() RequestsFilterType {
	if m == nil {
		return RequestsFilterType("")
	}
	return m.Operator
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) GetValue() []string {
	if m == nil {
		return []string{}
	}
	return m.Value
}

func (m *MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) GetField() MetricsDataPlaneNodeVersionFilterByFieldField {
	if m == nil {
		return MetricsDataPlaneNodeVersionFilterByFieldField("")
	}
	return m.Field
}

type MetricsDataPlaneNodeVersionFilterByFieldType string

const (
	MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters MetricsDataPlaneNodeVersionFilterByFieldType = "MetricsDataPlaneNodeVersionFilterByField_Multiselect filters"
	MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldEmptyFilters       MetricsDataPlaneNodeVersionFilterByFieldType = "MetricsDataPlaneNodeVersionFilterByField_Empty filters"
)

type MetricsDataPlaneNodeVersionFilterByField struct {
	MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters *MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters `queryParam:"inline" union:"member"`
	MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters       *MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters       `queryParam:"inline" union:"member"`

	Type MetricsDataPlaneNodeVersionFilterByFieldType
}

func CreateMetricsDataPlaneNodeVersionFilterByFieldMetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters(metricsDataPlaneNodeVersionFilterByFieldMultiselectFilters MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters) MetricsDataPlaneNodeVersionFilterByField {
	typ := MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters

	return MetricsDataPlaneNodeVersionFilterByField{
		MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters: &metricsDataPlaneNodeVersionFilterByFieldMultiselectFilters,
		Type: typ,
	}
}

func CreateMetricsDataPlaneNodeVersionFilterByFieldMetricsDataPlaneNodeVersionFilterByFieldEmptyFilters(metricsDataPlaneNodeVersionFilterByFieldEmptyFilters MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters) MetricsDataPlaneNodeVersionFilterByField {
	typ := MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldEmptyFilters

	return MetricsDataPlaneNodeVersionFilterByField{
		MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters: &metricsDataPlaneNodeVersionFilterByFieldEmptyFilters,
		Type: typ,
	}
}

func (u *MetricsDataPlaneNodeVersionFilterByField) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var metricsDataPlaneNodeVersionFilterByFieldMultiselectFilters MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters = MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters{}
	if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeVersionFilterByFieldMultiselectFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters,
			Value: &metricsDataPlaneNodeVersionFilterByFieldMultiselectFilters,
		})
	}

	var metricsDataPlaneNodeVersionFilterByFieldEmptyFilters MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters = MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters{}
	if err := utils.UnmarshalJSON(data, &metricsDataPlaneNodeVersionFilterByFieldEmptyFilters, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldEmptyFilters,
			Value: &metricsDataPlaneNodeVersionFilterByFieldEmptyFilters,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeVersionFilterByField", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeVersionFilterByField", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MetricsDataPlaneNodeVersionFilterByFieldType)
	switch best.Type {
	case MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters:
		u.MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters = best.Value.(*MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters)
		return nil
	case MetricsDataPlaneNodeVersionFilterByFieldTypeMetricsDataPlaneNodeVersionFilterByFieldEmptyFilters:
		u.MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters = best.Value.(*MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MetricsDataPlaneNodeVersionFilterByField", string(data))
}

func (u MetricsDataPlaneNodeVersionFilterByField) MarshalJSON() ([]byte, error) {
	if u.MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeVersionFilterByFieldMultiselectFilters, "", true)
	}

	if u.MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters != nil {
		return utils.MarshalJSON(u.MetricsDataPlaneNodeVersionFilterByFieldEmptyFilters, "", true)
	}

	return nil, errors.New("could not marshal union type MetricsDataPlaneNodeVersionFilterByField: all fields are null")
}
