// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// PathSelector - Configuration for routing requests to a specific model using a path selector.
type PathSelector struct {
	// Value that will cause this route to match if present in the request path.
	//
	PathAliases []string `json:"path_aliases"`
}

func (p PathSelector) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PathSelector) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PathSelector) GetPathAliases() []string {
	if p == nil {
		return []string{}
	}
	return p.PathAliases
}
