// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ReferenceByID - A static encryption key reference by ID.
type ReferenceByID struct {
	// The ID of the static key defined in the key source.
	ID string `json:"id"`
}

func (o *ReferenceByID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
