// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
	"time"
)

// SchemaRegistryConfluentResponse - A Confluent schema registry.
type SchemaRegistryConfluentResponse struct {
	// The unique name of the schema registry.
	Name string `json:"name"`
	// A human-readable description of the virtual cluster.
	Description *string `default:"" json:"description"`
	// The type of the schema registry.
	type_ string `const:"confluent" json:"type"`
	// The configuration of [Confluent Schema Registry](https://github.com/confluentinc/schema-registry)
	//
	Config SchemaRegistryConfluentConfig `json:"config"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
	// The unique identifier of the schema registry.
	ID string `json:"id"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (s SchemaRegistryConfluentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemaRegistryConfluentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemaRegistryConfluentResponse) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SchemaRegistryConfluentResponse) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SchemaRegistryConfluentResponse) GetType() string {
	return "confluent"
}

func (s *SchemaRegistryConfluentResponse) GetConfig() SchemaRegistryConfluentConfig {
	if s == nil {
		return SchemaRegistryConfluentConfig{}
	}
	return s.Config
}

func (s *SchemaRegistryConfluentResponse) GetLabels() map[string]*string {
	if s == nil {
		return nil
	}
	return s.Labels
}

func (s *SchemaRegistryConfluentResponse) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SchemaRegistryConfluentResponse) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SchemaRegistryConfluentResponse) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
