// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// SecretList - List
type SecretList struct {
	Items []SecretItem `json:"items"`
	// The total number of entities
	Total *float64 `default:"null" json:"total"`
	// URL to the next page
	Next *string `default:"null" json:"next"`
}

func (s SecretList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecretList) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SecretList) GetItems() []SecretItem {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *SecretList) GetTotal() *float64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *SecretList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}
