// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TooManyRequestsError - standard error
type TooManyRequestsError struct {
	Status   any `json:"status"`
	Title    any `json:"title"`
	Type     any `json:"type,omitempty"`
	Instance any `json:"instance"`
	Detail   any `json:"detail"`
}

func (t *TooManyRequestsError) GetStatus() any {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TooManyRequestsError) GetTitle() any {
	if t == nil {
		return nil
	}
	return t.Title
}

func (t *TooManyRequestsError) GetType() any {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TooManyRequestsError) GetInstance() any {
	if t == nil {
		return nil
	}
	return t.Instance
}

func (t *TooManyRequestsError) GetDetail() any {
	if t == nil {
		return nil
	}
	return t.Detail
}
