// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpdateGatewayRequest - The request schema for the update gateway request.
type UpdateGatewayRequest struct {
	// The name of the Gateway.
	Name *string `json:"name,omitempty"`
	// A human-readable description of the Gateway.
	Description *string `json:"description,omitempty"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
}

func (o *UpdateGatewayRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateGatewayRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateGatewayRequest) GetLabels() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Labels
}
