// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

type URLProviderType string

const (
	URLProviderTypeURL URLProviderType = "url"
)

func (e URLProviderType) ToPointer() *URLProviderType {
	return &e
}
func (e *URLProviderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "url":
		*e = URLProviderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for URLProviderType: %v", v)
	}
}

type Config struct {
	// Public URL that resolves to the raw API spec contents.
	// Supported formats are JSON and YAML.
	//
	URL string `json:"url"`
}

func (c Config) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Config) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Config) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type URLProvider struct {
	Type   URLProviderType `json:"type"`
	Config Config          `json:"config"`
}

func (u URLProvider) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *URLProvider) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *URLProvider) GetType() URLProviderType {
	if u == nil {
		return URLProviderType("")
	}
	return u.Type
}

func (u *URLProvider) GetConfig() Config {
	if u == nil {
		return Config{}
	}
	return u.Config
}
