// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type VirtualClusterNamespaceAdditionalProperties struct {
	// Additional backend topics to expose even if they don't match the namespace prefix.
	// The topics are not affected by the hide/enforce prefix mode.
	// If the client tries to create a topic that matches this list, the request is rejected.
	//
	Topics []VirtualClusterNamespaceTopicSelector `json:"topics,omitempty"`
	// Consumer group IDs to expose even if they don't start with the namespace prefix.
	//
	ConsumerGroups []VirtualClusterNamespaceIDSelector `json:"consumer_groups,omitempty"`
}

func (o *VirtualClusterNamespaceAdditionalProperties) GetTopics() []VirtualClusterNamespaceTopicSelector {
	if o == nil {
		return nil
	}
	return o.Topics
}

func (o *VirtualClusterNamespaceAdditionalProperties) GetConsumerGroups() []VirtualClusterNamespaceIDSelector {
	if o == nil {
		return nil
	}
	return o.ConsumerGroups
}
