// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/internal/utils"
)

// ZoneIngressList - List
type ZoneIngressList struct {
	Items []ZoneIngressItem `json:"items"`
	// The total number of entities
	Total *float64 `default:"null" json:"total"`
	// URL to the next page
	Next *string `default:"null" json:"next"`
}

func (z ZoneIngressList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(z, "", false)
}

func (z *ZoneIngressList) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &z, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (z *ZoneIngressList) GetItems() []ZoneIngressItem {
	if z == nil {
		return nil
	}
	return z.Items
}

func (z *ZoneIngressList) GetTotal() *float64 {
	if z == nil {
		return nil
	}
	return z.Total
}

func (z *ZoneIngressList) GetNext() *string {
	if z == nil {
		return nil
	}
	return z.Next
}
