// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-konnect-beta/internal/provider/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
)

func (r *CloudGatewayAddOnResourceModel) RefreshFromSharedAddOnResponse(ctx context.Context, resp *shared.AddOnResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Config.ManagedCacheAddOnConfigResponse != nil {
			r.Config.ManagedCacheAddOnConfigResponse = &tfTypes.ManagedCacheAddOnConfigResponse{}
			if resp.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig != nil {
				r.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig = &tfTypes.TieredCapacityConfig{}
				r.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig.Kind = types.StringValue(string(resp.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig.Kind))
				r.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig.Tier = types.StringValue(string(resp.Config.ManagedCacheAddOnConfigResponse.CapacityConfig.TieredCapacityConfig.Tier))
			}
			r.Config.ManagedCacheAddOnConfigResponse.DataPlaneGroups = []tfTypes.ManagedCacheAddOnDataPlaneGroup{}

			for _, dataPlaneGroupsItem := range resp.Config.ManagedCacheAddOnConfigResponse.DataPlaneGroups {
				var dataPlaneGroups tfTypes.ManagedCacheAddOnDataPlaneGroup

				dataPlaneGroups.CloudGatewayNetworkID = types.StringValue(dataPlaneGroupsItem.CloudGatewayNetworkID)
				dataPlaneGroups.ID = types.StringValue(dataPlaneGroupsItem.ID)
				dataPlaneGroups.Provider = types.StringValue(string(dataPlaneGroupsItem.Provider))
				dataPlaneGroups.Region = types.StringValue(dataPlaneGroupsItem.Region)
				dataPlaneGroups.State = types.StringValue(string(dataPlaneGroupsItem.State))
				dataPlaneGroups.StateMetadata.ErrorReason = types.StringPointerValue(dataPlaneGroupsItem.StateMetadata.ErrorReason)

				r.Config.ManagedCacheAddOnConfigResponse.DataPlaneGroups = append(r.Config.ManagedCacheAddOnConfigResponse.DataPlaneGroups, dataPlaneGroups)
			}
			r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheConfigID = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheConfigID)
			r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheHost = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheHost)
			r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CachePort = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CachePort)
			r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheServerName = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheServerName)
			r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheUsername = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CacheUsername)
			if resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication == nil {
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication = nil
			} else {
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication = &tfTypes.CloudAuthentication{}
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AuthProvider = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AuthProvider)
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsAssumeRoleArn = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsAssumeRoleArn)
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsCacheName = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsCacheName)
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsRegion = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AwsRegion)
				r.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AzureTenantID = types.StringPointerValue(resp.Config.ManagedCacheAddOnConfigResponse.StateMetadata.CloudAuthentication.AzureTenantID)
			}
		}
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.EntityVersion = types.Int64Value(resp.EntityVersion)
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		if resp.Owner.ControlPlaneAddOnOwner != nil {
			r.Owner.ControlPlaneAddOnOwner = &tfTypes.ControlPlaneAddOnOwner{}
			r.Owner.ControlPlaneAddOnOwner.ControlPlaneGeo = types.StringValue(string(resp.Owner.ControlPlaneAddOnOwner.ControlPlaneGeo))
			r.Owner.ControlPlaneAddOnOwner.ControlPlaneID = types.StringValue(resp.Owner.ControlPlaneAddOnOwner.ControlPlaneID)
		}
		if resp.Owner.ControlPlaneGroupAddOnOwner != nil {
			r.Owner.ControlPlaneGroupAddOnOwner = &tfTypes.ControlPlaneGroupAddOnOwner{}
			r.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupGeo = types.StringValue(string(resp.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupGeo))
			r.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupID = types.StringValue(resp.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupID)
		}
		r.State = types.StringValue(string(resp.State))
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
	}

	return diags
}

func (r *CloudGatewayAddOnResourceModel) ToOperationsDeleteAddOnRequest(ctx context.Context) (*operations.DeleteAddOnRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var addOnID string
	addOnID = r.ID.ValueString()

	out := operations.DeleteAddOnRequest{
		AddOnID: addOnID,
	}

	return &out, diags
}

func (r *CloudGatewayAddOnResourceModel) ToOperationsGetAddOnRequest(ctx context.Context) (*operations.GetAddOnRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var addOnID string
	addOnID = r.ID.ValueString()

	out := operations.GetAddOnRequest{
		AddOnID: addOnID,
	}

	return &out, diags
}

func (r *CloudGatewayAddOnResourceModel) ToSharedCreateAddOnRequest(ctx context.Context) (*shared.CreateAddOnRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var owner shared.AddOnOwner
	var controlPlaneAddOnOwner *shared.ControlPlaneAddOnOwner
	if r.Owner.ControlPlaneAddOnOwner != nil {
		var controlPlaneID string
		controlPlaneID = r.Owner.ControlPlaneAddOnOwner.ControlPlaneID.ValueString()

		controlPlaneGeo := shared.ControlPlaneGeo(r.Owner.ControlPlaneAddOnOwner.ControlPlaneGeo.ValueString())
		controlPlaneAddOnOwner = &shared.ControlPlaneAddOnOwner{
			ControlPlaneID:  controlPlaneID,
			ControlPlaneGeo: controlPlaneGeo,
		}
	}
	if controlPlaneAddOnOwner != nil {
		owner = shared.AddOnOwner{
			ControlPlaneAddOnOwner: controlPlaneAddOnOwner,
		}
	}
	var controlPlaneGroupAddOnOwner *shared.ControlPlaneGroupAddOnOwner
	if r.Owner.ControlPlaneGroupAddOnOwner != nil {
		var controlPlaneGroupID string
		controlPlaneGroupID = r.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupID.ValueString()

		controlPlaneGroupGeo := shared.ControlPlaneGeo(r.Owner.ControlPlaneGroupAddOnOwner.ControlPlaneGroupGeo.ValueString())
		controlPlaneGroupAddOnOwner = &shared.ControlPlaneGroupAddOnOwner{
			ControlPlaneGroupID:  controlPlaneGroupID,
			ControlPlaneGroupGeo: controlPlaneGroupGeo,
		}
	}
	if controlPlaneGroupAddOnOwner != nil {
		owner = shared.AddOnOwner{
			ControlPlaneGroupAddOnOwner: controlPlaneGroupAddOnOwner,
		}
	}
	var config shared.CreateAddOnConfig
	var createManagedCacheAddOnConfig *shared.CreateManagedCacheAddOnConfig
	if r.Config.CreateManagedCacheAddOnConfig != nil {
		var capacityConfig shared.ManagedCacheCapacityConfig
		var tieredCapacityConfig *shared.TieredCapacityConfig
		if r.Config.CreateManagedCacheAddOnConfig.CapacityConfig.TieredCapacityConfig != nil {
			kind := shared.Kind(r.Config.CreateManagedCacheAddOnConfig.CapacityConfig.TieredCapacityConfig.Kind.ValueString())
			tier := shared.Tier(r.Config.CreateManagedCacheAddOnConfig.CapacityConfig.TieredCapacityConfig.Tier.ValueString())
			tieredCapacityConfig = &shared.TieredCapacityConfig{
				Kind: kind,
				Tier: tier,
			}
		}
		if tieredCapacityConfig != nil {
			capacityConfig = shared.ManagedCacheCapacityConfig{
				TieredCapacityConfig: tieredCapacityConfig,
			}
		}
		createManagedCacheAddOnConfig = &shared.CreateManagedCacheAddOnConfig{
			CapacityConfig: capacityConfig,
		}
	}
	if createManagedCacheAddOnConfig != nil {
		config = shared.CreateAddOnConfig{
			CreateManagedCacheAddOnConfig: createManagedCacheAddOnConfig,
		}
	}
	out := shared.CreateAddOnRequest{
		Name:   name,
		Owner:  owner,
		Config: config,
	}

	return &out, diags
}
