// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
)

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) RefreshFromSharedEventGatewayPolicy(ctx context.Context, resp *shared.EventGatewayPolicy) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Condition = types.StringPointerValue(resp.Condition)
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.ID = types.StringValue(resp.ID)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringPointerValue(value)
			}
		}
		r.Name = types.StringPointerValue(resp.Name)
		r.ParentPolicyID = types.StringPointerValue(resp.ParentPolicyID)
		r.Type = types.StringValue(resp.Type)
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
	}

	return diags
}

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) ToOperationsCreateEventGatewayVirtualClusterProducePolicyRequest(ctx context.Context) (*operations.CreateEventGatewayVirtualClusterProducePolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var gatewayID string
	gatewayID = r.GatewayID.ValueString()

	var virtualClusterID string
	virtualClusterID = r.VirtualClusterID.ValueString()

	parentPolicyID := new(string)
	if !r.ParentPolicyID.IsUnknown() && !r.ParentPolicyID.IsNull() {
		*parentPolicyID = r.ParentPolicyID.ValueString()
	} else {
		parentPolicyID = nil
	}
	eventGatewayProducePolicyModify, eventGatewayProducePolicyModifyDiags := r.ToSharedEventGatewayProducePolicyModify(ctx)
	diags.Append(eventGatewayProducePolicyModifyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateEventGatewayVirtualClusterProducePolicyRequest{
		GatewayID:                       gatewayID,
		VirtualClusterID:                virtualClusterID,
		ParentPolicyID:                  parentPolicyID,
		EventGatewayProducePolicyModify: eventGatewayProducePolicyModify,
	}

	return &out, diags
}

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) ToOperationsDeleteEventGatewayVirtualClusterProducePolicyRequest(ctx context.Context) (*operations.DeleteEventGatewayVirtualClusterProducePolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var gatewayID string
	gatewayID = r.GatewayID.ValueString()

	var virtualClusterID string
	virtualClusterID = r.VirtualClusterID.ValueString()

	var policyID string
	policyID = r.ID.ValueString()

	out := operations.DeleteEventGatewayVirtualClusterProducePolicyRequest{
		GatewayID:        gatewayID,
		VirtualClusterID: virtualClusterID,
		PolicyID:         policyID,
	}

	return &out, diags
}

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) ToOperationsGetEventGatewayVirtualClusterProducePolicyRequest(ctx context.Context) (*operations.GetEventGatewayVirtualClusterProducePolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var gatewayID string
	gatewayID = r.GatewayID.ValueString()

	var virtualClusterID string
	virtualClusterID = r.VirtualClusterID.ValueString()

	var policyID string
	policyID = r.ID.ValueString()

	out := operations.GetEventGatewayVirtualClusterProducePolicyRequest{
		GatewayID:        gatewayID,
		VirtualClusterID: virtualClusterID,
		PolicyID:         policyID,
	}

	return &out, diags
}

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) ToOperationsUpdateEventGatewayVirtualClusterProducePolicyRequest(ctx context.Context) (*operations.UpdateEventGatewayVirtualClusterProducePolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var gatewayID string
	gatewayID = r.GatewayID.ValueString()

	var virtualClusterID string
	virtualClusterID = r.VirtualClusterID.ValueString()

	var policyID string
	policyID = r.ID.ValueString()

	eventGatewayProducePolicyModify, eventGatewayProducePolicyModifyDiags := r.ToSharedEventGatewayProducePolicyModify(ctx)
	diags.Append(eventGatewayProducePolicyModifyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateEventGatewayVirtualClusterProducePolicyRequest{
		GatewayID:                       gatewayID,
		VirtualClusterID:                virtualClusterID,
		PolicyID:                        policyID,
		EventGatewayProducePolicyModify: eventGatewayProducePolicyModify,
	}

	return &out, diags
}

func (r *EventGatewayVirtualClusterProducePolicyResourceModel) ToSharedEventGatewayProducePolicyModify(ctx context.Context) (*shared.EventGatewayProducePolicyModify, diag.Diagnostics) {
	var diags diag.Diagnostics

	var out shared.EventGatewayProducePolicyModify
	var eventGatewayModifyHeadersPolicy *shared.EventGatewayModifyHeadersPolicy
	if r.ModifyHeaders != nil {
		typeVar := shared.EventGatewayModifyHeadersPolicyType(r.ModifyHeaders.Type.ValueString())
		name := new(string)
		if !r.ModifyHeaders.Name.IsUnknown() && !r.ModifyHeaders.Name.IsNull() {
			*name = r.ModifyHeaders.Name.ValueString()
		} else {
			name = nil
		}
		description := new(string)
		if !r.ModifyHeaders.Description.IsUnknown() && !r.ModifyHeaders.Description.IsNull() {
			*description = r.ModifyHeaders.Description.ValueString()
		} else {
			description = nil
		}
		enabled := new(bool)
		if !r.ModifyHeaders.Enabled.IsUnknown() && !r.ModifyHeaders.Enabled.IsNull() {
			*enabled = r.ModifyHeaders.Enabled.ValueBool()
		} else {
			enabled = nil
		}
		condition := new(string)
		if !r.ModifyHeaders.Condition.IsUnknown() && !r.ModifyHeaders.Condition.IsNull() {
			*condition = r.ModifyHeaders.Condition.ValueString()
		} else {
			condition = nil
		}
		var actions []shared.EventGatewayModifyHeaderAction
		if r.ModifyHeaders.Config.Actions != nil {
			actions = make([]shared.EventGatewayModifyHeaderAction, 0, len(r.ModifyHeaders.Config.Actions))
			for _, actionsItem := range r.ModifyHeaders.Config.Actions {
				if actionsItem.Remove != nil {
					op := shared.Op(actionsItem.Remove.Op.ValueString())
					var key string
					key = actionsItem.Remove.Key.ValueString()

					eventGatewayModifyHeaderRemoveAction := shared.EventGatewayModifyHeaderRemoveAction{
						Op:  op,
						Key: key,
					}
					actions = append(actions, shared.EventGatewayModifyHeaderAction{
						EventGatewayModifyHeaderRemoveAction: &eventGatewayModifyHeaderRemoveAction,
					})
				}
				if actionsItem.Set != nil {
					op1 := shared.EventGatewayModifyHeaderSetActionOp(actionsItem.Set.Op.ValueString())
					var key1 string
					key1 = actionsItem.Set.Key.ValueString()

					var value string
					value = actionsItem.Set.Value.ValueString()

					eventGatewayModifyHeaderSetAction := shared.EventGatewayModifyHeaderSetAction{
						Op:    op1,
						Key:   key1,
						Value: value,
					}
					actions = append(actions, shared.EventGatewayModifyHeaderAction{
						EventGatewayModifyHeaderSetAction: &eventGatewayModifyHeaderSetAction,
					})
				}
			}
		}
		config := shared.EventGatewayModifyHeadersPolicyConfig{
			Actions: actions,
		}
		labels := make(map[string]*string)
		for labelsKey, labelsValue := range r.ModifyHeaders.Labels {
			labelsInst := new(string)
			if !labelsValue.IsUnknown() && !labelsValue.IsNull() {
				*labelsInst = labelsValue.ValueString()
			} else {
				labelsInst = nil
			}
			labels[labelsKey] = labelsInst
		}
		eventGatewayModifyHeadersPolicy = &shared.EventGatewayModifyHeadersPolicy{
			Type:        typeVar,
			Name:        name,
			Description: description,
			Enabled:     enabled,
			Condition:   condition,
			Config:      config,
			Labels:      labels,
		}
	}
	if eventGatewayModifyHeadersPolicy != nil {
		out = shared.EventGatewayProducePolicyModify{
			EventGatewayModifyHeadersPolicy: eventGatewayModifyHeadersPolicy,
		}
	}
	var eventGatewayProduceSchemaValidationPolicy *shared.EventGatewayProduceSchemaValidationPolicy
	if r.SchemaValidation != nil {
		typeVar1 := shared.EventGatewayProduceSchemaValidationPolicyType(r.SchemaValidation.Type.ValueString())
		name1 := new(string)
		if !r.SchemaValidation.Name.IsUnknown() && !r.SchemaValidation.Name.IsNull() {
			*name1 = r.SchemaValidation.Name.ValueString()
		} else {
			name1 = nil
		}
		description1 := new(string)
		if !r.SchemaValidation.Description.IsUnknown() && !r.SchemaValidation.Description.IsNull() {
			*description1 = r.SchemaValidation.Description.ValueString()
		} else {
			description1 = nil
		}
		enabled1 := new(bool)
		if !r.SchemaValidation.Enabled.IsUnknown() && !r.SchemaValidation.Enabled.IsNull() {
			*enabled1 = r.SchemaValidation.Enabled.ValueBool()
		} else {
			enabled1 = nil
		}
		condition1 := new(string)
		if !r.SchemaValidation.Condition.IsUnknown() && !r.SchemaValidation.Condition.IsNull() {
			*condition1 = r.SchemaValidation.Condition.ValueString()
		} else {
			condition1 = nil
		}
		var config1 shared.EventGatewayProduceSchemaValidationPolicyConfig
		var eventGatewayProduceSchemaValidationPolicySchemaRegistryConfig *shared.EventGatewayProduceSchemaValidationPolicySchemaRegistryConfig
		if r.SchemaValidation.Config.ConfluentSchemaRegistry != nil {
			var schemaRegistry *shared.SchemaRegistryReference
			if r.SchemaValidation.Config.ConfluentSchemaRegistry.SchemaRegistry != nil {
				var schemaRegistryReferenceByID *shared.SchemaRegistryReferenceByID
				if r.SchemaValidation.Config.ConfluentSchemaRegistry.SchemaRegistry.SchemaRegistryReferenceByID != nil {
					var id string
					id = r.SchemaValidation.Config.ConfluentSchemaRegistry.SchemaRegistry.SchemaRegistryReferenceByID.ID.ValueString()

					schemaRegistryReferenceByID = &shared.SchemaRegistryReferenceByID{
						ID: id,
					}
				}
				if schemaRegistryReferenceByID != nil {
					schemaRegistry = &shared.SchemaRegistryReference{
						SchemaRegistryReferenceByID: schemaRegistryReferenceByID,
					}
				}
				var schemaRegistryReferenceByName *shared.SchemaRegistryReferenceByName
				if r.SchemaValidation.Config.ConfluentSchemaRegistry.SchemaRegistry.SchemaRegistryReferenceByName != nil {
					var name2 string
					name2 = r.SchemaValidation.Config.ConfluentSchemaRegistry.SchemaRegistry.SchemaRegistryReferenceByName.Name.ValueString()

					schemaRegistryReferenceByName = &shared.SchemaRegistryReferenceByName{
						Name: name2,
					}
				}
				if schemaRegistryReferenceByName != nil {
					schemaRegistry = &shared.SchemaRegistryReference{
						SchemaRegistryReferenceByName: schemaRegistryReferenceByName,
					}
				}
			}
			keyValidationAction := shared.ProduceKeyValidationAction(r.SchemaValidation.Config.ConfluentSchemaRegistry.KeyValidationAction.ValueString())
			valueValidationAction := shared.ProduceValueValidationAction(r.SchemaValidation.Config.ConfluentSchemaRegistry.ValueValidationAction.ValueString())
			typeVar2 := shared.EventGatewayProduceSchemaValidationPolicySchemaRegistryConfigType(r.SchemaValidation.Config.ConfluentSchemaRegistry.Type.ValueString())
			eventGatewayProduceSchemaValidationPolicySchemaRegistryConfig = &shared.EventGatewayProduceSchemaValidationPolicySchemaRegistryConfig{
				SchemaRegistry:        schemaRegistry,
				KeyValidationAction:   keyValidationAction,
				ValueValidationAction: valueValidationAction,
				Type:                  typeVar2,
			}
		}
		if eventGatewayProduceSchemaValidationPolicySchemaRegistryConfig != nil {
			config1 = shared.EventGatewayProduceSchemaValidationPolicyConfig{
				EventGatewayProduceSchemaValidationPolicySchemaRegistryConfig: eventGatewayProduceSchemaValidationPolicySchemaRegistryConfig,
			}
		}
		var eventGatewayProduceSchemaValidationPolicyJSONConfig *shared.EventGatewayProduceSchemaValidationPolicyJSONConfig
		if r.SchemaValidation.Config.JSON != nil {
			var schemaRegistry1 *shared.SchemaRegistryReference
			if r.SchemaValidation.Config.JSON.SchemaRegistry != nil {
				var schemaRegistryReferenceById1 *shared.SchemaRegistryReferenceByID
				if r.SchemaValidation.Config.JSON.SchemaRegistry.SchemaRegistryReferenceByID != nil {
					var id1 string
					id1 = r.SchemaValidation.Config.JSON.SchemaRegistry.SchemaRegistryReferenceByID.ID.ValueString()

					schemaRegistryReferenceById1 = &shared.SchemaRegistryReferenceByID{
						ID: id1,
					}
				}
				if schemaRegistryReferenceById1 != nil {
					schemaRegistry1 = &shared.SchemaRegistryReference{
						SchemaRegistryReferenceByID: schemaRegistryReferenceById1,
					}
				}
				var schemaRegistryReferenceByName1 *shared.SchemaRegistryReferenceByName
				if r.SchemaValidation.Config.JSON.SchemaRegistry.SchemaRegistryReferenceByName != nil {
					var name3 string
					name3 = r.SchemaValidation.Config.JSON.SchemaRegistry.SchemaRegistryReferenceByName.Name.ValueString()

					schemaRegistryReferenceByName1 = &shared.SchemaRegistryReferenceByName{
						Name: name3,
					}
				}
				if schemaRegistryReferenceByName1 != nil {
					schemaRegistry1 = &shared.SchemaRegistryReference{
						SchemaRegistryReferenceByName: schemaRegistryReferenceByName1,
					}
				}
			}
			keyValidationAction1 := shared.ProduceKeyValidationAction(r.SchemaValidation.Config.JSON.KeyValidationAction.ValueString())
			valueValidationAction1 := shared.ProduceValueValidationAction(r.SchemaValidation.Config.JSON.ValueValidationAction.ValueString())
			typeVar3 := shared.EventGatewayProduceSchemaValidationPolicyJSONConfigType(r.SchemaValidation.Config.JSON.Type.ValueString())
			eventGatewayProduceSchemaValidationPolicyJSONConfig = &shared.EventGatewayProduceSchemaValidationPolicyJSONConfig{
				SchemaRegistry:        schemaRegistry1,
				KeyValidationAction:   keyValidationAction1,
				ValueValidationAction: valueValidationAction1,
				Type:                  typeVar3,
			}
		}
		if eventGatewayProduceSchemaValidationPolicyJSONConfig != nil {
			config1 = shared.EventGatewayProduceSchemaValidationPolicyConfig{
				EventGatewayProduceSchemaValidationPolicyJSONConfig: eventGatewayProduceSchemaValidationPolicyJSONConfig,
			}
		}
		labels1 := make(map[string]*string)
		for labelsKey1, labelsValue1 := range r.SchemaValidation.Labels {
			labelsInst1 := new(string)
			if !labelsValue1.IsUnknown() && !labelsValue1.IsNull() {
				*labelsInst1 = labelsValue1.ValueString()
			} else {
				labelsInst1 = nil
			}
			labels1[labelsKey1] = labelsInst1
		}
		eventGatewayProduceSchemaValidationPolicy = &shared.EventGatewayProduceSchemaValidationPolicy{
			Type:        typeVar1,
			Name:        name1,
			Description: description1,
			Enabled:     enabled1,
			Condition:   condition1,
			Config:      config1,
			Labels:      labels1,
		}
	}
	if eventGatewayProduceSchemaValidationPolicy != nil {
		out = shared.EventGatewayProducePolicyModify{
			EventGatewayProduceSchemaValidationPolicy: eventGatewayProduceSchemaValidationPolicy,
		}
	}
	var eventGatewayEncryptPolicy *shared.EventGatewayEncryptPolicy
	if r.Encrypt != nil {
		typeVar4 := shared.EventGatewayEncryptPolicyType(r.Encrypt.Type.ValueString())
		name4 := new(string)
		if !r.Encrypt.Name.IsUnknown() && !r.Encrypt.Name.IsNull() {
			*name4 = r.Encrypt.Name.ValueString()
		} else {
			name4 = nil
		}
		description2 := new(string)
		if !r.Encrypt.Description.IsUnknown() && !r.Encrypt.Description.IsNull() {
			*description2 = r.Encrypt.Description.ValueString()
		} else {
			description2 = nil
		}
		enabled2 := new(bool)
		if !r.Encrypt.Enabled.IsUnknown() && !r.Encrypt.Enabled.IsNull() {
			*enabled2 = r.Encrypt.Enabled.ValueBool()
		} else {
			enabled2 = nil
		}
		condition2 := new(string)
		if !r.Encrypt.Condition.IsUnknown() && !r.Encrypt.Condition.IsNull() {
			*condition2 = r.Encrypt.Condition.ValueString()
		} else {
			condition2 = nil
		}
		var config2 *shared.EventGatewayEncryptPolicyConfig
		if r.Encrypt.Config != nil {
			failureMode := shared.EncryptionFailureMode(r.Encrypt.Config.FailureMode.ValueString())
			keySources := make([]shared.EventGatewayKeySource, 0, len(r.Encrypt.Config.KeySources))
			for _, keySourcesItem := range r.Encrypt.Config.KeySources {
				if keySourcesItem.Aws != nil {
					typeVar5 := shared.EventGatewayAWSKeySourceType(keySourcesItem.Aws.Type.ValueString())
					eventGatewayAWSKeySource := shared.EventGatewayAWSKeySource{
						Type: typeVar5,
					}
					keySources = append(keySources, shared.EventGatewayKeySource{
						EventGatewayAWSKeySource: &eventGatewayAWSKeySource,
					})
				}
				if keySourcesItem.Static != nil {
					typeVar6 := shared.EventGatewayStaticKeySourceType(keySourcesItem.Static.Type.ValueString())
					keys := make([]shared.Keys, 0, len(keySourcesItem.Static.Keys))
					for _, keysItem := range keySourcesItem.Static.Keys {
						var id2 string
						id2 = keysItem.ID.ValueString()

						var key2 string
						key2 = keysItem.Key.ValueString()

						keys = append(keys, shared.Keys{
							ID:  id2,
							Key: key2,
						})
					}
					eventGatewayStaticKeySource := shared.EventGatewayStaticKeySource{
						Type: typeVar6,
						Keys: keys,
					}
					keySources = append(keySources, shared.EventGatewayKeySource{
						EventGatewayStaticKeySource: &eventGatewayStaticKeySource,
					})
				}
			}
			encrypt := make([]shared.EncryptionRecordSelector, 0, len(r.Encrypt.Config.Encrypt))
			for _, encryptItem := range r.Encrypt.Config.Encrypt {
				partOfRecord := shared.EncryptionRecordSelectorPartOfRecord(encryptItem.PartOfRecord.ValueString())
				var keyID string
				keyID = encryptItem.KeyID.ValueString()

				encrypt = append(encrypt, shared.EncryptionRecordSelector{
					PartOfRecord: partOfRecord,
					KeyID:        keyID,
				})
			}
			config2 = &shared.EventGatewayEncryptPolicyConfig{
				FailureMode: failureMode,
				KeySources:  keySources,
				Encrypt:     encrypt,
			}
		}
		labels2 := make(map[string]*string)
		for labelsKey2, labelsValue2 := range r.Encrypt.Labels {
			labelsInst2 := new(string)
			if !labelsValue2.IsUnknown() && !labelsValue2.IsNull() {
				*labelsInst2 = labelsValue2.ValueString()
			} else {
				labelsInst2 = nil
			}
			labels2[labelsKey2] = labelsInst2
		}
		eventGatewayEncryptPolicy = &shared.EventGatewayEncryptPolicy{
			Type:        typeVar4,
			Name:        name4,
			Description: description2,
			Enabled:     enabled2,
			Condition:   condition2,
			Config:      config2,
			Labels:      labels2,
		}
	}
	if eventGatewayEncryptPolicy != nil {
		out = shared.EventGatewayProducePolicyModify{
			EventGatewayEncryptPolicy: eventGatewayEncryptPolicy,
		}
	}

	return &out, diags
}
