// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-konnect-beta/internal/provider/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
)

func (r *MeshHTTPRouteListDataSourceModel) RefreshFromSharedMeshHTTPRouteList(ctx context.Context, resp *shared.MeshHTTPRouteList) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Items = []tfTypes.MeshHTTPRouteItem{}

		for _, itemsItem := range resp.Items {
			var items tfTypes.MeshHTTPRouteItem

			items.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(itemsItem.CreationTime))
			labelsValue, labelsDiags := types.MapValueFrom(ctx, types.StringType, itemsItem.Labels)
			diags.Append(labelsDiags...)
			labelsValuable, labelsDiags := kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}}.ValueFromMap(ctx, labelsValue)
			diags.Append(labelsDiags...)
			items.Labels, _ = labelsValuable.(kumalabels.KumaLabelsMapValue)
			items.Mesh = types.StringPointerValue(itemsItem.Mesh)
			items.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(itemsItem.ModificationTime))
			items.Name = types.StringValue(itemsItem.Name)
			if itemsItem.Spec.TargetRef == nil {
				items.Spec.TargetRef = nil
			} else {
				items.Spec.TargetRef = &tfTypes.MeshAccessLogItemTargetRef{}
				items.Spec.TargetRef.Kind = types.StringValue(string(itemsItem.Spec.TargetRef.Kind))
				if len(itemsItem.Spec.TargetRef.Labels) > 0 {
					items.Spec.TargetRef.Labels = make(map[string]types.String, len(itemsItem.Spec.TargetRef.Labels))
					for key, value := range itemsItem.Spec.TargetRef.Labels {
						items.Spec.TargetRef.Labels[key] = types.StringValue(value)
					}
				}
				items.Spec.TargetRef.Mesh = types.StringPointerValue(itemsItem.Spec.TargetRef.Mesh)
				items.Spec.TargetRef.Name = types.StringPointerValue(itemsItem.Spec.TargetRef.Name)
				items.Spec.TargetRef.Namespace = types.StringPointerValue(itemsItem.Spec.TargetRef.Namespace)
				items.Spec.TargetRef.ProxyTypes = make([]types.String, 0, len(itemsItem.Spec.TargetRef.ProxyTypes))
				for _, v := range itemsItem.Spec.TargetRef.ProxyTypes {
					items.Spec.TargetRef.ProxyTypes = append(items.Spec.TargetRef.ProxyTypes, types.StringValue(string(v)))
				}
				items.Spec.TargetRef.SectionName = types.StringPointerValue(itemsItem.Spec.TargetRef.SectionName)
				if len(itemsItem.Spec.TargetRef.Tags) > 0 {
					items.Spec.TargetRef.Tags = make(map[string]types.String, len(itemsItem.Spec.TargetRef.Tags))
					for key1, value1 := range itemsItem.Spec.TargetRef.Tags {
						items.Spec.TargetRef.Tags[key1] = types.StringValue(value1)
					}
				}
			}
			items.Spec.To = []tfTypes.MeshHTTPRouteItemTo{}

			for _, toItem := range itemsItem.Spec.To {
				var to tfTypes.MeshHTTPRouteItemTo

				to.Hostnames = make([]types.String, 0, len(toItem.Hostnames))
				for _, v := range toItem.Hostnames {
					to.Hostnames = append(to.Hostnames, types.StringValue(v))
				}
				to.Rules = []tfTypes.MeshHTTPRouteItemRules{}

				for _, rulesItem := range toItem.Rules {
					var rules tfTypes.MeshHTTPRouteItemRules

					rules.Default.BackendRefs = []tfTypes.BackendRefs{}

					for _, backendRefsItem := range rulesItem.Default.BackendRefs {
						var backendRefs tfTypes.BackendRefs

						backendRefs.Kind = types.StringValue(string(backendRefsItem.Kind))
						if len(backendRefsItem.Labels) > 0 {
							backendRefs.Labels = make(map[string]types.String, len(backendRefsItem.Labels))
							for key2, value2 := range backendRefsItem.Labels {
								backendRefs.Labels[key2] = types.StringValue(value2)
							}
						}
						backendRefs.Mesh = types.StringPointerValue(backendRefsItem.Mesh)
						backendRefs.Name = types.StringPointerValue(backendRefsItem.Name)
						backendRefs.Namespace = types.StringPointerValue(backendRefsItem.Namespace)
						backendRefs.Port = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(backendRefsItem.Port))
						backendRefs.ProxyTypes = make([]types.String, 0, len(backendRefsItem.ProxyTypes))
						for _, v := range backendRefsItem.ProxyTypes {
							backendRefs.ProxyTypes = append(backendRefs.ProxyTypes, types.StringValue(string(v)))
						}
						backendRefs.SectionName = types.StringPointerValue(backendRefsItem.SectionName)
						if len(backendRefsItem.Tags) > 0 {
							backendRefs.Tags = make(map[string]types.String, len(backendRefsItem.Tags))
							for key3, value3 := range backendRefsItem.Tags {
								backendRefs.Tags[key3] = types.StringValue(value3)
							}
						}
						backendRefs.Weight = types.Int64PointerValue(backendRefsItem.Weight)

						rules.Default.BackendRefs = append(rules.Default.BackendRefs, backendRefs)
					}
					rules.Default.Filters = []tfTypes.Filters{}

					for _, filtersItem := range rulesItem.Default.Filters {
						var filters tfTypes.Filters

						if filtersItem.RequestHeaderModifier == nil {
							filters.RequestHeaderModifier = nil
						} else {
							filters.RequestHeaderModifier = &tfTypes.RequestHeaderModifier{}
							filters.RequestHeaderModifier.Add = []tfTypes.MeshGlobalRateLimitItemAdd{}

							for _, addItem := range filtersItem.RequestHeaderModifier.Add {
								var add tfTypes.MeshGlobalRateLimitItemAdd

								add.Name = types.StringValue(addItem.Name)
								add.Value = types.StringValue(addItem.Value)

								filters.RequestHeaderModifier.Add = append(filters.RequestHeaderModifier.Add, add)
							}
							filters.RequestHeaderModifier.Remove = make([]types.String, 0, len(filtersItem.RequestHeaderModifier.Remove))
							for _, v := range filtersItem.RequestHeaderModifier.Remove {
								filters.RequestHeaderModifier.Remove = append(filters.RequestHeaderModifier.Remove, types.StringValue(v))
							}
							filters.RequestHeaderModifier.Set = []tfTypes.MeshGlobalRateLimitItemAdd{}

							for _, setItem := range filtersItem.RequestHeaderModifier.Set {
								var set tfTypes.MeshGlobalRateLimitItemAdd

								set.Name = types.StringValue(setItem.Name)
								set.Value = types.StringValue(setItem.Value)

								filters.RequestHeaderModifier.Set = append(filters.RequestHeaderModifier.Set, set)
							}
						}
						if filtersItem.RequestMirror == nil {
							filters.RequestMirror = nil
						} else {
							filters.RequestMirror = &tfTypes.RequestMirror{}
							filters.RequestMirror.BackendRef.Kind = types.StringValue(string(filtersItem.RequestMirror.BackendRef.Kind))
							if len(filtersItem.RequestMirror.BackendRef.Labels) > 0 {
								filters.RequestMirror.BackendRef.Labels = make(map[string]types.String, len(filtersItem.RequestMirror.BackendRef.Labels))
								for key4, value4 := range filtersItem.RequestMirror.BackendRef.Labels {
									filters.RequestMirror.BackendRef.Labels[key4] = types.StringValue(value4)
								}
							}
							filters.RequestMirror.BackendRef.Mesh = types.StringPointerValue(filtersItem.RequestMirror.BackendRef.Mesh)
							filters.RequestMirror.BackendRef.Name = types.StringPointerValue(filtersItem.RequestMirror.BackendRef.Name)
							filters.RequestMirror.BackendRef.Namespace = types.StringPointerValue(filtersItem.RequestMirror.BackendRef.Namespace)
							filters.RequestMirror.BackendRef.Port = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(filtersItem.RequestMirror.BackendRef.Port))
							filters.RequestMirror.BackendRef.ProxyTypes = make([]types.String, 0, len(filtersItem.RequestMirror.BackendRef.ProxyTypes))
							for _, v := range filtersItem.RequestMirror.BackendRef.ProxyTypes {
								filters.RequestMirror.BackendRef.ProxyTypes = append(filters.RequestMirror.BackendRef.ProxyTypes, types.StringValue(string(v)))
							}
							filters.RequestMirror.BackendRef.SectionName = types.StringPointerValue(filtersItem.RequestMirror.BackendRef.SectionName)
							if len(filtersItem.RequestMirror.BackendRef.Tags) > 0 {
								filters.RequestMirror.BackendRef.Tags = make(map[string]types.String, len(filtersItem.RequestMirror.BackendRef.Tags))
								for key5, value5 := range filtersItem.RequestMirror.BackendRef.Tags {
									filters.RequestMirror.BackendRef.Tags[key5] = types.StringValue(value5)
								}
							}
							filters.RequestMirror.BackendRef.Weight = types.Int64PointerValue(filtersItem.RequestMirror.BackendRef.Weight)
							if filtersItem.RequestMirror.Percentage != nil {
								filters.RequestMirror.Percentage = &tfTypes.MeshItemMode{}
								if filtersItem.RequestMirror.Percentage.Integer != nil {
									filters.RequestMirror.Percentage.Integer = types.Int64PointerValue(filtersItem.RequestMirror.Percentage.Integer)
								}
								if filtersItem.RequestMirror.Percentage.Str != nil {
									filters.RequestMirror.Percentage.Str = types.StringPointerValue(filtersItem.RequestMirror.Percentage.Str)
								}
							}
						}
						if filtersItem.RequestRedirect == nil {
							filters.RequestRedirect = nil
						} else {
							filters.RequestRedirect = &tfTypes.RequestRedirect{}
							filters.RequestRedirect.Hostname = types.StringPointerValue(filtersItem.RequestRedirect.Hostname)
							if filtersItem.RequestRedirect.Path == nil {
								filters.RequestRedirect.Path = nil
							} else {
								filters.RequestRedirect.Path = &tfTypes.MeshHTTPRouteItemSpecPath{}
								filters.RequestRedirect.Path.ReplaceFullPath = types.StringPointerValue(filtersItem.RequestRedirect.Path.ReplaceFullPath)
								filters.RequestRedirect.Path.ReplacePrefixMatch = types.StringPointerValue(filtersItem.RequestRedirect.Path.ReplacePrefixMatch)
								filters.RequestRedirect.Path.Type = types.StringValue(string(filtersItem.RequestRedirect.Path.Type))
							}
							filters.RequestRedirect.Port = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(filtersItem.RequestRedirect.Port))
							if filtersItem.RequestRedirect.Scheme != nil {
								filters.RequestRedirect.Scheme = types.StringValue(string(*filtersItem.RequestRedirect.Scheme))
							} else {
								filters.RequestRedirect.Scheme = types.StringNull()
							}
							if filtersItem.RequestRedirect.StatusCode != nil {
								filters.RequestRedirect.StatusCode = types.Int64Value(int64(*filtersItem.RequestRedirect.StatusCode))
							} else {
								filters.RequestRedirect.StatusCode = types.Int64Null()
							}
						}
						if filtersItem.ResponseHeaderModifier == nil {
							filters.ResponseHeaderModifier = nil
						} else {
							filters.ResponseHeaderModifier = &tfTypes.RequestHeaderModifier{}
							filters.ResponseHeaderModifier.Add = []tfTypes.MeshGlobalRateLimitItemAdd{}

							for _, addItem1 := range filtersItem.ResponseHeaderModifier.Add {
								var add1 tfTypes.MeshGlobalRateLimitItemAdd

								add1.Name = types.StringValue(addItem1.Name)
								add1.Value = types.StringValue(addItem1.Value)

								filters.ResponseHeaderModifier.Add = append(filters.ResponseHeaderModifier.Add, add1)
							}
							filters.ResponseHeaderModifier.Remove = make([]types.String, 0, len(filtersItem.ResponseHeaderModifier.Remove))
							for _, v := range filtersItem.ResponseHeaderModifier.Remove {
								filters.ResponseHeaderModifier.Remove = append(filters.ResponseHeaderModifier.Remove, types.StringValue(v))
							}
							filters.ResponseHeaderModifier.Set = []tfTypes.MeshGlobalRateLimitItemAdd{}

							for _, setItem1 := range filtersItem.ResponseHeaderModifier.Set {
								var set1 tfTypes.MeshGlobalRateLimitItemAdd

								set1.Name = types.StringValue(setItem1.Name)
								set1.Value = types.StringValue(setItem1.Value)

								filters.ResponseHeaderModifier.Set = append(filters.ResponseHeaderModifier.Set, set1)
							}
						}
						filters.Type = types.StringValue(string(filtersItem.Type))
						if filtersItem.URLRewrite == nil {
							filters.URLRewrite = nil
						} else {
							filters.URLRewrite = &tfTypes.URLRewrite{}
							filters.URLRewrite.Hostname = types.StringPointerValue(filtersItem.URLRewrite.Hostname)
							filters.URLRewrite.HostToBackendHostname = types.BoolPointerValue(filtersItem.URLRewrite.HostToBackendHostname)
							if filtersItem.URLRewrite.Path == nil {
								filters.URLRewrite.Path = nil
							} else {
								filters.URLRewrite.Path = &tfTypes.MeshHTTPRouteItemSpecPath{}
								filters.URLRewrite.Path.ReplaceFullPath = types.StringPointerValue(filtersItem.URLRewrite.Path.ReplaceFullPath)
								filters.URLRewrite.Path.ReplacePrefixMatch = types.StringPointerValue(filtersItem.URLRewrite.Path.ReplacePrefixMatch)
								filters.URLRewrite.Path.Type = types.StringValue(string(filtersItem.URLRewrite.Path.Type))
							}
						}

						rules.Default.Filters = append(rules.Default.Filters, filters)
					}
					rules.Matches = []tfTypes.Matches{}

					for _, matchesItem := range rulesItem.Matches {
						var matches tfTypes.Matches

						matches.Headers = []tfTypes.Headers{}

						for _, headersItem := range matchesItem.Headers {
							var headers tfTypes.Headers

							headers.Name = types.StringValue(headersItem.Name)
							if headersItem.Type != nil {
								headers.Type = types.StringValue(string(*headersItem.Type))
							} else {
								headers.Type = types.StringNull()
							}
							headers.Value = types.StringPointerValue(headersItem.Value)

							matches.Headers = append(matches.Headers, headers)
						}
						if matchesItem.Method != nil {
							matches.Method = types.StringValue(string(*matchesItem.Method))
						} else {
							matches.Method = types.StringNull()
						}
						if matchesItem.Path == nil {
							matches.Path = nil
						} else {
							matches.Path = &tfTypes.Path{}
							matches.Path.Type = types.StringValue(string(matchesItem.Path.Type))
							matches.Path.Value = types.StringValue(matchesItem.Path.Value)
						}
						matches.QueryParams = []tfTypes.QueryParams{}

						for _, queryParamsItem := range matchesItem.QueryParams {
							var queryParams tfTypes.QueryParams

							queryParams.Name = types.StringValue(queryParamsItem.Name)
							queryParams.Type = types.StringValue(string(queryParamsItem.Type))
							queryParams.Value = types.StringValue(queryParamsItem.Value)

							matches.QueryParams = append(matches.QueryParams, queryParams)
						}

						rules.Matches = append(rules.Matches, matches)
					}

					to.Rules = append(to.Rules, rules)
				}
				to.TargetRef.Kind = types.StringValue(string(toItem.TargetRef.Kind))
				if len(toItem.TargetRef.Labels) > 0 {
					to.TargetRef.Labels = make(map[string]types.String, len(toItem.TargetRef.Labels))
					for key6, value6 := range toItem.TargetRef.Labels {
						to.TargetRef.Labels[key6] = types.StringValue(value6)
					}
				}
				to.TargetRef.Mesh = types.StringPointerValue(toItem.TargetRef.Mesh)
				to.TargetRef.Name = types.StringPointerValue(toItem.TargetRef.Name)
				to.TargetRef.Namespace = types.StringPointerValue(toItem.TargetRef.Namespace)
				to.TargetRef.ProxyTypes = make([]types.String, 0, len(toItem.TargetRef.ProxyTypes))
				for _, v := range toItem.TargetRef.ProxyTypes {
					to.TargetRef.ProxyTypes = append(to.TargetRef.ProxyTypes, types.StringValue(string(v)))
				}
				to.TargetRef.SectionName = types.StringPointerValue(toItem.TargetRef.SectionName)
				if len(toItem.TargetRef.Tags) > 0 {
					to.TargetRef.Tags = make(map[string]types.String, len(toItem.TargetRef.Tags))
					for key7, value7 := range toItem.TargetRef.Tags {
						to.TargetRef.Tags[key7] = types.StringValue(value7)
					}
				}

				items.Spec.To = append(items.Spec.To, to)
			}
			items.Type = types.StringValue(string(itemsItem.Type))

			r.Items = append(r.Items, items)
		}
		r.Next = types.StringPointerValue(resp.Next)
		r.Total = types.Float64PointerValue(resp.Total)
	}

	return diags
}

func (r *MeshHTTPRouteListDataSourceModel) ToOperationsGetMeshHTTPRouteListRequest(ctx context.Context) (*operations.GetMeshHTTPRouteListRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cpID string
	cpID = r.CpID.ValueString()

	offset := new(int64)
	if !r.Offset.IsUnknown() && !r.Offset.IsNull() {
		*offset = r.Offset.ValueInt64()
	} else {
		offset = nil
	}
	size := new(int64)
	if !r.Size.IsUnknown() && !r.Size.IsNull() {
		*size = r.Size.ValueInt64()
	} else {
		size = nil
	}
	var filter *operations.GetMeshHTTPRouteListQueryParamFilter
	if r.Filter != nil {
		key := new(string)
		if !r.Filter.Key.IsUnknown() && !r.Filter.Key.IsNull() {
			*key = r.Filter.Key.ValueString()
		} else {
			key = nil
		}
		value := new(string)
		if !r.Filter.Value.IsUnknown() && !r.Filter.Value.IsNull() {
			*value = r.Filter.Value.ValueString()
		} else {
			value = nil
		}
		filter = &operations.GetMeshHTTPRouteListQueryParamFilter{
			Key:   key,
			Value: value,
		}
	}
	var mesh string
	mesh = r.Mesh.ValueString()

	out := operations.GetMeshHTTPRouteListRequest{
		CpID:   cpID,
		Offset: offset,
		Size:   size,
		Filter: filter,
		Mesh:   mesh,
	}

	return &out, diags
}
