// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	custom_listplanmodifier "github.com/kong/terraform-provider-konnect-beta/internal/planmodifiers/listplanmodifier"
	speakeasy_listplanmodifier "github.com/kong/terraform-provider-konnect-beta/internal/planmodifiers/listplanmodifier"
	speakeasy_objectplanmodifier "github.com/kong/terraform-provider-konnect-beta/internal/planmodifiers/objectplanmodifier"
	speakeasy_stringplanmodifier "github.com/kong/terraform-provider-konnect-beta/internal/planmodifiers/stringplanmodifier"
	tfTypes "github.com/kong/terraform-provider-konnect-beta/internal/provider/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &MeshOpenTelemetryBackendResource{}
var _ resource.ResourceWithImportState = &MeshOpenTelemetryBackendResource{}

func NewMeshOpenTelemetryBackendResource() resource.Resource {
	return &MeshOpenTelemetryBackendResource{}
}

// MeshOpenTelemetryBackendResource defines the resource implementation.
type MeshOpenTelemetryBackendResource struct {
	// Provider configured SDK client.
	client *sdk.KonnectBeta
}

// MeshOpenTelemetryBackendResourceModel describes the resource data model.
type MeshOpenTelemetryBackendResourceModel struct {
	CpID             types.String                              `tfsdk:"cp_id"`
	CreationTime     types.String                              `tfsdk:"creation_time"`
	Kri              types.String                              `tfsdk:"kri"`
	Labels           kumalabels.KumaLabelsMapValue             `tfsdk:"labels"`
	Mesh             types.String                              `tfsdk:"mesh"`
	ModificationTime types.String                              `tfsdk:"modification_time"`
	Name             types.String                              `tfsdk:"name"`
	Spec             *tfTypes.MeshOpenTelemetryBackendItemSpec `tfsdk:"spec"`
	Status           *tfTypes.Status                           `tfsdk:"status"`
	Type             types.String                              `tfsdk:"type"`
	Warnings         []types.String                            `tfsdk:"warnings"`
}

func (r *MeshOpenTelemetryBackendResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "konnect_mesh_open_telemetry_backend"
}

func (r *MeshOpenTelemetryBackendResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "MeshOpenTelemetryBackend Resource",
		Attributes: map[string]schema.Attribute{
			"cp_id": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
				Description: `Id of the Konnect resource. Requires replacement if changed.`,
			},
			"creation_time": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `Time at which the resource was created`,
			},
			"kri": schema.StringAttribute{
				Computed:    true,
				Description: `A unique identifier for this resource instance used by internal tooling and integrations. Typically derived from resource attributes and may be used for cross-references or indexing`,
			},
			"labels": schema.MapAttribute{
				CustomType:  kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}},
				Computed:    true,
				Optional:    true,
				Default:     kumalabels.EmptyKumaLabelsMapDefault{},
				ElementType: types.StringType,
				Description: `The labels to help identity resources`,
			},
			"mesh": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
				Description: `name of the mesh. Requires replacement if changed.`,
			},
			"modification_time": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `Time at which the resource was updated`,
			},
			"name": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
				Description: `name of the MeshOpenTelemetryBackend. Requires replacement if changed.`,
			},
			"spec": schema.SingleNestedAttribute{
				Required: true,
				Attributes: map[string]schema.Attribute{
					"endpoint": schema.SingleNestedAttribute{
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"address": schema.StringAttribute{
								Optional: true,
								MarkdownDescription: `Address of the OTel collector (hostname or IP).` + "\n" +
									`When omitted, kuma-dp resolves it at runtime using HOST_IP or 127.0.0.1.`,
							},
							"path": schema.StringAttribute{
								Optional: true,
								MarkdownDescription: `Path is an optional base path prefix for HTTP endpoints.` + "\n" +
									`The CP appends signal-specific suffixes (/v1/traces, /v1/metrics, /v1/logs).` + "\n" +
									`Non-empty value is rejected by validation when protocol is grpc.`,
							},
							"port": schema.Int32Attribute{
								Optional:    true,
								Description: `Port of the OTel collector. Defaults to 4317 when omitted.`,
							},
						},
						MarkdownDescription: `Endpoint optionally defines the OTel collector address and port.` + "\n" +
							`When omitted, the CP defaults port to 4317 and leaves address empty;` + "\n" +
							`kuma-dp resolves the address at runtime using HOST_IP or 127.0.0.1.`,
					},
					"env": schema.SingleNestedAttribute{
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"allow_signal_overrides": schema.BoolAttribute{
								Optional: true,
								MarkdownDescription: `AllowSignalOverrides controls whether per-signal OTEL env vars` + "\n" +
									`(OTEL_EXPORTER_OTLP_TRACES_*, OTEL_EXPORTER_OTLP_METRICS_*,` + "\n" +
									`OTEL_EXPORTER_OTLP_LOGS_*) may diverge from the shared` + "\n" +
									`OTEL_EXPORTER_OTLP_* values.` + "\n" +
									`true (default): per-signal vars override the shared values for that` + "\n" +
									`signal.` + "\n" +
									`false: per-signal vars are ignored; the shared values apply to all` + "\n" +
									`signals. When per-signal overrides are dropped this way,` + "\n" +
									`SignalOverridesDisallowed appears in blockedReasons (a soft block -` + "\n" +
									`export still works via the shared config).`,
							},
							"mode": schema.StringAttribute{
								Computed: true,
								Optional: true,
								Default:  stringdefault.StaticString(`Optional`),
								MarkdownDescription: `Mode controls whether OTEL env vars participate in the merge.` + "\n" +
									`Disabled: env vars are skipped entirely; only explicit backend fields and` + "\n" +
									`built-in defaults apply.` + "\n" +
									`Optional (default): env vars are used when present; absence is fine.` + "\n" +
									`Required: env vars must supply the missing fields - if any required field` + "\n" +
									`is missing the signal is blocked (state: missing, RequiredEnvMissing in` + "\n" +
									`blockedReasons) even when an explicit value or default could fill it.` + "\n" +
									`possible known values include one of ["Disabled", "Optional", "Required"]; Default: "Optional"`,
							},
							"precedence": schema.StringAttribute{
								Computed: true,
								Optional: true,
								Default:  stringdefault.StaticString(`EnvFirst`),
								MarkdownDescription: `Precedence controls which source wins when both an explicit backend field` + "\n" +
									`and an env var are present for the same field.` + "\n" +
									`EnvFirst (default): env vars win; explicit backend fields fill gaps.` + "\n" +
									`ExplicitFirst: explicit backend fields win; env vars fill gaps.` + "\n" +
									`In either case, built-in defaults are the last fallback.` + "\n" +
									`possible known values include one of ["ExplicitFirst", "EnvFirst"]; Default: "EnvFirst"`,
							},
						},
						MarkdownDescription: `Env controls whether standard OTEL exporter env vars participate in the` + "\n" +
							`final exporter config for this backend.` + "\n" +
							`Defaults to mode: Optional, precedence: EnvFirst, allowSignalOverrides: true` + "\n" +
							`when omitted.`,
					},
					"protocol": schema.StringAttribute{
						Optional: true,
						MarkdownDescription: `Protocol selects gRPC or HTTP transport for the collector connection.` + "\n" +
							`Defaults to grpc when omitted.` + "\n" +
							`possible known values include one of ["grpc", "http"]`,
					},
				},
				Description: `Spec is the specification of the Kuma MeshOpenTelemetryBackend resource.`,
			},
			"status": schema.SingleNestedAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.Object{
					speakeasy_objectplanmodifier.SuppressDiff(speakeasy_objectplanmodifier.ExplicitSuppress),
				},
				Attributes: map[string]schema.Attribute{
					"conditions": schema.ListNestedAttribute{
						Computed: true,
						PlanModifiers: []planmodifier.List{
							custom_listplanmodifier.SupressZeroNullModifier(),
							speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
						},
						NestedObject: schema.NestedAttributeObject{
							PlanModifiers: []planmodifier.Object{
								speakeasy_objectplanmodifier.SuppressDiff(speakeasy_objectplanmodifier.ExplicitSuppress),
							},
							Attributes: map[string]schema.Attribute{
								"message": schema.StringAttribute{
									Computed: true,
									MarkdownDescription: `message is a human readable message indicating details about the transition.` + "\n" +
										`This may be an empty string.`,
								},
								"reason": schema.StringAttribute{
									Computed: true,
									MarkdownDescription: `reason contains a programmatic identifier indicating the reason for the condition's last transition.` + "\n" +
										`Producers of specific condition types may define expected values and meanings for this field,` + "\n" +
										`and whether the values are considered a guaranteed API.` + "\n" +
										`The value should be a CamelCase string.` + "\n" +
										`This field may not be empty.`,
								},
								"status": schema.StringAttribute{
									Computed: true,
									PlanModifiers: []planmodifier.String{
										speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
									},
									Description: `status of the condition, one of True, False, Unknown.`,
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Description: `type of condition in CamelCase or in foo.example.com/CamelCase.`,
								},
							},
						},
					},
				},
				Description: `Status is the current status of the Kuma MeshOpenTelemetryBackend resource.`,
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: `the type of the resource. must be "MeshOpenTelemetryBackend"`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"MeshOpenTelemetryBackend",
					),
				},
			},
			"warnings": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				ElementType: types.StringType,
				MarkdownDescription: `warnings is a list of warning messages to return to the requesting Kuma API clients.` + "\n" +
					`Warning messages describe a problem the client making the API request should correct or be aware of.`,
			},
		},
	}
}

func (r *MeshOpenTelemetryBackendResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.KonnectBeta)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.KonnectBeta, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *MeshOpenTelemetryBackendResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *MeshOpenTelemetryBackendResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsPutMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.MeshOpenTelemetryBackend.PutMeshOpenTelemetryBackend(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 201:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.MeshOpenTelemetryBackendCreateOrUpdateSuccessResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedMeshOpenTelemetryBackendCreateOrUpdateSuccessResponse(ctx, res.MeshOpenTelemetryBackendCreateOrUpdateSuccessResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	request1, request1Diags := data.ToOperationsGetMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(request1Diags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res1, err := r.client.MeshOpenTelemetryBackend.GetMeshOpenTelemetryBackend(ctx, *request1)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res1 != nil && res1.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res1.RawResponse))
		}
		return
	}
	if res1 == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res1))
		return
	}
	if res1.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res1.StatusCode), debugResponse(res1.RawResponse))
		return
	}
	if !(res1.MeshOpenTelemetryBackendItem != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res1.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedMeshOpenTelemetryBackendItem(ctx, res1.MeshOpenTelemetryBackendItem)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MeshOpenTelemetryBackendResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *MeshOpenTelemetryBackendResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.MeshOpenTelemetryBackend.GetMeshOpenTelemetryBackend(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.MeshOpenTelemetryBackendItem != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedMeshOpenTelemetryBackendItem(ctx, res.MeshOpenTelemetryBackendItem)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MeshOpenTelemetryBackendResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *MeshOpenTelemetryBackendResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsPutMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.MeshOpenTelemetryBackend.PutMeshOpenTelemetryBackend(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 201:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.MeshOpenTelemetryBackendCreateOrUpdateSuccessResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedMeshOpenTelemetryBackendCreateOrUpdateSuccessResponse(ctx, res.MeshOpenTelemetryBackendCreateOrUpdateSuccessResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	request1, request1Diags := data.ToOperationsGetMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(request1Diags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res1, err := r.client.MeshOpenTelemetryBackend.GetMeshOpenTelemetryBackend(ctx, *request1)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res1 != nil && res1.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res1.RawResponse))
		}
		return
	}
	if res1 == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res1))
		return
	}
	if res1.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res1.StatusCode), debugResponse(res1.RawResponse))
		return
	}
	if !(res1.MeshOpenTelemetryBackendItem != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res1.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedMeshOpenTelemetryBackendItem(ctx, res1.MeshOpenTelemetryBackendItem)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MeshOpenTelemetryBackendResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *MeshOpenTelemetryBackendResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsDeleteMeshOpenTelemetryBackendRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.MeshOpenTelemetryBackend.DeleteMeshOpenTelemetryBackend(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *MeshOpenTelemetryBackendResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	dec := json.NewDecoder(bytes.NewReader([]byte(req.ID)))
	dec.DisallowUnknownFields()
	var data struct {
		CpID string `json:"cp_id"`
		Mesh string `json:"mesh"`
		Name string `json:"name"`
	}

	if err := dec.Decode(&data); err != nil {
		resp.Diagnostics.AddError("Invalid ID", `The import ID is not valid. It is expected to be a JSON object string with the format: '{"cp_id": "bf138ba2-c9b1-4229-b268-04d9d8a6410b", "mesh": "...", "name": "..."}': `+err.Error())
		return
	}

	if len(data.CpID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field cp_id is required but was not found in the json encoded ID. It's expected to be a value alike '"bf138ba2-c9b1-4229-b268-04d9d8a6410b"'`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("cp_id"), data.CpID)...)
	if len(data.Mesh) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field mesh is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("mesh"), data.Mesh)...)
	if len(data.Name) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field name is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), data.Name)...)
}
