// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-konnect-beta/internal/provider/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
)

func (r *MeshOpenTelemetryBackendResourceModel) RefreshFromSharedMeshOpenTelemetryBackendCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.MeshOpenTelemetryBackendCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshOpenTelemetryBackendResourceModel) RefreshFromSharedMeshOpenTelemetryBackendItem(ctx context.Context, resp *shared.MeshOpenTelemetryBackendItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Kri = types.StringPointerValue(resp.Kri)
		labelsValue, labelsDiags := types.MapValueFrom(ctx, types.StringType, resp.Labels)
		diags.Append(labelsDiags...)
		labelsValuable, labelsDiags := kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}}.ValueFromMap(ctx, labelsValue)
		diags.Append(labelsDiags...)
		r.Labels, _ = labelsValuable.(kumalabels.KumaLabelsMapValue)
		r.Mesh = types.StringPointerValue(resp.Mesh)
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Spec = &tfTypes.MeshOpenTelemetryBackendItemSpec{}
		if resp.Spec.Endpoint == nil {
			r.Spec.Endpoint = nil
		} else {
			r.Spec.Endpoint = &tfTypes.Endpoint{}
			r.Spec.Endpoint.Address = types.StringPointerValue(resp.Spec.Endpoint.Address)
			r.Spec.Endpoint.Path = types.StringPointerValue(resp.Spec.Endpoint.Path)
			r.Spec.Endpoint.Port = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Spec.Endpoint.Port))
		}
		if resp.Spec.Env == nil {
			r.Spec.Env = nil
		} else {
			r.Spec.Env = &tfTypes.Env{}
			r.Spec.Env.AllowSignalOverrides = types.BoolPointerValue(resp.Spec.Env.AllowSignalOverrides)
			if resp.Spec.Env.Mode != nil {
				r.Spec.Env.Mode = types.StringValue(string(*resp.Spec.Env.Mode))
			} else {
				r.Spec.Env.Mode = types.StringNull()
			}
			if resp.Spec.Env.Precedence != nil {
				r.Spec.Env.Precedence = types.StringValue(string(*resp.Spec.Env.Precedence))
			} else {
				r.Spec.Env.Precedence = types.StringNull()
			}
		}
		if resp.Spec.Protocol != nil {
			r.Spec.Protocol = types.StringValue(string(*resp.Spec.Protocol))
		} else {
			r.Spec.Protocol = types.StringNull()
		}
		if resp.Status == nil {
			r.Status = nil
		} else {
			r.Status = &tfTypes.MeshAccessLogItemStatus{}
			r.Status.Conditions = []tfTypes.Conditions{}

			for _, conditionsItem := range resp.Status.Conditions {
				var conditions tfTypes.Conditions

				conditions.Message = types.StringValue(conditionsItem.Message)
				conditions.Reason = types.StringValue(conditionsItem.Reason)
				conditions.Status = types.StringValue(string(conditionsItem.Status))
				conditions.Type = types.StringValue(conditionsItem.Type)

				r.Status.Conditions = append(r.Status.Conditions, conditions)
			}
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *MeshOpenTelemetryBackendResourceModel) ToOperationsDeleteMeshOpenTelemetryBackendRequest(ctx context.Context) (*operations.DeleteMeshOpenTelemetryBackendRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cpID string
	cpID = r.CpID.ValueString()

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteMeshOpenTelemetryBackendRequest{
		CpID: cpID,
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshOpenTelemetryBackendResourceModel) ToOperationsGetMeshOpenTelemetryBackendRequest(ctx context.Context) (*operations.GetMeshOpenTelemetryBackendRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cpID string
	cpID = r.CpID.ValueString()

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.GetMeshOpenTelemetryBackendRequest{
		CpID: cpID,
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshOpenTelemetryBackendResourceModel) ToOperationsPutMeshOpenTelemetryBackendRequest(ctx context.Context) (*operations.PutMeshOpenTelemetryBackendRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cpID string
	cpID = r.CpID.ValueString()

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	meshOpenTelemetryBackendItem, meshOpenTelemetryBackendItemDiags := r.ToSharedMeshOpenTelemetryBackendItemInput(ctx)
	diags.Append(meshOpenTelemetryBackendItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutMeshOpenTelemetryBackendRequest{
		CpID:                         cpID,
		Mesh:                         mesh,
		Name:                         name,
		MeshOpenTelemetryBackendItem: *meshOpenTelemetryBackendItem,
	}

	return &out, diags
}

func (r *MeshOpenTelemetryBackendResourceModel) ToSharedMeshOpenTelemetryBackendItemInput(ctx context.Context) (*shared.MeshOpenTelemetryBackendItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := shared.MeshOpenTelemetryBackendItemType(r.Type.ValueString())
	mesh := new(string)
	if !r.Mesh.IsUnknown() && !r.Mesh.IsNull() {
		*mesh = r.Mesh.ValueString()
	} else {
		mesh = nil
	}
	var name string
	name = r.Name.ValueString()

	var labels map[string]string
	if !r.Labels.IsUnknown() && !r.Labels.IsNull() {
		diags.Append(r.Labels.ElementsAs(ctx, &labels, true)...)
	}
	var endpoint *shared.Endpoint
	if r.Spec.Endpoint != nil {
		address := new(string)
		if !r.Spec.Endpoint.Address.IsUnknown() && !r.Spec.Endpoint.Address.IsNull() {
			*address = r.Spec.Endpoint.Address.ValueString()
		} else {
			address = nil
		}
		path := new(string)
		if !r.Spec.Endpoint.Path.IsUnknown() && !r.Spec.Endpoint.Path.IsNull() {
			*path = r.Spec.Endpoint.Path.ValueString()
		} else {
			path = nil
		}
		port := new(int)
		if !r.Spec.Endpoint.Port.IsUnknown() && !r.Spec.Endpoint.Port.IsNull() {
			*port = int(r.Spec.Endpoint.Port.ValueInt32())
		} else {
			port = nil
		}
		endpoint = &shared.Endpoint{
			Address: address,
			Path:    path,
			Port:    port,
		}
	}
	var env *shared.Env
	if r.Spec.Env != nil {
		allowSignalOverrides := new(bool)
		if !r.Spec.Env.AllowSignalOverrides.IsUnknown() && !r.Spec.Env.AllowSignalOverrides.IsNull() {
			*allowSignalOverrides = r.Spec.Env.AllowSignalOverrides.ValueBool()
		} else {
			allowSignalOverrides = nil
		}
		mode := new(shared.MeshOpenTelemetryBackendItemMode)
		if !r.Spec.Env.Mode.IsUnknown() && !r.Spec.Env.Mode.IsNull() {
			*mode = shared.MeshOpenTelemetryBackendItemMode(r.Spec.Env.Mode.ValueString())
		} else {
			mode = nil
		}
		precedence := new(shared.Precedence)
		if !r.Spec.Env.Precedence.IsUnknown() && !r.Spec.Env.Precedence.IsNull() {
			*precedence = shared.Precedence(r.Spec.Env.Precedence.ValueString())
		} else {
			precedence = nil
		}
		env = &shared.Env{
			AllowSignalOverrides: allowSignalOverrides,
			Mode:                 mode,
			Precedence:           precedence,
		}
	}
	protocol := new(shared.MeshOpenTelemetryBackendItemProtocol)
	if !r.Spec.Protocol.IsUnknown() && !r.Spec.Protocol.IsNull() {
		*protocol = shared.MeshOpenTelemetryBackendItemProtocol(r.Spec.Protocol.ValueString())
	} else {
		protocol = nil
	}
	spec := shared.MeshOpenTelemetryBackendItemSpec{
		Endpoint: endpoint,
		Env:      env,
		Protocol: protocol,
	}
	out := shared.MeshOpenTelemetryBackendItemInput{
		Type:   typeVar,
		Mesh:   mesh,
		Name:   name,
		Labels: labels,
		Spec:   spec,
	}

	return &out, diags
}
