// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-konnect-beta/internal/provider/types"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect-beta/internal/sdk/models/shared"
)

func (r *PortalDeveloperResourceModel) RefreshFromSharedPortalDeveloper(ctx context.Context, resp *shared.PortalDeveloper) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.AdditionalData) > 0 {
			r.AdditionalData = make(map[string]tfTypes.FormResponseInput, len(resp.AdditionalData))
			for formResponseInputKey := range resp.AdditionalData {
				var formResponseInputResult tfTypes.FormResponseInput

				r.AdditionalData[formResponseInputKey] = formResponseInputResult
			}
		}
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Email = types.StringValue(resp.Email)
		r.FullName = types.StringValue(resp.FullName)
		r.ID = types.StringValue(resp.ID)
		r.Status = types.StringValue(string(resp.Status))
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
	}

	return diags
}

func (r *PortalDeveloperResourceModel) ToOperationsCreateDeveloperRequest(ctx context.Context) (*operations.CreateDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.PortalID.ValueString()

	createDeveloperRequest, createDeveloperRequestDiags := r.ToSharedCreateDeveloperRequest(ctx)
	diags.Append(createDeveloperRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateDeveloperRequest{
		PortalID:               portalID,
		CreateDeveloperRequest: *createDeveloperRequest,
	}

	return &out, diags
}

func (r *PortalDeveloperResourceModel) ToOperationsDeleteDeveloperRequest(ctx context.Context) (*operations.DeleteDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.PortalID.ValueString()

	var developerID string
	developerID = r.ID.ValueString()

	out := operations.DeleteDeveloperRequest{
		PortalID:    portalID,
		DeveloperID: developerID,
	}

	return &out, diags
}

func (r *PortalDeveloperResourceModel) ToOperationsGetDeveloperRequest(ctx context.Context) (*operations.GetDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.PortalID.ValueString()

	var developerID string
	developerID = r.ID.ValueString()

	out := operations.GetDeveloperRequest{
		PortalID:    portalID,
		DeveloperID: developerID,
	}

	return &out, diags
}

func (r *PortalDeveloperResourceModel) ToOperationsUpdateDeveloperRequest(ctx context.Context) (*operations.UpdateDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.PortalID.ValueString()

	var developerID string
	developerID = r.ID.ValueString()

	updateDeveloperRequest, updateDeveloperRequestDiags := r.ToSharedUpdateDeveloperRequest(ctx)
	diags.Append(updateDeveloperRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateDeveloperRequest{
		PortalID:               portalID,
		DeveloperID:            developerID,
		UpdateDeveloperRequest: *updateDeveloperRequest,
	}

	return &out, diags
}

func (r *PortalDeveloperResourceModel) ToSharedCreateDeveloperRequest(ctx context.Context) (*shared.CreateDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var email string
	email = r.Email.ValueString()

	var fullName string
	fullName = r.FullName.ValueString()

	status := new(shared.CreateDeveloperRequestDeveloperStatus)
	if !r.Status.IsUnknown() && !r.Status.IsNull() {
		*status = shared.CreateDeveloperRequestDeveloperStatus(r.Status.ValueString())
	} else {
		status = nil
	}
	sendInvitationEmail := new(bool)
	if !r.SendInvitationEmail.IsUnknown() && !r.SendInvitationEmail.IsNull() {
		*sendInvitationEmail = r.SendInvitationEmail.ValueBool()
	} else {
		sendInvitationEmail = nil
	}
	additionalData := make(map[string]shared.FormResponseInput)
	for additionalDataKey := range r.AdditionalData {
		var additionalDataInst shared.FormResponseInput
		str := new(string)
		if !r.AdditionalData[additionalDataKey].Str.IsUnknown() && !r.AdditionalData[additionalDataKey].Str.IsNull() {
			*str = r.AdditionalData[additionalDataKey].Str.ValueString()
		} else {
			str = nil
		}
		if str != nil {
			additionalDataInst = shared.FormResponseInput{
				Str: str,
			}
		}
		number := new(float64)
		if !r.AdditionalData[additionalDataKey].Number.IsUnknown() && !r.AdditionalData[additionalDataKey].Number.IsNull() {
			*number = r.AdditionalData[additionalDataKey].Number.ValueFloat64()
		} else {
			number = nil
		}
		if number != nil {
			additionalDataInst = shared.FormResponseInput{
				Number: number,
			}
		}
		boolean := new(bool)
		if !r.AdditionalData[additionalDataKey].Boolean.IsUnknown() && !r.AdditionalData[additionalDataKey].Boolean.IsNull() {
			*boolean = r.AdditionalData[additionalDataKey].Boolean.ValueBool()
		} else {
			boolean = nil
		}
		if boolean != nil {
			additionalDataInst = shared.FormResponseInput{
				Boolean: boolean,
			}
		}
		var arrayOfStr []string
		if r.AdditionalData[additionalDataKey].ArrayOfStr != nil {
			arrayOfStr = make([]string, 0, len(r.AdditionalData[additionalDataKey].ArrayOfStr))
			for arrayOfStrIndex := range r.AdditionalData[additionalDataKey].ArrayOfStr {
				arrayOfStr = append(arrayOfStr, r.AdditionalData[additionalDataKey].ArrayOfStr[arrayOfStrIndex].ValueString())
			}
		}
		if arrayOfStr != nil {
			additionalDataInst = shared.FormResponseInput{
				ArrayOfStr: arrayOfStr,
			}
		}
		additionalData[additionalDataKey] = additionalDataInst
	}
	out := shared.CreateDeveloperRequest{
		Email:               email,
		FullName:            fullName,
		Status:              status,
		SendInvitationEmail: sendInvitationEmail,
		AdditionalData:      additionalData,
	}

	return &out, diags
}

func (r *PortalDeveloperResourceModel) ToSharedUpdateDeveloperRequest(ctx context.Context) (*shared.UpdateDeveloperRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	status := new(shared.DeveloperStatus)
	if !r.Status.IsUnknown() && !r.Status.IsNull() {
		*status = shared.DeveloperStatus(r.Status.ValueString())
	} else {
		status = nil
	}
	out := shared.UpdateDeveloperRequest{
		Status: status,
	}

	return &out, diags
}
