// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AIGatewayMCPServerListenerConsumer struct {
	Acls              *AIGatewayACLS                               `tfsdk:"acls"`
	DefaultToolAcls   *AIGatewayACLS                               `tfsdk:"default_tool_acls"`
	IdentityProviders []types.String                               `tfsdk:"identity_providers"`
	Metadata          *AIGatewayMCPServerProtectedResourceMetadata `tfsdk:"metadata"`
}
