// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type AIGatewayMCPServerBaseACLProperties struct {
	Consumer         *AIGatewayMCPServerBaseACLPropertiesConsumer `queryParam:"inline" tfsdk:"consumer"`
	OauthAccessToken *AIGatewayMCPServerBaseACLPropertiesOauth    `queryParam:"inline" tfsdk:"oauth_access_token"`
}
