// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type AIGatewayACLS struct {
	AIGatewayAllowACL *AIGatewayAllowACL `queryParam:"inline" tfsdk:"ai_gateway_allow_acl"`
	AIGatewayDenyACL  *AIGatewayDenyACL  `queryParam:"inline" tfsdk:"ai_gateway_deny_acl"`
}
