// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AIGatewayMCPServerBaseACLPropertiesOauth struct {
	AccessTokenClaimField types.String      `tfsdk:"access_token_claim_field"`
	ACLAttributeType      types.String      `tfsdk:"acl_attribute_type"`
	Acls                  *AIGatewayMCPACLs `tfsdk:"acls"`
	DefaultToolAcls       *AIGatewayMCPACLs `tfsdk:"default_tool_acls"`
}
