// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type EventGatewayDecryptPolicyConfig struct {
	Decrypt     []DecryptionRecordSelector `tfsdk:"decrypt"`
	FailureMode types.String               `tfsdk:"failure_mode"`
	KeySources  []EventGatewayKeySource    `tfsdk:"key_sources"`
}
