// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type EventGatewayACLRule struct {
	Action        types.String                    `tfsdk:"action"`
	Operations    []VirtualClusterReferenceByName `tfsdk:"operations"`
	ResourceNames []EventGatewayACLResourceName   `tfsdk:"resource_names"`
	ResourceType  types.String                    `tfsdk:"resource_type"`
}
