// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshRetryItemSpec struct {
	TargetRef *TargetRef        `tfsdk:"target_ref"`
	To        []MeshRetryItemTo `tfsdk:"to"`
}
