// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshRetryItemTo struct {
	Default   *MeshRetryItemDefault `tfsdk:"default"`
	TargetRef *TargetRef            `tfsdk:"target_ref"`
}
