// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MeshZoneAddressItemSpec struct {
	Address types.String `tfsdk:"address"`
	Port    types.Int32  `tfsdk:"port"`
}
