// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ResourceNames struct {
	ArrayOfEventGatewayACLResourceName []EventGatewayACLResourceName `queryParam:"inline" tfsdk:"array_of_event_gateway_acl_resource_name" tfPlanOnly:"true"`
	Str                                types.String                  `queryParam:"inline" tfsdk:"str" tfPlanOnly:"true"`
}
