// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Size struct {
	Cols types.Int64 `tfsdk:"cols"`
	Rows types.Int64 `tfsdk:"rows"`
}
