// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type TableVisualization struct {
	Chart *ChoroplethMapChart      `tfsdk:"chart"`
	Query *TableVisualizationQuery `tfsdk:"query"`
}
