// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type TimeRange struct {
	Absolute *MetricsAbsoluteTimeRangeDtoV2 `queryParam:"inline" tfsdk:"absolute"`
	Relative *MetricsRelativeTimeRangeDtoV2 `queryParam:"inline" tfsdk:"relative"`
}
