// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type VirtualClusterNamespaceIDSelectorExactList struct {
	ExactList []ExactList  `tfsdk:"exact_list"`
	Type      types.String `tfsdk:"type"`
}
