name: Run Speakeasy on PR Open

on:
  workflow_dispatch: {}
  # pull_request:
  #   types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  speakeasy-on-pr-open:
    name: Run Speakeasy on PR Open
    # if: ${{ github.event.pull_request.head.ref == 'feat/platform-api-automated-update' }}
    runs-on: ubuntu-latest
    concurrency:
      group: speakeasy-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: feat/platform-api-automated-update

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Speakeasy
        run: make speakeasy

      - name: Commit & push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(ci): speakeasy auto-update on PR open"
            git push origin HEAD:feat/platform-api-automated-update
          else
            echo "No changes to commit."
          fi

