name: Run Speakeasy on PR Open

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'examples/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'feat/platform-api-automated-update'

permissions:
  contents: write
  pull-requests: write

jobs:
  speakeasy-on-pr-open:
    env:
      REF: ${{ github.event.pull_request.head.ref || github.event.inputs.branch }}
    name: Run Speakeasy on PR Open
    if: github.event.pull_request.head.ref == 'feat/platform-api-automated-update' ||
      github.event_name == 'workflow_dispatch' ||
      github.actor == 'renovate[bot]' ||
      github.actor == 'mend[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: speakeasy-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Install Speakeasy
        uses: mheap/setup-go-cli@fa9b01cdd4115eac636164f0de43bf7d51c82697 # v1
        with:
          owner: speakeasy-api
          repo: speakeasy
          cli_name: speakeasy
          package_type: zip

      - name: Configure speakeasy CLI
        run: |
          mkdir -p ~/.speakeasy
          echo 'speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}' > ~/.speakeasy/config.yaml

      - name: Generate GitHub app token
        id: github-app-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ vars.KONG_MESH_APP_ID }}
          private-key: ${{ secrets.KONG_MESH_APP_PRIVATE_KEY }}

      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ env.REF }}
          path: repo
          fetch-depth: 0
          token: ${{ steps.github-app-token.outputs.token }}

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: repo/go.mod

      - name: Install staticcheck
        working-directory: repo
        run: |
          set -x
          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Set up Git identity
        working-directory: repo
        run: |
          git config user.name "kong-mesh[bot]"
          git config user.email "123109030+kong-mesh[bot]@users.noreply.github.com"

      - name: Run Generators
        working-directory: repo
        run: make generate

      - name: Commit & push changes (if any)
        working-directory: repo
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(ci): speakeasy auto-update on PR open"
            git push
          else
            echo "No changes to commit."
          fi
